### ISSUE TITLE
`SoftBody3D` vs `SoftBody3D` collision and self-collision

### ISSUE THREAD

**Issue by Daerpion** [godot-jolt/godot-jolt#1000]
Hello. I'm not sure if i should open the issue.
This has been mentioned [here](https://github.com/godot-jolt/godot-jolt/issues/503#issuecomment-1646630711) 
So do you plan to implement this, or do we have to wait for Godot to implement it first? Even though they've been ignoring the problem for five years.

**Comment by mihe** [comment]
This isn't something that can be implemented from this extension alone. It's something that would need to be added to Jolt itself, and is tracked in this issue: jrouwe/JoltPhysics#789

It was left out in part because Godot Physics doesn't support it either, so wasn't deemed necessary for feature parity, as seen below the comment you linked. I assume it's not a trivial problem to solve.

**Comment by mihe** [comment]
With this extension now having been merged into Godot in the form of an engine module (see [README](https://github.com/godot-jolt/godot-jolt?tab=readme-ov-file)), it will be considered to be in maintenance mode going forward, where only bug fixes will be considered for merging. As such, I'll go ahead and close this.

This will instead be addressed for the new engine module by adding freezing support to `PhysicalBone3D`, as mentioned in my previous comment.
