### ISSUE TITLE
Custom inertia isn't implemented correctly

### ISSUE THREAD

**Issue by NatCracken** [godot-jolt/godot-jolt#1012]
Versions: Godot v4.3.stable.mono, godot-jolt 0.14.0-stable 3392156fab

Sys Information: Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz (12 Threads),

When attempting to set a custom inertia value on a RigidBody3d which has a ConvexPolygonShape3D, only the X value will be applied correctly. The Y and Z value are set to an extremely large negative value. These incorrect axis resist forces, so its something wrong with how the backend numbers are set unlike #798

You can reproduce using this project https://github.com/NatCracken/inertia_test/tree/main
There are two shapes, they both have cube meshes and the same custom inertia values, but their colliders are different. The left has a capsule mesh, the right a custom collision mesh (the bounds of a helicopter cause that's whats causing problems in my actual project). They will print what is being reported as their inertia in the console, and have both been set to experience constant torque on every axis. You should observe the custom collider only rotating around its local x (the axis that gets set correctly) and some quirked up values being printed for its y and z inertia

**Comment by mihe** [comment]
@jrouwe Any chance I could ask you for some guidance here? It's clear that [my implementation](https://github.com/godot-jolt/godot-jolt/blob/dfbf40e322654b63f595c22ea30da4530f7d32b8/src/objects/jolt_body_impl_3d.cpp#L1280-L1309) of custom inertia was too naive and just not correct, and clearly I never tested this with more complex shapes, like the one in the repro here.

I'm pushing the limits of my own understanding here, but basically Godot lets you specify a custom inertia _diagonal_ for a body, which is set to `(0, 0, 0)` by default, and any value left at zero is supposed to be whatever the physics engine calculated automatically (with some caveats mentioned below).

So if we take this `king_stallion_shape` in the provided repro as an example, and you set the custom inertia to `(100, 100, 100)`, then Godot Physics will report the local-space diagonal of the body as being `(100, 100, 100)` and its local-space principal axes as being identity, but with Godot Jolt you end up failing on [the validation](https://github.com/jrouwe/JoltPhysics/blob/d6e015372b08f28c3c62e9aaab9a5cb2af667e54/Jolt/Physics/Body/MassProperties.cpp#L51-L57) in `JPH::MassProperties::DecomposePrincipalMomentsOfInertia` and the local-space diagonal is subsequently reported as `(100.0012, -3079325440, -3017010176)` and the local-space principal axes as `[(-0.000007, 0.707107, -0.707107), (1, 0.000039, 0.000029), (0.000048, -0.707107, -0.707107)]`.

If I wanted to mimick that particular behavior of Godot Physics I imagine I could just overwrite the entire inertia tensor with identity and overwrite the diagonal whenever every component of the custom inertia is set to a non-zero value.

However, where things get weird is if you leave one or more components at zero, which is supposed to be something that's allowed, although the documentation makes no mention of it. In this case Godot Physics actually goes through and calculates the inertia tensor properly (?) based on the moments of inertia of all its shapes, albeit with a seemingly [simplistic approximation](https://github.com/godotengine/godot/blob/76fa7b291455a8ba24c50005072ebdb58f8a5984/modules/godot_physics_3d/godot_shape_3d.cpp#L1087-L1095) for hull shapes, but then runs it through [`Basis::diagonalize`](https://github.com/godotengine/godot/blob/76fa7b291455a8ba24c50005072ebdb58f8a5984/core/math/basis.cpp#L150-L208) before extracting the diagonal, which can end up changing the diagonal anyway.

I'm not sure how to fix this properly. I'm frankly not even sure the behavior of Godot Physics is something worth mimicking, nor what the expected behavior is supposed to be when dealing with more complex shapes and a partial custom inertia.

I assume I should be involving something like `JPH::MassProperties::DecomposePrincipalMomentsOfInertia`, and override that resulting diagonal instead, and then re-compose the inertia tensor with the new values? I tried something along those lines already, but ended up with the reported diagonal components being swizzled, which I assume means I messed up the transformations somehow, so I figured it'd be best to check with you instead of doing my usual trial-and-error.

Here is the Godot Physics code that runs when using a fully custom inertia: [godot_body_3d.cpp#L218-L219](https://github.com/godotengine/godot/blob/76fa7b291455a8ba24c50005072ebdb58f8a5984/modules/godot_physics_3d/godot_body_3d.cpp#L218-L219)
Here is the Godot Physics code that runs when using a partial custom inertia: [godot_body_3d.cpp#L91-L143](https://github.com/godotengine/godot/blob/76fa7b291455a8ba24c50005072ebdb58f8a5984/modules/godot_physics_3d/godot_body_3d.cpp#L91-L143)

**Comment by jrouwe** [comment]
I played around with it a bit and as far as I can see the attached PR fixes the issue.

**Comment by mihe** [comment]
> I played around with it a bit and as far as I can see the attached PR fixes the issue.

Thank you! That looked a lot simpler than I thought it would be.

> Note that the calculated center of mass is unaffected by overriding the inertia diagonal, so the convex hull and the capsule don't rotate in the same way. I haven't looked if this is the same behavior as godot.

It does seem to behave the same, but you'll only see them not rotating the same way when using a compound shape for one of them, as Godot Physics apparently uses the shape's position as its center-of-mass, instead of calculating it like Jolt does, so if you just have a single non-translated shape the center of mass will always be at `(0, 0, 0)` in the body's local-space and thus the two bodies would behave the same in Godot Physics in this repro (when setting the same inertia) whereas they won't with Jolt.

I've frankly never reflected over this discrepancy before, and I'm a bit surprised nobody has brought it up yet.

I'm not saying I would want to, but I assume you could theoretically emulate the behavior of Godot Physics by just wrapping every single shape in a `OffsetCenterOfMassShape`?

**Comment by jrouwe** [comment]
> I'm not saying I would want to, but I assume you could theoretically emulate the behavior of Godot Physics by just wrapping every single shape in an OffsetCenterOfMassShape that negates its calculated center-of-mass?

Yes, that would be the fix. I think it would be better to leave this discrepancy though as bodies behave in weird ways if their COM is not in the right place.

> EDIT: Although I suppose it would really only be relevant for convex hulls?

It would be relevant for compound shapes, rotated translated shapes, convex hull shapes (basically anything that doesn't return Vec3::sZero() as COM).
