### ISSUE TITLE
Error for scaled Bodies/Collision Shapes

### ISSUE THREAD

**Issue by Wardius** [godot-jolt/godot-jolt#1025]
I constantly get an error trying to tell me a specific scale is not supported and that it will be treated as a slightly different scale:

try_build_shape: Failed to correctly scale body 'blue_crystal_area:<Area3D#177318399998>'. A scale of (0.359997, 0.240000, 0.359998) is not supported by Godot Jolt for this shape/body. The scale will instead be treated as (0.319998, 0.319998, 0.319998).
  <C++ Source>   src/objects/jolt_shaped_object_impl_3d.cpp:140 @ try_build_shape()

I personally don't mind that it is changing the scale a bit but the error message is really driving me insane because the whole debugger gets full of them. 
Would be awesome if there was an option to ignore that specific warning in the project settings.

Thanks!

**Comment by mihe** [comment]
Apologies for the late reply.

Is there any particular reason why you can't change the scale to be uniform, like it is in the corrected scale?

I'm torn on how to better design this error-checking. Allowing people to disable the error-reporting entirely is not a great option, in my opinion, because you'll end up with collision checking that doesn't line up with what the visual representation of the object tells you, both in the editor and in-game.

In fact, I'm already silencing these errors when the discrepancy between the actual scaling and the corrected scaling is small enough, which yours is not in this case. The scale discrepancy shown in your particular message can be quite a lot if your `Area3D` is even just a few meters in size.

If you really don't care about scale you can also work around this by calling `orthonormalize()` in the `_physics_process` method of your object, but you'll end up with an effective scaling of `(1, 1, 1)`. You could also grab the scale of one of the axes and apply that scale to all axes. That should give you a similar effect that what you're seeing already, but without the errors.

**Comment by Wardius** [comment]
Thanks for replying!

The problem is that I scale the object in different axes while a _squash-and-stretch_ animation plays. I think that is when the error occurs. 
Of course there are workarounds (like only scaling the mesh and not its body-child) that I can use. But the easiest fix would have been to ignore the error in itself.

But I understand that you don't think that's a great idea.
Was just wondering; no worries if you don't put it in!.

Thanks!
