### ISSUE TITLE
Add support for applying forces/wind on `SoftBody3D`

### ISSUE THREAD

**Issue by James103** [godot-jolt/godot-jolt#1026]
Firstly, it appears wind from `Area3D` is not supported by Godot Jolt and any non-zero wind force vector is treated as if it were zero. Furthermore, gravity overrides coming from `Area3D` nodes appear to have no effect on `SoftBody3D` nodes. As a result, when using Godot Jolt, there is no way I know of to apply forces on `SoftBody3D` nodes without affecting the gravitational force applied to everything else, and even that is very limited.

Would it be possible to add that support and allow `SoftBody3D` objects to be affected by wind and/or gravity from `Area3D`?

I tested this on:
Godot Jolt version `0.14.0-stable`
Godot Engine `v4.3.stable.official.77dcf97d8`

**Comment by mihe** [comment]
Yes, this is listed in the "What's not supported?" section of `README.md` as:

> `SoftBody3D` does not support any interactions with `Area3D`

This was unsupported because Jolt itself didn't have the ability to do this. However, this was recently added (jrouwe/JoltPhysics#1276) and I had hoped to finish up the implementation for the extension linked there, but other priorities have gotten in the way unfortunately.

Since then I've put up a pull request to Godot (see [here](http://github.com/godotengine/godot/pull/99895)) to migrate this extension to be a Godot engine module instead, where I've listed this as one of the to-do items, which will likely be dealt with after it's been merged.

I'll see if I end up backporting it to this extension, but it's very likely that I won't. Once that pull request is merged this extension will be put into maintenance mode, and "enhancements" like this one will be done upstream instead.

**Comment by mihe** [comment]
The above mentioned pull request has now been merged, and as such this extension will now be considered to be in maintenance mode going forward. This means I won't be implementing this feature here, but instead will try to implement it in the new Godot engine module in the coming weeks/months instead, assuming nobody beats me to it.
