### ISSUE TITLE
6DOFJoint angular limits and motor does not take parent rotation into consideration

### ISSUE THREAD

**Issue by mgiraud** [godot-jolt/godot-jolt#382]
Godot 4.03
Windows 10
Intel(R) Core(TM) i7-7700K CPU
Nvidia 2080 Super

Rotating the parent node of a 6DOFJoint will not change the angular limits axis rotation
For example rotating the parent X with 90deg will make angular limit still efftcive on the global Y axis and not the local. Whereas the torque impulse on the rigidbody uses local space.

If it is intended, maybe it should be documented.
See the MRP (same as #380 with rotation of 90deg on x axis)
[6dof-rotated-godot-jolt.zip](https://github.com/godot-jolt/godot-jolt/files/11532085/6dof-rotated-godot-jolt.zip)

Edit : 
- Same issue with Hinge Joint. 
- The gizmo representing the angular limits are rotated as expected

**Comment by mihe** [comment]
I'm having trouble reproducing this one.

When I rotate the scene's root node it behaves the same in Jolt as it does in Godot, where the motor rotation and limit look the same from the camera's point-of-view regardless of the rotation of the root node. Although, the motor direction changes between physics engines, due to #395.

Also, I noticed the `RigidBody3D` had "Top Level" enabled. Is that relevant to this somehow?

**Comment by mgiraud** [comment]
There's no difference with Godot Physics except for #395.
I just expected that the motor rotation axis would take in consideration its parent rotation.

In this MRP i've rotated the parent node to 90deg on x axis so i would expect that the angular Y motor to rotate around the global z axis but it keeps rotating around the Y axis

Also you can see that the angular limit gizmo is rotated accordingly to what i was expecting.

The way around this "issue" is to apply the parent rotation to the joint itself.

Again i don't know if it is the expected behaviour, but the gizmo being rotated led me astray

**Comment by mihe** [comment]
> so i would expect that the angular Y motor to rotate around the global z axis

That is exactly what's happening though, unless I'm misunderstanding you.

If I set the scene up like this:

![image](https://github.com/godot-jolt/godot-jolt/assets/4884246/c4fc193d-b20e-49de-9bdb-39cec21a53b7)

and then rotate the "Root" node instead of the "DOF" node, just to not affect the gizmo, then it looks like this with 0 and 90 degrees rotation around the X-axis, respectively:

https://github.com/godot-jolt/godot-jolt/assets/4884246/369f374e-139a-4991-ac51-d34b5e0fe380

https://github.com/godot-jolt/godot-jolt/assets/4884246/4d85d656-5be8-4693-a487-2245f561e3cf

Here's the scene: [dof.zip](https://github.com/godot-jolt/godot-jolt/files/11568928/dof.zip)

**Comment by mgiraud** [comment]
I'm so sorry I wasted your time, everything works fine. Materializing the axis was a great idea in your scene, and made me realize that the camera would also follow the parent rotation... I feel stupid 🤦

**Comment by mihe** [comment]
I suspected that was the problem. 😄

Don't worry about it. I'm just glad we could figure it out!
