### ISSUE TITLE
Areas don't detect static bodies

### ISSUE THREAD

**Issue by timshannon** [godot-jolt/godot-jolt#391]
Areas don't detect static bodies.  Areas work fine for character bodies, and rigid bodies, but not static bodies.

See the attached project, or simply create an area that overlaps with a static body and check `get_overlapping_bodies` or `has_overlapping_bodies`.

[bug.zip](https://github.com/godot-jolt/godot-jolt/files/11547088/bug.zip)

The attached project is C#, but I can probably throw together a GD script one if needed.

**Comment by mihe** [comment]
To quote Jolt's [documentation](https://jrouwe.github.io/JoltPhysics/) on sensors, which are the thing backing `Area3D` in Godot Jolt:

> Sensors are normal rigid bodies that report contacts with other Dynamic or Kinematic bodies through the ContactListener interface.

So them not detecting static bodies is by design. Judging by the reply [here](https://github.com/jrouwe/JoltPhysics/discussions/431) it's done for performance reasons.

I was under the impression that this was a limitation in Godot Physics as well, but when looking more closely it seems that was only an issue when the "Monitorable" property was disabled, as seen [here](https://github.com/godotengine/godot/issues/57539). I'll make sure to document this discrepancy.

As for a workaround, I suppose you could either do what was suggested in that Jolt discussion and just do an [`intersect_shape`](https://docs.godotengine.org/en/latest/classes/class_physicsdirectspacestate3d.html#class-physicsdirectspacestate3d-method-intersect-shape) yourself using the area's shape(s), although you won't be able to do that from C#, due to #270. Alternatively you could maybe child some sort of "ghost" kinematic body to your static body, using a dedicated collision layer, and use that as a sort of proxy body. I'm sure there are other interesting ways of going about it as well.

**Comment by mihe** [comment]
> and made extra clear in documentation

I bumped it up to the list of unsupported features instead.

> I rely on Area3D to know whether I should fire off raycasts for more detailed collision detection or not

An initial `intersect_shape` sounds like it might serve as a reasonable workaround then, albeit not as convenient I'll admit.

While I haven't taken the time to explore this yet, this limitation in Jolt is potentially nothing more than [an if-statement](https://github.com/jrouwe/JoltPhysics/blob/8d3008e21baff6ce774b821adc73618bb3b891af/Jolt/Physics/Body/Body.inl#L32-L38) away from being supported, and could theoretically be forked to accommodate for this feature, if needed. In fact, we've already had a similar discussion and fix for allowing [areas to detect other areas](https://github.com/jrouwe/JoltPhysics/pull/432).

The important difference between these two is that `Area3D` has the ability to disable (on a per-area basis) whether they want other areas to be able to collide with them, through the `monitorable` property. So it's at least technically possible to opt out of that, or even make it opt-in by extending `Area3D` and having `monitorable` be disabled by default instead, if you find yourself in performance trouble.

Controlling collision between areas and static bodies would only be possible globally through some potential project setting, and seeing as how areas are likely put to use as triggers around levels, potentially in great numbers, and likely intersecting with the static level geometry, a global setting like this starts to feel like a dangerous rabbit hole that you can't reasonably climb out of once you've found yourself in trouble. Sufficiently clear documentation might be a counter to that though, assuming people read it.

Sorry to be lighting the bat-signal so soon again, but I'd love to hear your thoughts on this as well @jrouwe.

(It's probably relevant to point out that I run my sensors as kinematic, and with `mUseManifoldReduction` disabled.)

In the end, without any numbers to back this up, and this being way outside my expertise, I suspect that even enabling this functionality globally without a setting to disable it would still put us in a better spot than Godot Physics, even if it's technically not making the most out of Jolt. I find this to be a difficult thing to balance though.

**Comment by jrouwe** [comment]
Bat man responding, :smile:

I took a quick look and made this: https://github.com/jrouwe/JoltPhysics/tree/feature/sensors_vs_static

If you start the SensorTest you see that the 'KinematicSensor' will start detecting the floor. As you can see it's quite a simple fix (I didn't test it very well though so it might be buggy) but I'm very worried about the performance implications. Sensors in general tend to be quite large so I think this will end up wasting a lot of CPU cycles and it's not easy to spot that you're burning all these cycles because the code will probably ignore all collisions that its not interested in. As suggested in the other ticket, I would be more in favor of solving this by doing explicit collision checks to avoid polluting the contact cache with this information (could this be done in Godot Jolt's Area3D implementation?).

**Comment by mihe** [comment]
> could this be done in Godot Jolt's Area3D implementation?

Yes, I believe so. In fact, this is what [the Bullet implementation](https://github.com/godotengine/godot/blob/b71701714fe97909d9bd3a495b6051697a136152/modules/bullet/space_bullet.cpp#L684-L778) in Godot 3 does. It would be a fairly sizeable refactoring, but a doable one I think.

I guess that would effectively remove my use of Jolt's sensors entirely, and instead they would be replaced with just narrow phase queries.

How would that compare in performance overall? Is using sensors with a contact listener mostly a convenience thing, and not so much an optimization, over just doing your own queries?

**Comment by timshannon** [comment]
I know I would definitely prefer to opt-in to this behavior rather than have it enabled globally by default.

I'm easily seeing the perf gains had by switching to Jolt, and it's worth a few minor workarounds needed for the change in behavior.

**Comment by mihe** [comment]
> I know I would definitely prefer to opt-in to this behavior rather than have it enabled globally by default.

I must admit I'd be tempted to have it be opt-out just to make the migration path easier, because I do feel strongly about the drop-in aspect about this extension, but I also understand that a lot of people wouldn't know or care to disable such a setting, even when suffering the negative side effects from it. Having it be opt-in (with a prominent warning) is probably the wiser choice.

> I'm leaning towards adding an additional flag on a body next to the IsSensor flag that indicates if you want a sensor to collide with static objects.

How would this pair up with disabling `mUseManifoldReduction` on the sensors? I had to [disable that](https://github.com/jrouwe/JoltPhysics/discussions/433) for contacts to be added/removed in a predictable manner. Are there any negative interactions there that need to be considered?

Also, just to be clear, if one were to set up their collision layers/masks (object layers) in such a way that the static bodies were completely culled from any collision with the sensors, then this performance concern mostly goes away, right?

**Comment by jrouwe** [comment]
> How would this pair up with disabling mUseManifoldReduction on the sensors? 

This should work for static too (with the same performance cost).

> Also, just to be clear, if one were to set up their collision layers/masks (object layers) in such a way that the static bodies were completely culled from any collision with the sensors, then this performance concern mostly goes away, right?

Yes, if people carefully set up their collision layers so that sensors don't collide with static then there is no performance issue.

**Comment by mihe** [comment]
> Yes, if people carefully set up their collision layers so that sensors don't collide with static then there is no performance issue.

Great!

Seeing as how there seems to be some path forward with this, either with this new body flag or by refactoring areas to instead use queries, I'll go ahead and reopen this.

**Comment by jrouwe** [comment]
I'll let you know when there's some progress on this.

**Comment by jrouwe** [comment]
There's a new flag BodyCreationSettings::mSensorDetectsStatic to make this possible in jrouwe/JoltPhysics#581.

**Comment by mihe** [comment]
This is included in the newly released [0.3.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.3.0-rc1). I'd appreciate it if you could give it a try and report back how it works out for you, either here or in the release's [dedicated discussion](https://github.com/godot-jolt/godot-jolt/discussions/465).

**Comment by timshannon** [comment]
Yep, after flipping the option in the project settings, areas detect static bodies just like in GD physics.

Thanks,
