### ISSUE TITLE
Rigidbody attached to 6DOFJoint prevents bouncing

### ISSUE THREAD

**Issue by mgiraud** [godot-jolt/godot-jolt#392]
Godot 4.03
Godot Jolt 0.1.0-rc3

Attaching a rigidbody to 6DOFJoint and drop a ball (bounce =1) on it kills the bounce.
Left is standard rigidbody
Right is ridigbody attached to a "hinge" with a 6DOF joint

https://github.com/godot-jolt/godot-jolt/assets/11818237/0799b43a-d959-4eb0-93df-66aad10bd3de

I've found something even weirder, Disabling the root node and enabling during the run makes the bounce just fine 🤔 

https://github.com/godot-jolt/godot-jolt/assets/11818237/2cbdab72-0c31-4313-bb2f-df6e83ca2a04

EDIT  : It really looks like the joint is broken when enabling the process as the box is falling on the "plane" collider, see #393 

Here is the MRP : 
[bounce-6dof-godot-jolt.zip](https://github.com/godot-jolt/godot-jolt/files/11547569/bounce-6dof-godot-jolt.zip)

This is quite an issue for my project because the ball doesn't bounce on the flippers, they behave more like magnets

**Comment by mihe** [comment]
I'm not sure there's much that can done about this one, unfortunately. The joints will never be completely rigid, especially when the body is offset from the joint like that, so they'll inherently absorb some of the energy that's meant to go into the bounce.

The only thing you can do to alleviate the problem (as far as I know) is by bumping up the solver iterations in the project settings. I'm not sure what values make the most sense, but just bump them both up in multiples until you're satisfied I guess.

Normally in Jolt you'd have the ability to set these solver iterations per-joint, which would allow you to set these much higher, but since I'm bound by the Godot Physics interface you'll just have to set them globally until I can get the new joints in.

**Comment by mgiraud** [comment]
That absolutely makes sense, thank you for your explanation

**Comment by mihe** [comment]
> you can lock the Y linear axis of the rigidbody attached to the hinge

Funnily enough, this is implemented using a 6DOF joint internally, but since the joint is positioned at the body's center-of-mass you end up not having the same issues with energy absorption.

**Comment by mgiraud** [comment]
This issue is closed, but for anybody who stumble upon this issue, you have to reffer to the real life physics ^^

As you can see on this video https://youtu.be/Tmg5WOvPKpU?t=387, on a real flipper mechanism there's a metal plate which stops the flipper at a lower position.
So i've removed the lower angular limit and made the metal plate (a simple static body) absorb the ball impact and restitute it to the ball to make it bounce. It works just fine.
Now I'm waiting for a hinge spring behaviour to be supported on godot jolt which should replace my angular motor for even a better physic simulation I hope

**Comment by mihe** [comment]
It's looking like some of the "Angular Spring" and "Linear Spring" properties on the regular `Generic6DOFJoint` might be supported soon, which might help with this.
