### ISSUE TITLE
Disabling a body attached to a joint causes errors

### ISSUE THREAD

**Issue by mgiraud** [godot-jolt/godot-jolt#393]
Godot 4.03
Godot-jolt 0.1.0-rc3

There are multiple errors and crashes that can happen when disabling a joint or one of its physicsbody. For example : https://github.com/godotengine/godot/issues/75522

But for this issue I've disabled the joint's parent node and run the project:
```
E 0:00:00:0478   _generic_6dof_joint_set_param: Condition "joint->get_type() != JOINT_TYPE_6DOF" is true.
  <Source C++>   servers\jolt_physics_server_3d.cpp:1590 @ _generic_6dof_joint_set_param()
```

This is also valid for Hinge joint and any kind of joint i guess. This is probably more a godot error than a godot-jolt error but you might want to handle this specific case 

MRP :[joint-disabled-godot-jolt.zip](https://github.com/godot-jolt/godot-jolt/files/11554480/joint-disabled-godot-jolt.zip)

**Comment by mihe** [comment]
The problem here isn't that the joint is disabled. The problem is that the "RandomChild" node is disabled, which leads to the bodies you've attached to also being disabled, which means they doesn't get added to the physics space, which means there's no simulation of Jolt to actually add a constraint to, nor any actual bodies.

This is indicative of a larger issue on my end, where the joints aren't notified whenever the space of a body changes, which can lead to dangling pointers and potentially a crash.

I'll have to think about this for a bit.
