### ISSUE TITLE
Absorbent bounce parameter throws warning

### ISSUE THREAD

**Issue by mgiraud** [godot-jolt/godot-jolt#396]
In #379 i mentioned a bounce warning that i could not explain.
Well I do now, the warning appears when setting a material as absorbent 
```
W 0:00:00:0565   set_bounce: Bounce values less than 0 or greater than 1 are not supported by Godot Jolt. Values outside this range will be clamped.
  <Source C++>   objects\jolt_body_impl_3d.cpp:821 @ set_bounce()
```

![image](https://github.com/godot-jolt/godot-jolt/assets/11818237/c58a3a58-7258-4115-b902-66862bd36788)

Pardon my half-french godot ^^

**Comment by mihe** [comment]
I'm not sure how I missed these, but when you enable Absorbent and Rough it negates the values you've entered and sends that to the physics server.

Using negative friction/restitution values is not something that Jolt supports, as far as I know. I'll have to take a closer look at what can be done about this. Worst case I'll just have to add a warning message saying it's not supported while still clamping them to 0.

**Comment by mgiraud** [comment]
Maybe a negative `mRestitution` could be a request feature on Jolt Physics ?

**Comment by mihe** [comment]
So it seems I had also missed that Jolt offers the ability to provide [custom functions](https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Physics/PhysicsSystem.h#L54-L60) for how to combine frictions and restitutions. In fact, [the way Jolt does it](https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Physics/Constraints/ContactConstraintManager.h#L489-L491) by default is not the same as [the way Godot does it](https://github.com/godotengine/godot/blob/2210111eb5e8bac6a476227c01205ac44745e21e/servers/physics_3d/godot_body_pair_3d.cpp#L250-L256). In part due to this ability to have negative numbers of course. This does mean that Jolt wouldn't necessarily need to add support for negative numbers though.

But there are still some limits/asserts hardcoded into Jolt that prevents setting any restitution outside of 0 to 1 though, but even when removing that and providing the custom functions mentioned above there's something weird happening where a ball with restitution 1 bouncing on a box with restitution -1 still results in a bounce that resembles a combined restitution of 1.

I'll need to do a bit more digging.

**Comment by jrouwe** [comment]
I had never heard of negative restitution but it seems to be a thing indeed. I created PR jrouwe/JoltPhysics#547 which I think supports it, but I find it hard to imagine what it should look like.

I updated the SimpleTest with:

```
float restitution = -0.4f;

// Floor
Body &floor = CreateFloor();
floor.SetRestitution(restitution);

RefConst<Shape> box_shape = new BoxShape(Vec3(0.5f, 1.0f, 2.0f));

// Dynamic body 1
Body &body1 = *mBodyInterface->CreateBody(BodyCreationSettings(box_shape, RVec3(0, 10, 0), Quat::sIdentity(), EMotionType::Dynamic, Layers::MOVING));
mBodyInterface->AddBody(body1.GetID(), EActivation::Activate);
body1.SetRestitution(restitution);

// Dynamic body 2
Body &body2 = *mBodyInterface->CreateBody(BodyCreationSettings(box_shape, RVec3(5, 10, 0), Quat::sRotation(Vec3::sAxisX(), 0.25f * JPH_PI), EMotionType::Dynamic, Layers::MOVING));
mBodyInterface->AddBody(body2.GetID(), EActivation::Activate);
body2.SetRestitution(restitution);

// Dynamic body 3
Body &body3 = *mBodyInterface->CreateBody(BodyCreationSettings(new SphereShape(2.0f), RVec3(10, 10, 0), Quat::sRotation(Vec3::sAxisX(), 0.25f * JPH_PI), EMotionType::Dynamic, Layers::MOVING));
mBodyInterface->AddBody(body3.GetID(), EActivation::Activate);
body3.SetRestitution(restitution);
```

(note I'm setting both floor and bodies to the same restitution as the default behavior is to take max(restitution1, restitution2), this is something you would have to change to match Godots behavior)

And this (restitution = -0.4) looks like:

https://github.com/godot-jolt/godot-jolt/assets/1621693/75ad6b73-6cbd-4ddc-99ce-62c4d8fe078f

Maybe you can check if this matches the Godot physics behavior? (I won't merge it until I'm sure it's correct :smile:)

B.t.w. I didn't do anything for negative friction. I'm not sure if that's sensible, it would make a body speedup instead of slowdown? Or does it just trigger a different friction algorithm?

**Comment by mihe** [comment]
Amazing, thank you!

> Maybe you can check if this matches the Godot physics behavior?

While using this combiner:

```cpp
physics_system->SetCombineRestitution(
    [](const JPH::Body& inBody1,
       const JPH::SubShapeID& inSubShapeID1,
       const JPH::Body& inBody2,
       const JPH::SubShapeID& inSubShapeID2)
    {
        return clamp(inBody1.GetRestitution() + inBody2.GetRestitution(), 0.0f, 1.0f);
    });
```

This is what the PR looks like with Jolt, where the left floor has a restitution of 0 and the right floor has a restitution of -0.4. The dynamic objects have a restitution of -1 to +1, from top to bottom.

https://github.com/godot-jolt/godot-jolt/assets/4884246/e543810e-09e2-4f71-a4d9-3bb478609d60

and here's what the same setup looks like with Godot Physics:

https://github.com/godot-jolt/godot-jolt/assets/4884246/1ccac7e0-31c2-4c2a-9533-c7bc0a792cea

I'd say that's pretty much the same!

> I didn't do anything for negative friction. I'm not sure if that's sensible, it would make a body speedup instead of slowdown? Or does it just trigger a different friction algorithm?

From what I can tell there's only one place where they use this [`combine_friction`](https://github.com/godotengine/godot/blob/2210111eb5e8bac6a476227c01205ac44745e21e/servers/physics_3d/godot_body_pair_3d.cpp#L254-L256) function. It seems to be a way to effectively "override" any other friction, since any negative value gets chosen as the combined value.

Here's what something similar to your `FrictionTest` looks like in Godot Physics, where the floor has a friction of +1 and the dynamic objects have a friction of -1 to +1, from left to right.

https://github.com/godot-jolt/godot-jolt/assets/4884246/0334d964-1064-4402-b646-5ae5d9166787

and here's what happens when I change the floor to have a friction of -1.

https://github.com/godot-jolt/godot-jolt/assets/4884246/bb244076-b974-499a-9fe2-16e469b0ffcc

**Comment by mihe** [comment]
and just to cover all the bases, here's your scene as well, running in Godot Physics, with a combined restitution of -0.4:

https://github.com/godot-jolt/godot-jolt/assets/4884246/45f2338e-5de0-4279-b7aa-90f2620a3281

I have no clue where that rocking motion on the box is coming from.

**Comment by mgiraud** [comment]
Here is what i understand fot Godot rough paramater from the documentation

|Body1|Body2|Collision|
| ------------- | ------------- |----|
|Friction = 0.5 rough = true|Friction = 0.7 rough = false|Friction = 0.5|
|Friction = 0.5 rough = true|Friction = 0.7 rough =true|Friction = 0.7|
|Friction = 0.5 rough = false|Friction = 0.7 rough =false|Friction = 0.5|

**Comment by jrouwe** [comment]
Ok, so friction wise it looks like you just need to create your own implementation for the friction callback and set it using ```PhysicsSystem::SetCombineFriction```.

And if the combiner is indeed ```clamp(restitution1 + restitution2, 0, 1)``` then support for a negative restitution would actually not be needed at all since the combined restitution that goes to the solver never goes below zero. All that is needed is to remove the assert that restitiution is between 0 and 1 and on your side to install a custom combiner with ```PhysicsSystem::SetCombineRestitution```. 

You can see in the last movie that in Godot, the objects actually don't sink into the floor unlike the Jolt movie.

I'll adjust the PR accordingly. Actually supporting negative restitution in the solver comes with its own set of artifacts:
* For bodies that have collision quality LinearCast will still stop at the border but then continue to sink at a lower speed than they should
* For all bodies, the restitution is applied every simulation step (because they continue to collide) which means the effect is heavily frame rate dependent and dependent on the number of integration steps you pass to ```PhysicsSystem::Update```

**Comment by mihe** [comment]
> you just need to create your own implementation for the friction callback and set it

There are still asserts in Jolt preventing any negative numbers from being set. I haven't checked to see if just removing those is sufficient, but I would assume so.

> support for a negative restitution would actually not be needed at all since the combined restitution that goes to the solver never goes below zero. All that is needed is to remove the assert that restitiution is between 0 and 1 and on your side to install a custom combiner

Great! I was gonna ask about the changes in your PR accounting for negative restitution, considering the custom combiner should have eliminated such things. Bear in mind [the comment I made above](https://github.com/godot-jolt/godot-jolt/issues/396#issuecomment-1564761956) with regards to testing this approach already though. Just removing the limits didn't quite seem to do the trick.

> You can see in the last movie that in Godot, the objects actually don't sink into the floor unlike the Jolt movie.

I completely missed that part somehow. My bad!

**Comment by mihe** [comment]
Scratch that, actually. I just tested your updated PR and that worked just fine with the custom combiner above. I must have messed something up when I tried this myself.

**Comment by jrouwe** [comment]
> Scratch that, actually. I just tested your updated PR and that worked just fine with the custom combiner above. I must have messed something up when I tried this myself.

Yes I looked through the code and GetRestitution is always passed on to the combine function.

Anyway, I just merged the changes for restitution and will continue now with the friction.

**Comment by jrouwe** [comment]
Negative friction is done too now.

**Comment by mihe** [comment]
Great! I'll bump Jolt right away and start hammering out all the changes queued up. Thank you again.
