### ISSUE TITLE
Kinematic bodies don't interact with dynamic bodies properly

### ISSUE THREAD

**Issue by GAMER-H2** [godot-jolt/godot-jolt#414]
Note: Apologies if this isn't a bug but just me missing something but I have tried all I could think of to solve this with no results.

When I switched my FPS project to Jolt, I encountered an issue when my `CharacterBody3D` node interacted with any `RigidBody3D` nodes. The `CharacterBody3D` node I was using makes use of multiple `CollisionShape3D` nodes, using the `SeperationRayShape3D` shape, at the feet to detect slight changes in elevation to not get stuck. However, when colliding with a `RigidBody3D` node (in my project, the object was representing a football and acted as expected in Godot Physics), it would spin towards the `CharacterBody3D` when in colliding and would eventually cause the `RigidBody3D` node to clip through the floor.

This behavior only occurred when the object colliding with the `RigidBody3D` had any `SeperationRayShape3D` `CollisionShape3D` nodes attached. Although I will note, in the case of the sphere `RigidBody3D` object, it would glide across the floor as if it was on ice instead of roll like it did with the Godot Physics.

Included is a simple project that displays this issue with a `CharacterBody3D` node setup similarly to what I have in my own project. Note that only the front of the Player node has `SeperationRayShape3D` collisions; the player in my own project has them on all sides. They're only on the front so the issue of a "gliding" sphere, mentioned above, can also be demonstrated in this project.

[collisionTest2.zip](https://github.com/godot-jolt/godot-jolt/files/11619161/collisionTest2.zip)

If any more information is needed then I am happy to provide what I can.

**Comment by mihe** [comment]
That does look a bit strange, and seeing as how Godot Physics doesn't present the same issue I'd consider this a bug.

I won't have time to look at this just yet, but thank you for the detailed issue as well as a minimal repro that gets straight to the point. It's greatly appreciated.

**Comment by mihe** [comment]
I took a quick look at this, and I must say I'm a bit embarrassed for having missed this, since it's a fairly crucial part of kinematic bodies.

The way kinematic bodies (i.e. `CharacterBody3D`) are moved in Godot is by just setting their transform. I had then naively let this be translated to Jolt's `SetPositionAndRotation` method. That doesn't actually impart any linear/angular velocity on the kinematic body though, which means any collision response between the character and the ball will be completely "dulled" and only the position will be resolved.

The way to solve it was by just using Jolt's `MoveKinematic` method instead, which does apply velocities to the kinematic body, resulting in the type of collision response you'd normally expect.

I'll try to have this fix in for version 0.2.0, which should hopefully be released before the end of this week, if I can wrap up my ongoing refactoring of the joints before that.

Also, I would recommend you enable "Slide on Slope" for your ray shapes, since otherwise the collision normal generated by them will be a bit "unnatural", leading to a more janky collision response.

**Comment by mihe** [comment]
These fixes, along with a bunch of other changes, are included in the just recently published [**0.2.0-rc1**](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.2.0-rc1). I'd appreciate it if you could give it a try. There's a dedicated [discussion](https://github.com/godot-jolt/godot-jolt/discussions/423) open for it if you have questions or concerns unrelated to this issue.

**Comment by GAMER-H2** [comment]
That's great! I will test out the build as soon as I can. Most likely the beginning of next week.

**Comment by GAMER-H2** [comment]
I have tested the 0.2.0-rc1 build and I can confirm the issue where the sphere `RigidBody3D` object would glide across the floor has been fixed! The ball now rolls as expected as it does in the Godot physics with the fix to Kinematic bodies.

However, the issue with the `SeperationRayShape3D` collisions still persists. While harder to activate, it still causes the `RigidBody3D` object to roll towards the player and can still fall through the floor plane if sandwiched between the player and another static body. I couldn't get this to happen in the minimal repo I provided, but my own project it was quite predominant.

I think this is likely a different issue to Kinematic bodies not using the correct Jolt method, so perhaps a new issue should be opened? I would be happy to make another minimal repo there that has my exact player scene and movement script that causes this issue included for demonstration.

**Comment by GAMER-H2** [comment]
Apologies, I probably should have tested "side on slope" value for the `SeperationRayShape3D` before posting my comment but I forgot. Enabling that value fixes the issue and even makes my movement system perform better overall.

As for the tunnelling problem, I am aware this is something most physics engines struggle with and I have seen Godot physics perform the same. Thought it would be best to notify you of this behaviour though just in case it is something you weren't expecting (I am very much not a physics programmer!). But I also agree that the floor plane I am using is not ideal and was only in place to test the worst case scenario.

Thanks for you help with these issues and I look forward to using Godot Jolt with my game project and to see it evolve :)
