### ISSUE TITLE
AnimatableBodies don't respond to tweens/animations visually

### ISSUE THREAD

**Issue by k0bolde** [godot-jolt/godot-jolt#432]
They worked fine in 0.1, but in 0.2 they stopped working for me.

It seems like you can only move animatablebodies while in the _physics_process loop? Changing the location/rotation/etc from anywhere else doesn't change the body - like tweens or animationplayers. BUT strangely it seems to actually move the physics correctly but doesn't update anything visually, even the debug collision shape!

Attached 
[jolt-bug.zip](https://github.com/godot-jolt/godot-jolt/files/11676334/jolt-bug.zip)
 is a test project with 0.2.1-stable showing that tweens and animation players update the physics, but the visuals don't move. The tween part is also interesting in that is collides for a bit, then stops. Switching to godot physics shows tweens and animationplayers work as expected. Change between tween and animationplayer with the animatablebody's _ready() (comment one, uncomment the other)

Also just want to say thanks for this project! It's letting me actually make a physics heavy game without being too worried about struggling against the physics engine!

**Comment by mihe** [comment]
Thank you for reporting this, as well as the minimal repro project.

This seems to be a regression caused by #410, which changed how the extension synchronizes its state with Godot, in order to fix another de-sync issue that I ran into.

I was under the impression that static bodies pretty much never have their state synced from the physics server to the rest of the engine, since pretty much all transform changes for static bodies are caused by the engine in the first place. Clearly this assumption does not hold true though, so I'll have to look into this more closely.

> but doesn't update anything visually, even the debug collision shape

The debug shapes you typically see when using either the gizmos in the viewport or the "Visible Collision Shapes" debug option are Godot's interpretation of the physics. If you want to see Jolt's actual view of the world you can add a `JoltDebugGeometry3D` node to the root of your scene (with an identity transform). This is more meant as a debug tool for myself, so I haven't really made much noise about it. Once I'm able to move it over to some sort of editor plugin then it'll probably be more appropriate for general use.

**Comment by mihe** [comment]
I am somewhat confident that this is actually broken on the Godot side of things, as `AnimatableBody3D` is doing some strange things with how it has its transform set, but I don't know enough about all the different gotchas and interactions that there might be, so I'll refrain from digging any further and just surrender to synchronizing the state of all kinematic bodies.

Is there anything in the 0.2.x releases that you need, or are you okay with holding off for a week or so until I publish 0.3.0?

**Comment by k0bolde** [comment]
I don't mind waiting, but I can also build from source ;) (it works)
Thanks for the quick fix! I just love tweens haha.

Strange sounding internals! Out of curiosity I took my example and changed the animatablebody to a staticbody and it worked as expected (even without the fix). So now I'm curious what animatablebodies even offer over staticbodies in jolt?

**Comment by mihe** [comment]
As mentioned in the documentation:

> When AnimatableBody3D is moved, its linear and angular velocity are estimated and used to affect other physics bodies in its path. This makes it useful for moving platforms, doors, and other moving objects.
