### ISSUE TITLE
Short SeperationRay3D doesn't collide with concave shapes

### ISSUE THREAD

**Issue by Gamepro5** [godot-jolt/godot-jolt#455]
MRP [here](https://github.com/godot-jolt/godot-jolt/files/11780838/mrp.zip), simply hit play.

I was using a SeperationRay3D shape as the shape for my rocket launcher's rocket, so that won't have a width. I need it to be small (here it's 0.01) because otherwise it would trigger a detection on a wall that is behind the player. I discovered this bug shortly after when I went on a map that used concave collision shapes.

**Comment by mihe** [comment]
This seems to be a regular case of tunneling, and happens with Godot Physics as well, from what I can tell.

In short, your `CharacterBody3D` takes a step of 0.05 m at a tick rate of 60 hz, which is greater than the length of your `SeparationRayShape3D`. Increasing the tick rate or shortening the step will lead to the ray colliding.

Concave shapes are effectively hollow, since they don't necessarily need to be a continuous solid shape, so once you've passed through the surface there's not a whole lot you can do, unfortunately.

With `RigidBody3D` you can normally counter this by enabling "Continuous CD", which will essentially do a shape-cast for you each step to see if it should be colliding with something. I honestly have no idea how well that works with `SeparationRayShape3D` though, since the implementation for that one is a bit strange, and doesn't really have an internal radius that the CCD can make use of.

If you're not actually using `SeparationRayShape3D` as a `RigidBody3D` then I'd probably recommend just doing your own ray-cast every step instead, since that's how it's implemented internally anyway.

**Comment by mihe** [comment]
Hm, actually, I just realized you were using `move_and_collide`, which obviously does a shape-cast as part of its implementation.

Now I'm curious why that shape-cast isn't catching the collision.

**Comment by mihe** [comment]
Oh right, I forgot there is a parameter in [`PhysicsTestMotionParameters3D`](https://docs.godotengine.org/en/latest/classes/class_physicstestmotionparameters3d.html) (which is used by `PhysicsServer3D.body_test_motion` that powers `move_and_collide`) that's called `collide_separation_ray`, which explicitly omits any `SeparationRayShape3D` from the collision checks. For some reason this parameter defaults to `false` and `move_and_collide` doesn't provide any parameter to change it.

You can work around this by using `PhysicsServer3D.body_test_motion` directly instead:

```gdscript
func _physics_process(delta: float):
    var step := transform.basis.z * 3.0 * delta

    var params := PhysicsTestMotionParameters3D.new()
    params.collide_separation_ray = true
    params.exclude_bodies = [self]
    params.exclude_objects = []
    params.from = global_transform
    params.margin = 0
    params.max_collisions = 1
    params.motion = step
    params.recovery_as_collision = true # This is ignored due to a bug

    var result := PhysicsTestMotionResult3D.new()

    if PhysicsServer3D.body_test_motion(self, params, result):
        $Label.text = "Sphere collision detected with %s with normal %v" % [result.get_collider(), result.get_collision_normal()]

    global_position += step
```

**Comment by Gamepro5** [comment]
I was trying a ray length of 5 on a more complex concave collision shape, and it fails to detect it properly. Maybe move_and_collide() not giving access to that parameter should be changed by the Godot devs. For now, I'll use the workaround with the more low level PhysicsMotionParameter3D. Thanks!

**Comment by mihe** [comment]
If your rocket only ever moves forward it might be worth considering not using the `SeparationRayShape3D` at all and instead replacing it with just an `intersect_ray` check that's run every step, similar to what you'd do with `body_test_motion`.

Using `SeparationRayShape3D` along with `body_test_motion` adds quite a lot of overhead for no real benefit in that scenario.

**Comment by Gamepro5** [comment]
So you mean attach a Raycast3D to a Node3D and do a check for intersection every move? I thought that the problem with raycast3d is that they point to a target location so you can't really treat it like a seperation ray shape.

**Comment by mihe** [comment]
> So you mean attach a Raycast3D to a Node3D and do a check for intersection every move?

I meant going straight for [`PhysicsDirectSpaceState3D.intersect_ray`](https://docs.godotengine.org/en/latest/classes/class_physicsdirectspacestate3d.html#class-physicsdirectspacestate3d-method-intersect-ray) and use it in the same way as the `body_test_motion` code above. `RayCast3D` is just the node wrapper for it, but if that works then that's perfectly fine as well.

> I'm really not sure what the point of a separation ray shape is if this strategy is far less buggy.

It's definitely a strange shape that I've only ever seen in Godot. Having it be a shape does have the benefit of it being able to be added to a body and actually participate in all the collision stuff, like imparting a collision response, generating contacts, emitting collision events and all that stuff.

**Comment by Gamepro5** [comment]
I also noticed another problem with your manual solution (https://github.com/godot-jolt/godot-jolt/issues/455#issuecomment-1596112226). Since this is directly changing position, tunneling does occur with this method. Is there a way to use your method but with CCD enabled?

**Comment by mihe** [comment]
I'm not sure I follow. In the MRP the bodies were kinematic bodies, in which case CCD has no relevance, since you're entirely responsible for its change in position.

If you're actually using `RigidBody3D` then there's a problem, since `SeparationRayShape3D` doesn't/can't have any inner radius for the CCD to make use of. I could give it an incredibly small float value, but I'd expect that to be pretty flaky, since you'd effectively be turning the ray into a point. Switching to a very thin `BoxShape3D` is probably not gonna help much from that standpoint either.

In that case you're probably better off doing some ray-cast in `_integrate_forces`, and projecting the body's linear velocity (which you can fetch from the `state` parameter) onto your ray's direction to figure out how far you need to cast it.

**Comment by Gamepro5** [comment]
So you are suggesting using a rigidbody, and in a script for it, use the template for integrate forces to access the velocity from the state and basically just scaling with raycasts with that value? I think I can do that, is it essentially dynamically scaling the ray based on the frame delta?

Speaking of integrate forces, I know this might be kind of unrelated, but i noticed that animating a animateable body does not seem to change its linear velocity and angular velocity, because I try to access it during physics process to move my character on a platform. The frame rate is set to high enough such that jolt can auto correct and keep my player on top, but it doesnt actually get the velocity of a collider from the move and collide collision data. I was wondering if this had to do with integrate forces or if this was another issue that needs an mrp. It worked fine in Godot physics.

**Comment by mihe** [comment]
> So you are suggesting using a rigidbody

No. Keep using a kinematic body (i.e. a `CharacterBody3D` or frozen `RigidBody3D`) if you're already doing so.

> and basically just scaling with raycasts with that value?

Yes, but scaling assumes that your ray is traveling in the exact direction its facing. If not, you'll want to project (dot product) the velocity onto the direction instead, but that'll also break down too if there's too much of a discrepancy between the two.

> is it essentially dynamically scaling the ray based on the frame delta?

Yes, you'd essentially be doing your own CCD, by casting up ahead to see if you're gonna collide with something in the next step.

> or if this was another issue that needs an mrp

Yes, please create a new issue for this. This is something I messed around with fairly recently for version 0.2.2. I thought I had squashed all the bugs there, but I guess not.

**Comment by Gamepro5** [comment]
> No. Keep using a kinematic body (i.e. a CharacterBody3D) if you're already doing so.

What would the collision shape be then? Right now I had a node3d with a raycast child node.

**Comment by mihe** [comment]
In that case just leave it as a `Node3D` and change the length of the ray-cast according to your velocity, I guess.

**Comment by mihe** [comment]
Just to (hopefully) dispel any confusion, here's another modified version of the original MRP: [rocket.zip](https://github.com/godot-jolt/godot-jolt/files/11821845/rocket.zip)

No matter the speed you'll always hit the wall.

I used `intersect_ray` just to make things more explicit, but I'm sure you can adapt it to the `RayCast3D` node as well.

Also, this will clip halfway-ish through the rocket before hitting, due to the placement/length of the cast, so you'll need to adjust that if it matters.

**Comment by Gamepro5** [comment]
I understand now, thank you so much. Your help allowed me to perfect [this](https://youtu.be/By-CVcuFjzU). Instead of doing `explosion.set_position(self.global_position)`, I did `explosion.set_position(self.global_position-velocity*delta)` so that the raycast for the line of sight that is spawned doesn't instantly collide with the thing the rocket collided with. Have a good day, you made mine!
