### ISSUE TITLE
Bodies/shapes do not support negative scale

### ISSUE THREAD

**Issue by ettiSurreal** [godot-jolt/godot-jolt#461]
Hello, i am making a small physics based game and currently trying out Jolt as a physics engine.
The game has a lot of StaticBodies with their collision placed offcenter, that often get inverted on a single axis for variation, since i don't want to have to make a separate scene for every inverted one.
However unlike GodotPhysics, Jolt does not handle these correctly, as you can see in the reproduction project.
[MinReproduction.zip](https://github.com/godot-jolt/godot-jolt/files/11799594/MinReproduction.zip)

**Comment by mihe** [comment]
Thank you for reporting this, and for providing the minimal repro.

Negative scaling is something I seem to have forgotten to test altogether, and is indeed broken.

Jolt does seem to support it as well, so it's likely some small thing on my end that needs to be fixed.

**Comment by mihe** [comment]
It did turn out to be a small thing, thankfully.

The next release (containing this fix) will likely drop some time next week, but you can always [build from source](https://github.com/godot-jolt/godot-jolt/blob/master/docs/building.md) if you need the fix sooner.

**Comment by Gamepro5** [comment]
Just curious, in Godot physics, scaling any collision shape is a terrible idea according to rburing. Does jolt work correctly with scaled collision shapes? Why does having a negative scale make any sense at all, does it swap the faces with backfaces?

**Comment by mihe** [comment]
I honestly have no idea. I was expecting it to not be supported when I first tried it, since it does mess with my head a bit as well, but even `ConcavePolygonShape3D` works just fine.

Jolt seems to have been designed with scaling in mind from the start though, unlike Godot Physics, allowing for things like scaling compound shapes (which I use to scale bodies, even dynamic ones) as well as being able to scale most shapes non-uniformly. I assume it has something to do with the fact that Jolt always takes scale separate from the rest of the transform.

**Comment by mihe** [comment]
This is included in the newly released [0.3.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.3.0-rc1). I'd appreciate it if you could give it a try @ettiSurreal and report back how it works out for you, either here or in the release's [dedicated discussion](https://github.com/godot-jolt/godot-jolt/discussions/465).

**Comment by ettiSurreal** [comment]
Tried it out, works perfectly now. Thanks!
