### ISSUE TITLE
CharacterBody3D getting stuck in simple trimesh collider body. Repro inside.

### ISSUE THREAD

**Issue by idchlife** [godot-jolt/godot-jolt#464]
Hey! Thank you so much for this addon!

I came to your addon after experiencing issues with CharacterBody3D getting stuck in simple trimesh collider body with Godot 3 Physics engine.

Unfortunately, I am experiencing the same problem with Jolt physics.

Maybe I am doing something wrong with settings or something? It seems so weird that capsule collider getting stuck with simple trimesh collider, but maybe I am really doing something wrong.

Here is the video of the problem: 
https://imgur.com/a/0f1mM13

And here is repro project:

[character-body-3d-stuck-repro.zip](https://github.com/godot-jolt/godot-jolt/files/11847044/character-body-3d-stuck-repro.zip)

**Comment by mihe** [comment]
As seen in Godot's script template for `CharacterBody3D`, your application of gravity in `player_mover.gd` needs to only happen if `not player.is_on_floor()`, like so:

```gdscript
if not player.is_on_floor():
    _velocity.y -= gravity * delta
```

Otherwise your velocity (and thus effectively your direction) ends up always pointing nearly straight down all the time, which throws off some fundamental assumptions in the code that powers things like `move_and_slide`.

**Comment by idchlife** [comment]
@mihe thank you so much for your response and that you pinpointed the problem!

You eased the dreaded feeling that I had thinking that godot physics and godot-jolt physics were unusable in terms of CharacterBody3D. Turns out, the problem is not there.
