### ISSUE TITLE
Collision normals with cylinder shape are rounded on sloped edges

### ISSUE THREAD

**Issue by Gamepro5** [godot-jolt/godot-jolt#471]
I'm fairly sure this is also an issue with Godot Physics, and I think this happens because normals are calculated from the origin of the shape to the collision point, but when on the edge of an angled slope, the normal appears always much higher than it actually is. I don't know if this technically counts as a bug. If it doesn't, I'd love some ways to work around this problem, because it means that my character is unable to step up a stair if the stair is angled (because it thinks that stair is too steep).

[mrp.zip](https://github.com/godot-jolt/godot-jolt/files/11913548/mrp.zip)

**Comment by mihe** [comment]
This is indeed not a bug, since the collision normal doesn't represent the surface normal of the thing you're hitting but instead the direction by which to separate the two bodies to resolve the collision, and in this particular case the curve of your character shape comes into play.

The only way to get the actual surface normal of something in Godot (as far as I'm aware) is through a ray-cast. It's a bit of a crude solution in this particular case, but I suppose ray-casting from the character's origin to the collision position might serve as a workaround.

Here's an example: [surface_normal.zip](https://github.com/godot-jolt/godot-jolt/files/11914598/surface_normal.zip)

I only use the first collision there, so you might have to figure out something that incorporates all of them, but hopefully that gets the point across at least. I'm sure there will be plenty of other weird edge-cases (no pun intended) with this solution as well, but it is what it is.

I appreciate any and all reported issues, but in the future, as a general rule of thumb, if you observe the same behavior with both Godot Physics and Godot Jolt, I'd appreciate it if you explore other avenues for advice first, like Godot's [Questions & Answers](https://ask.godotengine.org/), the [Godot subreddit](https://old.reddit.com/r/godot/), or the Godot [Discord server](https://discord.gg/4JBkykG).
