### ISSUE TITLE
Add support for web

### ISSUE THREAD

**Issue by TranquilMarmot** [godot-jolt/godot-jolt#477]
Similar to https://github.com/godot-jolt/godot-jolt/issues/354 and https://github.com/godot-jolt/godot-jolt/issues/353, I wonder if it would be possible to support jolt on the web (HTML5 export)?

**Comment by mihe** [comment]
Thank you for the feature request.

Jolt does technically support web builds through [JoltPhysics.js](https://github.com/jrouwe/JoltPhysics.js), but I haven't really explored what it would look like to make use of it from Godot Jolt, nor what loading extensions looks like for Godot's web exports.

I must admit that I'm not super keen on supporting this, which is why I didn't create an issue for it. Although the situation is certainly much better these days, browsers tend to have frustrating discrepancies that I'd rather not spend my time chasing down. Throwing Emscripten and WebAssembly into the mix will probably bring its own set of challenges as well.

I'll leave this open to better gauge what the demand is for this, but for the time being this will not be on the roadmap.

However, if someone else with more experience with Emscripten and WebAssembly wants to do some exploratory work, to give me a better sense of how it all would work and what changes would be necessary, then I'd be willing to allocate some time for accommodating that.

**Comment by TranquilMarmot** [comment]
Yeah, even reading [Godot's docs on exporting for the web](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html) there are so many warnings 😅 It is definitely a somewhat painful thing to support right now.

**Comment by jrouwe** [comment]
I concur that supporting this is painful. I managed to make it work for Jolt, but the code, compile, debug loop is extremely slow. The debugger is almost unusable. I had to resort to printf debugging in many cases and even then it manages to not show the printfs. There are indeed bugs in browsers, e.g. https://github.com/jrouwe/JoltPhysics/issues/577 where even the HelloWorld application doesn't work on macOS Safari.

**Comment by bikemurt** [comment]
Just chiming in here - not sure if there's been any more decisions regarding Jolt Physics and the web. One of the most frustrating things I'm dealing with right now is very basic collision shapes "jittering" unnecessarily with the vanilla physics engine. I'm using very basic shapes such as boxes and cylinders, and no matter how I tweak all the parameters, the physics engine just seems to do it wrong.

I've tested in Jolt Physics and it works with no errors whatsoever, but of course, I am developing for the web, hence my post...

Any advice? What possible avenues there are for people like me? I have built GDextension code for the web before, I'm curious how much more difficult it would be to do for Godot Jolt.

**Comment by mihe** [comment]
> Any advice? What possible avenues there are for people like me? I have built GDextension code for the web before, I'm curious how much more difficult it would be to do for Godot Jolt.

Near-term I don't have any advice for you, unfortunately. I don't think it's trivial for anyone to just jump in and add web support to this extension, given the unfortunate complexity of CMake, as well as the stuff I've stacked on top of CMake.

Long-term it's looking likely that this extension will be merged into Godot as an official module, in which case web support will largely come "for free" as part of that porting process. I can't give you any timeline on that, but I'm hoping it's not too far away.

**Comment by tetious** [comment]
After much wrangling with CMake and Emscripten, I've got this barely sorta-kinda working... for about 5 seconds at a go. :grinning: 

I will keep poking at it, but I'm hoping that someone with a bit more experience with godot-jolt can point me in a direction. It's probably something simple I'm missing.

Anyway! Here's how to try it out! (Note that this process is a bit convoluted due to a [very soon to be fixed bug in Emscripten](https://github.com/godotengine/godot/issues/82865) and my lack of Cmake expertise. Apologies! I'll do my best to clean it up once it is working properly.)

1. Install `emsdk` or similar: https://github.com/emscripten-core/emsdk
2. Grab the version of Emscripten **_that has working dlopen support_**:
```
emsdk install 3.1.39
emsdk activate 3.1.39
```
3. Set up your path for emsdk. (Differs across shells, the quick version is to source the correct `emsdk_env` for your shell.)
4. Build the godot web export templates with dlink and threads (the official version is built with a newer, broken Emscripten, so alas you must do this yourself)
(NOTE: I've only tested with 4.3 beta 1, so grab that version! Git commit: `a4f2ea91`)
```
scons platform=web dlink_enabled=yes target=template_debug
scons platform=web dlink_enabled=yes target=template_release
```
5. Copy the zip files in bin/ to wherever export templates end up on your platform (example is for Linux) and rename.
```
cp bin/godot.web.template_debug.wasm32.dlink.zip ~/.local/share/godot/export_templates/4.3.beta1/web_dlink_debug.zip
cp bin/godot.web.template_release.wasm32.dlink.zip ~/.local/share/godot/export_templates/4.3.beta1/web_dlink_release.zip
```
6. Grab my fork from here: https://github.com/tetious/godot-jolt/tree/web-platform-support
7. Configure and build: (mimalloc doesn't work, and I don't know why...)
```
cmake --preset web-wasm32 -DGDJ_USE_MIMALLOC=FALSE
cmake --build --preset web-editor-debug
```
8. Open the godot-jolt example and set up a web export. **_Make sure to enable extensions and threads!_**
9. Run the export via the remote debugger item in the editor and bask in the excitement of 5 seconds of full working until it asserts and hangs. :grin: 

Here is a gist of the full console output leading to the crash: https://gist.github.com/tetious/9f40ec318b8d07e4ee902414e0c5b5db

My wild guess is that something is getting mangled in the job cleanup logic (various errors like this:) 
```
RuntimeError: null function or function signature mismatch
    at godot::StringName::StringName(char const*, bool)
```
and it never cleans up completed jobs, leading to this: 
```
Godot Jolt's job system exceeded maximum number of jobs. This should not happen. Waiting for jobs to become available.
```

Any suggestions, guesses or "try this"es would be appreciated! Thanks in advance!

**Comment by jrouwe** [comment]
The problem appears to be related to multi threading, which is a precarious thing in JS:

* I think the `-sALLOW_MEMORY_GROWTH=1` flag is totally incompatible with multithreading. The C++ memory heap is implemented as a JS `Int8Array`. Resizing it on the fly breaks all atomic operations that may be operating on that array (which is what the job system basically revolves around). So I would suggest starting with a large enough initial memory size and disabling growth, e.g. `-sTOTAL_MEMORY=67108864` is what JoltPhysics.js uses.
* Multi threading in Safari is buggy in my experience, so if you're doing this on a Mac you might want to consider downloading Firefox and trying that.
* You might want to try disabling multi threading completely. There's a project setting `threading/worker_pool/max_threads` in godot that could be set to 1.

**Comment by mihe** [comment]
> You might want to try disabling multi threading completely. There's a project setting `threading/worker_pool/max_threads` in godot that could be set to 1.

You'll likely want to compile Godot with `threads=no` to begin with, as not doing so will require `SharedArrayBuffer`, which is pretty much a showstopper in any browser (post Spectre/Meltdown) from what I understand. This is also the reason for several of the warnings you find in [the Godot documentation](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html) that was linked above. See godotengine/godot#85939 for more details.

Unfortunately I'm forced to infer the thread count for `WorkerThreadPool` from `OS::get_processor_count()` (unless you set it explicitly using the above mentioned project setting) and I have no idea what that will return with `threads=no` nor `threads=yes`. I made a PR to expose the thread count from `WorkerThreadPool` but it got shot down at the time for reasons I don't quite understand.

The official Godot export templates ship with two sets of web builds, one that's threaded and one that's not. It's not unlikely that something similar would have to be done for an extension as well, using the `threads` feature tag in the `.gdextension` file.

> mimalloc doesn't work, and I don't know why

This is to be expected. mimalloc only really supports the desktop platforms. I already disable it for iOS and Android [here](https://github.com/godot-jolt/godot-jolt/blob/6ffe4ff2b681143fd38565fd3e416b1a42bf6f2d/cmake/GodotJoltOptions.cmake#L12).

**Comment by tetious** [comment]
Thank you @mihe and @jrouwe! Your tips helped me solve it and it seems to be working great here, at least in my light testing with both the example and my project. (I should have mentioned previously, I'm testing this under Linux and using Chromium 126. I will do a bit more testing on Mac and ChromeOS soon, though I don't currently have access to Windows.) 

https://github.com/godot-jolt/godot-jolt/assets/55581/81eb3230-3a5e-4b3d-be33-a0dbff22b4ca

It was all threading related, just as you suggested.

Previously, I'd started with exports with `threads=no` and was getting a very mysterious and nonsensical error during the extension init. I was still in the "try random things" phase and forgot to revisit. The problem turned out to be that I missed this line from godot-jolt's CMakeLists:
`PRIVATE -pthread # Use POSIX threads` :man_facepalming:

Once I wrapped that behind a guard to exclude for the web build, the single-threaded target worked! (web export templates compiled with `threads=no` and adjusted build settings reflected in my fork)

I will pop this in a PR shortly with updated build instructions as well as figure out how to distribute the wasm file so others can test more easily. 

> This is to be expected. mimalloc only really supports the desktop platforms.

Interestingly, the Emscripten folks [merged a port of mimalloc](https://github.com/emscripten-core/emscripten/pull/20651) that we could maybe use once we can run a newer version, though I dunno if it will be better than the default in a [single-threaded workload](https://emscripten.org/docs/tools_reference/settings_reference.html#malloc).

> I have no idea what that will return with `threads=no`

On my platform (Linux/Chromium) it returns 2, which is mysterious. This machine has 8 cores. :shrug:
