### ISSUE TITLE
Build a module?

### ISSUE THREAD

**Issue by greenfox1505** [godot-jolt/godot-jolt#492]
I like to use GDExtension for a lot of game specific code. Unfortunately that means nodes created with other GDExtensions are hard to interface with.

It sounds like this project is intending to make some additional nodes and that will make it very hard for me to interface with through Rust. A solution to this problem is to make this a Module. Is this viable? Would you consider this a supportable use case?

**Comment by mihe** [comment]
Building as a module is not something I'm likely to support, unfortunately.

While some of the code-specific hurdles could be dealt with one way or another, building as a module would also likely mean building the extension (and all its dependencies) through SCons, which is a bit of an undertaking and not something I'm willing to commit to or maintain. Frankly, SCons is one of the reasons why this project is an extension in the first place, as Godot Jolt started its life as a module once upon a time.

With that said, this project is not likely to amass a great number of custom nodes. The only custom nodes I have planned at the moment are ones that replace the default set of joints, as well as adding some "core" ones that I feel are missing from Godot, like Jolt's `FixedConstraint` and its `DistanceConstraint`. Those two don't really add any functionality though, as they can technically be implemented using 6DOF joints. The only real difference between this custom set of joints and the default set will be some minor stuff, like support for soft limits, a better interface for springs, breakable joints and the ability to override solver iterations per-joint.

Custom nodes also put a lot of strain on the C# scripting, since it suffers from the same problem of not being aware of any nodes exposed by extensions. With C# I am hopeful that I can whip up some custom bindings somehow and distribute those as a NuGet package, but it's none the less likely to be a lot of work that I'd rather not do, so that acts as further incentive to not delve too deep into custom nodes.
