### ISSUE TITLE
Support for non-square/non-power-of-two `HeightMapShape3D`

### ISSUE THREAD

**Issue by jrouwe** [godot-jolt/godot-jolt#502]
Opening an issue to discuss comment at https://github.com/godotengine/godot-proposals/issues/7308#issuecomment-1646151034:

For performance reasons I'm reluctant to support non-power of 2 / non-rectangular height fields. There are work arounds to support more dimensions:

* You can round up dimensions to the next power of 2 and fill the remaining height samples with ```HeightFieldShapeConstants::cNoCollisionValue```.
* You can play around with ```HeightFieldShapeSettings::mBlockSize``` which doesn't need to be a power of 2 to reach resolutions that are not a power of 2 (and can combine this with the first trick).
* You can create multiple HeightFieldShapes and combine them into a CompoundShape for non-square height fields.
* You can convert a HeightMapShape3D to a MeshShape if none of the above are applicable (this is what we do when there many holes in the terrain so that a mesh uses less memory than a heightfield).

Do you know what the common patterns are for dimensions of height maps in godot? If there are, then perhaps I can support them.

**Comment by mihe** [comment]
Thank you for the suggestions. I'll give those a try when I have the chance.

> Do you know what the common patterns are for dimensions of height maps in godot?

Until very recently I would have said this shape in general was largely forgotten about, as it's had some issues in Godot Physics and people don't seem to really use it much, presumably for that reason.

But just a couple of days ago there was a terrain extension released called [Terrain3D](https://github.com/outobugi/Terrain3D), which implements clipmaps that utilize `HeightMapShape3D`, and for reasons that I'm not intimately familiar with they use `power_of_two + 1` as their height map dimensions. So with their default "region size" of 1024, you end up with 1025 samples.

I got a question from @Dabnabbit about this exact thing the other day, who had run up against this same problem in Godot Jolt when trying to use his own clipmap solution, and from what I understand this extra row/column stems from somehow simplifying the process of being able to tile the regions, because the quads and pixels end up 1:1, or something like that. :)

So to answer your question I guess pretty much the only pattern I've run into so far is exactly that, `power_of_two + 1`, which I suppose your first suggestion should technically be able to accommodate for just fine.

**Comment by jrouwe** [comment]
If you create a terrain texture for rendering of NxN pixels you can see each pixel as the value at the center of each of the NxN quads of the terrain, this means you'll need (N+1)*(N+1) vertices in order to get N*N quads. We have chosen the opposite where we see the terrain texture as the values at the vertices rather than at the center of the quads and then it makes sense to have N*N vertices in the height field (where N is power of 2).

I'll see how difficult this is to support (but first soft body support).

**Comment by DarcyLawrence** [comment]
Support for alternative dimensions would be great. Zylann's heightmap plugin also follows power_of_two + 1 rules for dimensions and provides their reasoning here: https://github.com/Zylann/godot_heightmap_plugin/blob/a481edb415d29eb01f7b0f220bde301e9052dcfb/addons/zylann.hterrain/hterrain_data.gd#L227

**Comment by Zylann** [comment]
I was actually wondering about using *chunk sizes* that are not powers of two (for example 63 instead of 64), so that the terrain maps would not be `2^x+1`, but instead `N*2^x+1`, where N is not power of two. Which means maps would fit within a power-of-two image, just not using the full image. I thought of that because I had the impression that forcing a texture to be non-power-of-two by just 1 above a power of two was going to waste memory on the graphics card, in case the driver worked around that by allocating the next power of two, wasting almost 75% of memory. I never really investigated whether that's true^^" But...

> You can round up dimensions to the next power of 2 and fill the remaining height samples with HeightFieldShapeConstants::cNoCollisionValue.

Physics-wise, it would then mean as well that not as much memory would be wasted when using such a technique.

On top of that I was thinking if a terrain is already using tiles, non-power-of-two sizes don't seem to be much of a problem, since tiles can already help greatly in covering the "used space" of the game world.

**Comment by TokisanGames** [comment]
> If you create a terrain texture for rendering of NxN pixels you can see each pixel as the value at the center of each of the NxN quads of the terrain

Hi, I'm a Terrain3D coauthor. I wrote up a discussion about why we use 1025^2, which is not quite what is quoted above. I tried Jolt today after reducing down to 1024, I found it mostly works but there are two key issues. If I can get help resolving them, I have no problem reducing our collision down to 1024.

https://github.com/outobugi/Terrain3D/discussions/152

**Comment by trekfan42** [comment]
I just ran into this issue trying to implement Jolt in my game and then going down the rabbit hole on the error from Zylann's terrain plugin. Glad to know supporting non power of 2 is a planned feature! Thank you so much! Looking forward to release!

**Comment by jrouwe** [comment]
I just submitted a change that allows non-power of 2 height fields.

**Comment by trekfan42** [comment]
oh awesome i thought it was planned for 1.0 i saw .5 was out. I'll check it out!

**Comment by mihe** [comment]
@jrouwe meant with respect to Jolt itself, not Godot Jolt. I did just try this locally with Terrain3D's demo project though and everything seems to work, as far as I can tell, so expect this to be in for the next release, which should hopefully be out some time early next week.

**Comment by TokisanGames** [comment]
@mihe You can enable debug collision in our settings then you can see it. Specific areas to look at are the borders between regions as that's where the heightmap shapes overlap. That's the +1.

**Comment by SlashScreen** [comment]
When godot jolt gets updated to reflect this, don't forget to update the caveat in the readme.

**Comment by mihe** [comment]
I decided to also throw in preliminary support for non-square height maps, by just falling back to Jolt's `MeshShape` (i.e. `ConcavePolygonShape3D`) in those cases. I hadn't planned on doing anything about it during this first pass, but since I was already adding support for 2x2 and 3x3 height maps (yeah yeah, I know, but Godot supports it) through Jolt's `MeshShape` I figured why not. It's probably such a vanishingly small number of users that need non-square height maps that this should be fine for a while.

I also removed the error when you have a `HeightMapShape3D` with 0 heights in it, which seemed to be a thing that Terrain3D does at some point. I'm already forced to support having 0 faces in a `ConcavePolygonShape3D`, due to how `CSGShape3D` works, so this seemed like the right thing to do either way.

With all these changes, the Terrain3D demo project seems to work just fine without any errors. Although, I'll admit I haven't looked at it too closely.

I'll try to get a release out in the next few days, so you can try it for yourselves, if you don't feel like building from source.

**Comment by TokisanGames** [comment]
Great, looking forward to trying it.

> I also removed the error when you have a HeightMapShape3D with 0 heights in it, which seemed to be a thing that Terrain3D does at some point.

I wasn't aware that happens. Under what conditions? If there are no regions there shouldn't be any collision generated.  That's what I see in the code, it only makes heightmapshape3d if there's a region with data in it.

**Comment by mihe** [comment]
> I wasn't aware that happens. Under what conditions?

From just looking at your code, you add the shape to the body before settings the shape data [here](https://github.com/outobugi/Terrain3D/blob/278956659f37891f6b13388f17ad13991ff5a84e/src/terrain_3d.cpp#L203-L209), meaning you're adding an empty `HeightMapShape3D` to a live body, which will trigger a setup of the internals, but with 0 heights, and then you set the proper shape data, triggering the real setup of the internals. Flipping those two lines should prevent that.

Godot Physics silently lets this become an empty/invalid shape, like with so many other invalid shape configurations, but I had tried to be more aggressive about actually emitting errors in such cases. I guess there's some argument for 0 heights actually being a valid configuration though, hence the change.

**Comment by TokisanGames** [comment]
Ah, I see. Most tasks in Godot allow one to create an empty resource when working in the inspector. I didn't see any errors or notice any problem, even when testing jolt before. We can swap the lines easily.

**Comment by mihe** [comment]
Just to clarify, this behavior is specific to how Godot Jolt deals with how the underlying Jolt shapes are rebuilt. I didn't mean to imply that what you're doing is somehow incorrect. Godot Physics doesn't care in which order these two lines happen, and will run its internal setup twice either way. Godot Jolt won't run the internal setup until the shape is actually set on at least one body that's also attached to a scene tree, which is what allows me to be a bit more picky about invalid configurations, since shapes should ideally be properly configured by that point.

**Comment by mihe** [comment]
I've just published [0.6.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.6.0-rc1), which includes the relaxed restrictions on `HeightMapShape3D`. I'd appreciate it if anyone here awaiting either of these changes could give it a try and confirm that it works for your particular use-case(s).

**Comment by Dabnabbit** [comment]
I'm happy to announce proper 1:1 working functionality matched against the original Godot API, with near identical calculation/generation times. Super awesome to the see the community come together to solve an issue like this in such a short amount of time!

**Comment by mihe** [comment]
Glad to hear it! Thank you @jrouwe for taking on the non-power-of-two stuff on your end by the way. I'll see about experimenting with the non-square compound shape stuff at some later point (before v1.0).

I'll probably let this release candidate sit for a couple of days until I publish the stable version.
