### ISSUE TITLE
Concave polygons with `backface_collision` yield inconsistent normals when ray-casting

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#511]
When ray-casting against a `ConcavePolygonShape3D` that has its `backface_collision` property enabled, you can randomly end up with normals that point in one direction or the other.

Here's how to reproduce it:

1. Download this project: [BackfaceRayCast.zip](https://github.com/godot-jolt/godot-jolt/files/12165865/BackfaceRayCast.zip)
2. Run the main scene
3. Note how the output shows either `(0, 1, 0)` or `(0, -1, 0)`
4. Switch physics engine to Godot Physics
5. Run the main scene again
6. Note how the output only shows `(0, 1, 0)`

This has to do with the way I've implemented `backface_collision`, which just duplicates the set of triangles with a reversed winding order. The ray-cast then uses `JPH::Body::GetWorldSpaceSurfaceNormal` which requests a normal at the position where the ray hit, and since the two triangles overlap perfectly you randomly end up with the normal of either one.

One quick hack is to just check if the normal is facing away from the ray-cast direction, and just flip it, but I'd like to investigate what else can be done to fix this properly.

**Comment by Evanator05** [comment]
Ive been having this problem with csg combiner collisions which with my game causes massive problems, so my solution was to normalize the vectors unfortunately near the edges of objects my game freezes then crashes trying to normalize the vectors, this doesnt happen when im using default godot physics, is is possible that this addon changes how vector 3s work? because my game crashing from normalizing them makes no sense

**Comment by mihe** [comment]
@Evanator05 Please create a new issue with a small example project that shows the problem you're having.

**Comment by mihe** [comment]
It seems like there's a much better way to solve this issue, but it might be a while before I get to it. See the discussion in jrouwe/JoltPhysics#672.

In the meantime I'll throw in the above mentioned flip, just to make this less buggy.
