### ISSUE TITLE
CylinderShape3D imprecision on ShapeCast3D

### ISSUE THREAD

**Issue by wjagodfrey** [godot-jolt/godot-jolt#516]
```
OS: MacOS 12.3
Godot: 4.1.1
```

When casting a `CylinderShape3D` `ShapeCast3D` down onto a `ConvexPolygonShape` collider attached to a `StaticBody3D`, it clips near the edge. Makes stair checking too imprecise to work.

Works well with the default Godot physics engine.

Godot Jolt:
<img width="1500" alt="Screen Shot 2023-07-27 at 3 36 29 PM" src="https://github.com/godot-jolt/godot-jolt/assets/5732688/c6a013cf-f05c-4ae1-963f-8bace141a3d9">

Godot Default Physics:
<img width="1500" alt="Screen Shot 2023-07-27 at 3 37 39 PM" src="https://github.com/godot-jolt/godot-jolt/assets/5732688/e0749385-1cbd-4f23-ab1e-d596309a4dd5">

**Comment by mihe** [comment]
Similar to Bullet (as used in Godot 3), as well as other real-time physics engines, this is the result of what Godot refers to as "[shape margins](https://docs.godotengine.org/en/stable/classes/class_shape3d.html#class-shape3d-property-margin)", or what other physics engines refer to as "collision margin", "convex radius", "bevel radius" or "polygon skin", which is used as part of an optimization technique that's common with real-time physics engines.

What it means is that any convex shape with sharp edges, meaning `BoxShape3D`, `CylinderShape3D` and `ConvexPolygonShape3D`, will have their edges rounded off, leading to the artifact you see in your screenshots.

You can disable this technique if you want, either by setting the `margin` property on your shapes to 0, which you'll likely need to do for both the cylinder you're casting as well as any convex shape your cylinder may collide with, or you can choose to disable this globally by going into the "Jolt 3D" project settings and disabling the "Use Shape Margins" setting, which will effectively just set the margin to 0 for all shapes.

Godot Physics uses a different type of collision detection that doesn't use this optimization technique, so it completely ignores the `margin` property for all shape types.

I'll see about maybe making this fact more prominent in the README, since this seems to be a common point of friction.

**Comment by mihe** [comment]
Also note that this is (somewhat confusingly) not quite the same thing as the `margin` property on `ShapeCast3D`, which in both Godot Jolt and Godot Physics will "inflate" the shape you're casting. So you need to set the margin on the shape itself, not on `ShapeCast3D`.

**Comment by wjagodfrey** [comment]
@mihe that didn't solve the problem, or perhaps it solved one problem and left the one I'm noticing. I've also noticed it's inconsistent. Let me show you. These are both taken with Godot Jolt:

Sometimes when I hit, it gets the hit depth correct and `get_closest_collision_safe_fraction()` gives me a fraction less than `1`:
<img width="1500" alt="Screen Shot 2023-08-04 at 12 24 01 PM" src="https://github.com/godot-jolt/godot-jolt/assets/5732688/18d52a74-cddd-488f-86ea-dc53f6d753bf">

If I walk away and come back, it registers a hit but it thinks the hit happened all the way at the end of the cast. `get_closest_collision_safe_fraction()` gives me `1`:
<img width="1388" alt="Screen Shot 2023-08-04 at 12 21 57 PM" src="https://github.com/godot-jolt/godot-jolt/assets/5732688/9f649568-1cee-403d-8342-a0f46e16c6d2">

The latter is more common than the former by a factor of 4.

**Comment by mihe** [comment]
I'm not quite sure I understand what you mean, or what I'm seeing in the screenshots. Any chance you could reduce that project down to the bare minimum and upload it here? Preferably set up in such a way that just running the main scene shows the problem right away.

**Comment by wjagodfrey** [comment]
Hi @mihe, when I'm through my current piece of work I'll try Jolt again and progress this issue, but until then- the pale blue cylinder clipping through the stairs (not by very much, you may have to zoom in) shows the `ShapeCast3D` imprecision every few frames. When it happens, the safe collision distance fraction is also misreporting as `1`.
