### ISSUE TITLE
hit_from_inside = off is not working

### ISSUE THREAD

**Issue by Regrad** [godot-jolt/godot-jolt#542]
hit_from_inside dose not affect hitting from inside body. In Godot Physics it's working.

**Comment by mihe** [comment]
It does work, but there's some stuff to keep in mind...

`hit_from_inside` will make convex shapes (boxes, spheres, capsules, cylinders, convex polygons) "solid" instead of "hollow", so that you *immediately* hit something if your ray-cast starts from within one of these shapes.

However, even when disabling `hit_from_inside` you can (when using Godot Jolt) still hit the "inside wall" of a convex shape if you have `hit_back_faces` enabled, which it is when using the `RayCast3D` node.

I realize this discrepancy between Godot Jolt and Godot Physics is confusing, especially when reading Godot's documentation for `hit_from_inside`, but it's unfortunately the way it has to be.

If you're using the `RayCast3D` node, your only real option (until Godot 4.2 is out) is to add the body that you're inside of as an exception, using the `add_exception(...)` method.

You can also do the ray-cast yourself using `get_world_3d().direct_space_state.intersect_ray(...)`, in which case you can disable both `hit_from_inside` and `hit_back_faces` through the `PhysicsRayQueryParameters3D` and thereby ignore _all_ shapes/bodies that you might be casting inside of.
