### ISSUE TITLE
Collisions with edges are incorrect

### ISSUE THREAD

**Issue by Gamepro5** [godot-jolt/godot-jolt#550]
When doing a down movement check for a floor normal, there is an edge case I found where, if you are on the perfect edge of a rect, it will be in this weird limbo state where the normal reported is a wall (so my code assumes it isn't on the floor and should apply gravity to slide along it), but the move_and_collide prevents it from moving down. In other words, the normal reported does not match the collision. This is only an issue when trying to step down a stair at a high physics tick rate and at a very low speed (0.01 m/s) (although you can also just get unlucky and have it happen at high speeds). Turning off recovery_as_collision sometimes fixes this, but not in this MRP for some reason. Either way, removing that causes other bugs in the character controller so I think recovery as collision is important.

Here's an MRP.
[bug.zip](https://github.com/godot-jolt/godot-jolt/files/12340373/bug.zip)

**Comment by mihe** [comment]
This one seems to be an unfortunate side effect of the way shape-casting is done in Godot, which I was forced to emulate in Godot Jolt.

Shape-casting in Godot is done using a binary search, where you effectively "stretch" the shape along the motion vector by the full distance, check to see if that results in a collision, and if it does, you pull back to half that distance and repeat the process, for a set number of steps, until you've ended up with two fractions that constitute the "safe" and "unsafe" fraction.

Since `move_and_collide` also uses this type of shape-casting as the second of the three phases that I've [described before](https://github.com/godot-jolt/godot-jolt/discussions/526#discussioncomment-6614828), it means that the third phase (the actual collision check) will happen wherever this unsafe fraction ends up being, and the precision of this unsafe fraction is dependent on the number of steps taken in the binary search.

In this particular case, where the number of steps in the search ends up being 4, the unsafe fraction ends up in such a way that the collision check is done in a place where the character's shape is technically penetrating more with the "floor" vertically than it does horizontally, leading to the X-axis being the resulting penetration axis instead.

I can "fix" this by cranking up the minimum number of steps, in this case to 11, but that means every call to `move_and_collide` and `move_and_slide` for all users everywhere will perform up to 7 more collision checks, which I don't think is warranted here.

Frankly, I don't understand why Godot Physics doesn't show the same behavior here. Godot Physics uses a hardcoded number of steps (8) as opposed to the variable amount that I use, so it should exhibit the same behavior, but for whatever reason Godot Physics ends up with an unsafe fraction that lands the character at a Y coordinate of 1.25009406, which is obviously 0.00009406 units above the ground, and as such shouldn't be unsafe. It's only thanks to the margin being taken into account in the third phase that it hits anything at all. Very odd.

Anyway, rather than messing with the steps here, the most efficient workaround for you is to simply run a `get_rest_info` (with the same margin) before doing `move_and_collide`, which will skirt around this whole issue with the unsafe fraction and just do a collision check where you're standing, giving you the collision normal you want.

**Comment by Gamepro5** [comment]
Sorry for the super late response.

> Anyway, rather than messing with the steps here, the most efficient workaround for you is to simply run a get_rest_info (with the same margin) before doing move_and_collide, which will skirt around this whole issue with the unsafe fraction and just do a collision check where you're standing, giving you the collision normal you want.

From what I understand, get_rest_info() only ever gives one normal. How does it know which normal to pick?
