### ISSUE TITLE
Bodies with locked axes emit NaNs when joint constrain same axes

### ISSUE THREAD

**Issue by phelioz** [godot-jolt/godot-jolt#558]
Updated from godot-jolt 4.1 to 6.0 and noticed a probably unintended change.

I receive a `nan` position for each rigid body when two rigid bodies, both with locked rotations or axis locks, are connected together by a Generic6DOFJoint or JoltGeneric6DOFJoint. This issue might occur with other joints, but I've only tested these two.

I've attached a minimal reproduction project that demonstrates how the rigid bodies attain the nan position.
[mrp.zip](https://github.com/godot-jolt/godot-jolt/files/12387415/mrp.zip)

This issue seems to be present in godot-jolt 5.0 as well, suggesting it was probably introduced in that version.

**Comment by mihe** [comment]
Thank you for reporting this, and for the MRP.

Without bisecting this properly, I am fairly certain that this is caused by #483, meaning version 0.5.0, which changed the axis-locking from being just an internal/hidden 6DOF joint to instead be done in a way where the body is given effectively infinite inertia on each axis to prevent it from rotating.

This seems to become a problem within Jolt itself when you have a joint attached that's also trying to constrain the bodies on all angular axes, resulting in the NaNs you ran into.

I'll see if I can deal with this on my end somehow, or if I need to forward this to Jolt. In the meantime the workaround is fairly straight-forward, just disable the limit on one or more of the angular axes on the 6DOF joint, which you shouldn't need in the case of that MRP, since the bodies can't rotate anyway.

**Comment by mihe** [comment]
Seems to also be a problem if you lock the linear axes and use a hinge joint.

**Comment by phelioz** [comment]
Thanks for the tip. Yeah it't not really a problem in my project right now. I did just disable the locked axis on one of the rigid bodies.

But a fix would of course still be nice ☺️ could be confusing to users why the get NaNs

**Comment by mihe** [comment]
The fix for this is included in the newly released [0.7.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.7.0-stable).
