### ISSUE TITLE
`HeightMapShape3D` triangulates differently from Godot Physics

### ISSUE THREAD

**Issue by dkaste** [godot-jolt/godot-jolt#566]
The actual triangles godot-jolt uses for calculations appear to be rotated 90 degrees. The difference can be clearly seen with "Visible Collision Shapes" enabled.

![triangles](https://github.com/godot-jolt/godot-jolt/assets/9663536/4ee8d459-9b2b-4d06-ba73-dc018c4707a8)

**Comment by mihe** [comment]
Thank you for reporting this.

This is something I've noticed myself in passing once or twice, since the discrepancy can be seen when turning on Jolt's debug rendering as well, but I never considered that it might actually be a practical problem, which was a bit sloppy of me.

Not only that, I actually triangulate it the same way as Godot Physics when you use a non-square height map, since it falls back to what's effectively a `ConcavePolygonShape3D` in those cases. So not only is it inconsistent with Godot Physics, it's inconsistent within the extension even.

If I crank up the amplitude on the example height map, it looks like this with Jolt's debug rendering:

![Debug height map](https://github.com/godot-jolt/godot-jolt/assets/4884246/53e69ebb-0945-4342-85c2-2d52557bc68e)

... which is not good.

**Comment by mihe** [comment]
The fix for this is included in the newly released [0.7.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.7.0-stable).
