### ISSUE TITLE
Sphere shapes collide with inactive edges

### ISSUE THREAD

**Issue by yosoyfreeman** [godot-jolt/godot-jolt#587]
I open another issue because https://github.com/godot-jolt/godot-jolt/issues/508 is indeed fixed.

A similar problem happens when a sphere is used, but in this case, it will collide between perfectly coplanar triangles too. 

https://github.com/godot-jolt/godot-jolt/assets/64601424/d877373b-2e74-432d-9910-694e7d63f8b3

This causes the ball to be launched against the floor. This is how it affects our game:

https://github.com/godot-jolt/godot-jolt/assets/64601424/7e0971ef-8b50-4a64-af37-de206d9a7cbe

The following minimal reproduction project contains two scenes equally setup with a box and a sphere for you to be able to compare quickly between the two.

[BallStuckBug.zip](https://github.com/godot-jolt/godot-jolt/files/12640936/BallStuckBug.zip)

**Comment by mihe** [comment]
Yeah, that does not look right. I'll dig into it.

**Comment by jrouwe** [comment]
@yosoyfreeman Are these triangles from the same mesh? And are you sure this edge is not part of a T-edge:

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/fd4d738d-389f-4acc-869c-33e910cc3fab)

Jolt can't detect active edges across different meshes and it currently treats all T-edges as active since there is are multiple edges that connects to that edge and it is currently not smart enough check if all neighbors are coplanar (mainly because it detects neighboring triangles by shared vertices and not if vertices happen to fall on an edge).

**Comment by yosoyfreeman** [comment]
Hi! The collision shape is a trimesh collision shape generated from a single mesh. I thought about this kind of scenarios being a variable so this example uses the original shape from https://github.com/godot-jolt/godot-jolt/issues/508. The mesh was scaled up to have a bigger top plane and the collision shape re generated accordingly. I thought using the same mesh would produce less variables. In our game, the collision shapes are also trimeshs. Hope this helps.

**Comment by jrouwe** [comment]
The mesh is indeed fine, the edge is not an active edge:

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/3df6c477-054f-4063-abe4-e51379da29c6)

For reference, the bottom of the shape has an active edge which is colored green:

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/364129c8-c266-4d17-9d1d-519145aa2160)

This is going to require some serious debugging, but I fear this is not going to be an easy thing to fix...

**Comment by jrouwe** [comment]
I'm able to repro the issue in the Jolt Samples app, initial investigation shows that the active edge code is working as expected:

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/db0484ce-0584-4029-80b6-9f6a30920f9e)

Both triangles produce a contact point and both normals are aligned. The problem is that the sphere sinks a little bit into the floor which means that the left contact point forms a bit of an obstruction and causes the ball to jump. A proper solution would be to ignore the left contact point altogether and only use the right contact point (which would require to move the active edge detection to run time instead of build time).

You can alleviate the issue by ensuring that the ball doesn't sink into the floor as much as it does right now. I was able to get this by setting the following settings in godot:

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/6b6ebb51-a5c3-4189-a524-c3afbf00fe8b)

Please experiment a bit with the values and let me know if this works.

**Comment by yosoyfreeman** [comment]
I'm currently testing this and trying to isolate other issues derived by this config that i can reproduce in my game but i want to isolate for reproduction purposes. I will provide all the information i can as soon as i can. Thank you for looking into this!

**Comment by yosoyfreeman** [comment]
Hi! I been testing the settings you said and i found some really unpredictable behaviors. With your settings and the scene as it was, the ball seems to jump but way less, almost imperceivable.  This is the result:

https://github.com/godot-jolt/godot-jolt/assets/64601424/7d85e2e2-862b-4049-8255-9aaa9fd2445e


However, when testing in my game i found the behavior of the ball unpredictable. I was able to isolate a couple of examples. Here you can see that, with half the speed, the ball now get stuck for several frames before continuing:


https://github.com/godot-jolt/godot-jolt/assets/64601424/3c6bfb55-04aa-42f4-b420-07402b2f7493


With boxes, they sometimes get stuck in the poly even far from the edges, but i'm unsure if it is related. But i was able to isolate also this (Which is included as a second scene in the reproduction project): 

https://github.com/godot-jolt/godot-jolt/assets/64601424/50a56579-e059-43e3-94a8-a603de7be2ab

As you can see, at an angle, the ball will only respond to collision if its spinning slow. The nearest ball accelerates so much quicker, so it gets stuck as soon as it touches floor. The second one get stuck at soon as it reach x speed.

Here is the reproduction project which contains both scenes i showed here.
[BallStuckBug_2.zip](https://github.com/godot-jolt/godot-jolt/files/12683722/BallStuckBug_2.zip)

**Comment by jrouwe** [comment]
From looking at the video, this could be an artifact of the lowered 'movement threshold' but I will investigate.

**Comment by danbronsema** [comment]
> I'm able to repro the issue in the Jolt Samples app, initial investigation shows that the active edge code is working as expected:
> 
> ![image](https://user-images.githubusercontent.com/1621693/268525424-db0484ce-0584-4029-80b6-9f6a30920f9e.png)
> 
> Both triangles produce a contact point and both normals are aligned. The problem is that the sphere sinks a little bit into the floor which means that the left contact point forms a bit of an obstruction and causes the ball to jump. A proper solution would be to ignore the left contact point altogether and only use the right contact point (which would require to move the active edge detection to run time instead of build time).
> 
> You can alleviate the issue by ensuring that the ball doesn't sink into the floor as much as it does right now. I was able to get this by setting the following settings in godot:
> 
> ![image](https://user-images.githubusercontent.com/1621693/268525694-6b6ebb51-a5c3-4189-a524-c3afbf00fe8b.png)
> 
> Please experiment a bit with the values and let me know if this works.

Preface: I'm a noob.

Just wanted to say that with those settings you provided, I was able to eliminate the 'jittering' that occured when my rigidbody3d sphere rolled over a collisionshape3d mesh. Thankyou!

**Comment by mihe** [comment]
Looks like this new enhanced internal edge removal that was just added to Jolt (jrouwe/JoltPhysics#882) fixes the original issue here, so long as it's not a cross-body edge. Neat!

@jrouwe How viable is this new flag as a project-wide setting? Considering you made it opt-in, and it requiring collection of faces, I'm assuming that the runtime cost is not trivial?

I don't really have a way of adding new properties to physics bodies from the extension side of things, so it would either need to be a project-wide thing, or I'd have to make Jolt-specific sub-classes, like `JoltRigidBody3D`, `JoltStaticBody3D`, and so forth, but that's something I've been trying my best to avoid.

I guess there's also the somewhat odd-looking alternative of creating a new non-spatial node whose only purpose is to "imbue" its first `PhysicsBody3D` ancestor with this flag, but it's not a pattern I've seen much in Godot.

**Comment by jrouwe** [comment]
> How viable is this new flag as a project-wide setting? Considering you made it opt-in, and it requiring collection of faces, I'm assuming that the runtime cost is not trivial?

I think it is quite viable as a project-wide setting. The algorithm itself is pretty expensive as it does many O(N) searches to deduplicate vertices, but it often leads to discarded contact points, which saves a whole bunch of time in the contact solver later. I think it will vary from scene to scene, but the [Ragdoll performance test](https://github.com/jrouwe/JoltPhysics/blob/master/PerformanceTest/RagdollScene.h) actually ran 8% faster with the new algorithm enabled. I need to do some more testing to see what it does for other scenes. Since it is new code, I'm not 100% sure that the results are correct in every case, so I kept it as an opt-in for now. It is not unlikely that with time the option will go away and it will be enabled by default.

Another thing that I think is interesting to look at is to try this new algorithm on regular collision tests, e.g. for issue jrouwe/JoltPhysics#630 I made a WeldingCollideShapeCollector for the move_and_collide function which didn't really work at the time. I think you could try dropping in InternalEdgeRemovingCollector (which just forwards the results to any other collector so should be compatible with anything you have). 

B.t.w. I see now that I forgot to forward the OnBody call, which I will fix shortly.

**Comment by mihe** [comment]
This new "Use Enhanced Internal Edge Removal" project setting (which is enabled by default) can now be found in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).

Note that this version targets the just recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.

A proper release will be out some time around Godot 4.3-stable.

**Comment by leftbones** [comment]
I was experiencing this issue, I updated my project to Godot 4.3 and Jolt 0.13.0-beta1 and it's still happening in the exact same way.

**Comment by leftbones** [comment]
> I was experiencing this issue, I updated my project to Godot 4.3 and Jolt 0.13.0-beta1 and it's still happening in the exact same way.
> 
> EDIT: I realized I had unchecked "Calculate Tangents" on my geometry (currently using CSG stuff for testing) and checking that fixed it again. Maybe this info will be helpful?

I take that back. It is definitely still happening, it's just not very consistent. It's worth noting that I am using a gravity scale of 2 on my rolling ball, but if I increase the gravity scale it seems to go away. That might just be due to the increased gravity making the jump not noticeable.

**Comment by leftbones** [comment]
> This new "Use Enhanced Internal Edge Removal" project setting (which is enabled by default) can now be found in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).
> 
> Note that this version targets the just recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.
> 
> A proper release will be out some time around Godot 4.3-stable.

I've spent the last 5 days tinkering with settings in and out of Jolt and I still can't fix this issue. The only thing that makes the "jumping" stop is using the default Godot physics. Can you comment on this please? Thanks.

**Comment by mihe** [comment]
I'll make a proper upstream issue for this shortly.

**Comment by mihe** [comment]
Reported upstream as jrouwe/JoltPhysics#1155.

**Comment by mihe** [comment]
It's probably worth pointing out that while this new "Use Enhanced Internal Edge Removal" setting will now (for real this time) fix the repro cases here, it will only work on edges that are internal to a single body.

So it'll work on things like internal edges within a single `ConcavePolygonShape3D` shape, or two `ConcavePolygonShape3D` within the same `StaticBody3D` that are right up against eachother, but it won't do anything for two separate `StaticBody3D`, each with their own `ConcavePolygonShape3D`, that are right up against eachother (commonly referred to as cross-body welding).

I figured I should mention that, in case there's any confusion about that.

**Comment by leftbones** [comment]
@mihe Just to be clear, the fixes are only included if you build from source currently, correct?

**Comment by mihe** [comment]
As of right now, yes. I'd like to publish another beta release before Godot 4.3-stable is out, but it's a fairly time-consuming process, so I can't say when that'll be.

**Comment by mihe** [comment]
[0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, which includes the proper fix for this.

Note that the release in the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.

**Comment by ryevdokimov** [comment]
> it won't do anything for two separate StaticBody3D, each with their own ConcavePolygonShape3D

Hi mihe, could you explain the reason for this limitation? 

I am trying to create a grid of static bodies with a box shape that are "cross-body welded", because I want to be able to adjust the constant linear velocity of each section of the grid independently to control the motion of an object moving along the grid.

**Comment by jrouwe** [comment]
The reason is that Jolt doesn't support it. It is very difficult to weld across bodies when those bodies are handled by different threads. Maybe someday it will be supported, but it will really hurt parallelism.

**Comment by ryevdokimov** [comment]
Thanks for the response jrouwe. I'm pretty ignorant at the moment on this topic, so sorry if my next questions might not make sense, but would it be possible to opt-in different bodies to be processed by the same thread, so that it could utilize that functionality?

**Comment by jrouwe** [comment]
To get there is quite a code rewrite and I'm not sure if I can do it without affecting performance when you don't care about cross body welding.

**Comment by ryevdokimov** [comment]
Understood, thanks for the info. I don't want to keep pinging the people here, so I may start a discussion upstream.
