### ISSUE TITLE
Joints aren't notified of center-of-mass changes

### ISSUE THREAD

**Issue by LunarShadow01** [godot-jolt/godot-jolt#594]
godot 4.1

I haven't been able to isolate the exact cause of this issue
I have also seen it happen with the native godot joints

in my project the player can add a collider to a rigidbody during run time
the joint holds to of these unique rigidbodies together

when a collider is added to one of the rigidbodies the body on which the collider was added will move slightly closer to the joint
but when you quickly disabled and enable any of the joints properties within a single frame
the rigidbodies will snap back to their appropriate position relative to the joint

this quick on and off is a good workaround for most cases but i felt that it should be reported anyways

**Comment by mihe** [comment]
Thank you for reporting this.

I hadn't considered this until now, but yes, joints store the relative transforms of the bodies they constrains, and in Jolt these transforms are relative to the body's center-of-mass. When you add a shape to a body it will (if "Center of Mass Mode" is set to "Auto") recalculate its center-of-mass but not actually report it back to the joint, leading to this weird snapping behavior.

The reason it works when you change some of the properties is because some of them (like the ones related to the joint limits) will force a full rebuild of the joint.

You can also set "Center of Mass Mode" to "Custom" to avoid this snapping behavior, but depending on your setup that might not be a suitable workaround.

**Comment by LunarShadow01** [comment]
damn, that was quick. thanks for the help. this project is super helpful
and yes the other workaround would not be suitable

**Comment by mihe** [comment]
The fix for this is included in the newly released [0.8.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.8.0-rc1). If you're able to, I'd appreciate it if you could give that release a try and report back whether it solves the issue for you.

**Comment by LunarShadow01** [comment]
i created a copy of my project and loaded 0.8.0 release candidate 1
after disabling my work around by escaping the function that implements the workaround i have not been able to observe the bug in my previous test scenario

**Comment by LunarShadow01** [comment]
as an extra test i did the same with my main project and the bug presents itself on the current LTS

**Comment by mihe** [comment]
The fix for this is now also included in the newly released [0.8.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.8.0-stable).
