### ISSUE TITLE
Custom nodes are not exposed to statically compiled languages

### ISSUE THREAD

**Issue by nothke** [godot-jolt/godot-jolt#632]
Is it possible to use Jolt types from C#? It is impossible to inherit from JoltGeneric6DofJoint3D for example, as the type doesn't exist or I can't find the right namespace it belongs to..?

**Comment by mihe** [comment]
No, this is not possible at the moment, unfortunately. This is a somewhat general problem with Godot, where bindings for statically compiled languages like C#, C++ and Rust are sort of "frozen in time" from when that build of Godot was made, and anything exposed by a GDExtension (or even GDScript as seen [here](https://docs.godotengine.org/en/stable/tutorials/scripting/cross_language_scripting.html)) won't be available from these languages. I've been meaning to investigate this since long before I even added the Jolt-specific nodes, but I haven't gotten around to it.

My initial hope/ambition was to distribute a separate NuGet package with bindings that somehow utilize `GodotObject.Get`, `GodotObject.Set` and `GodotObject.Call` to at least make the interface more ergonomic, but honestly I'm not sure how well that plays out in practice. I don't think you'd be able to things like inherit from such a class in any case.

There are other alternatives as well, like the approach taken by the [Debug Draw 3D](https://github.com/DmitriySalnikov/godot_debug_draw_3d#c) extension, where the bindings are generated on-demand by the extension through an editor action and compiled along with the rest of the Godot project. I believe the circumstances for Debug Draw 3D are quite different though, in that the entirety of the API can be expressed as a `static class` in C#, which makes this approach a lot more feasible.

The workaround in the meantime would be to utilize things like `GodotObject.Get`, `GodotObject.Set` and `GodotObject.Call` yourself when interacting with these nodes from C#. I don't think there's anything like that which would let you inherit from the class, but you could always make your own wrapper for it instead I guess.

**Comment by simeonradivoev** [comment]
Can you get access from a another GDExtension if not from C#?

**Comment by mihe** [comment]
Assuming your GDExtension is written in C, C++ or Rust, or any other statically compiled language, you'd have the exact same issue, and you would need to use `Object::get`, `Object::set` and `Object::call` to interact with any of the custom nodes.

If it's written in some dynamic language like Python or Lua (that isn't relying on bindings generated by `extension_api.json`) it might be a different story, but I'm not familiar enough with the scripting side of GDExtension to really say for sure.

And just be clear, you can still use this extension just fine to power all the default Godot nodes (`RigidBody3D`, `Generic6DOFJoint`, etc.) which you can obviously interact with just fine from another GDExtension, but using the substitute joints (`JoltGeneric6DOFJoint`, etc.) won't be very ergonomic unfortunately.

**Comment by simeonradivoev** [comment]
I'm new to the GDExtensions, but how do different GDExtensions communicate typically? My thinking was if there was a way to access the more advanced features of jolt, for example the simulation rollback.

**Comment by mihe** [comment]
There is no such channel of communication between extensions, official or otherwise. The only public symbol that's exposed from the DLL is the extension entry point, which then registers the physics server, the custom nodes, the editor plugin, etc.

Rollback in particular is also not something you'll be likely to achieve by just exposing the underlying Jolt stuff to some other extension. See [this](https://github.com/godot-jolt/godot-jolt/pull/637#issuecomment-1757743646) comment for more details as to why.

**Comment by mihe** [comment]
This is unlikely to ever be addressed from this extension alone, and with this extension now having been merged into Godot in the form of an engine module (see [README](https://github.com/godot-jolt/godot-jolt?tab=readme-ov-file)), albeit without the substitute joint nodes, it will be considered to be in maintenance mode going forward, where only bug fixes will be considered for merging. As such, I'll go ahead and close this issue.

Note that the joint properties introduced by the substitute joint nodes (`JoltGeneric6DOFJoint3D`, etc.) will eventually be exposed by the new Godot engine module on the default joint nodes instead, when such a mechanism is in place. At that point we'll likely find ourselves with the same problem of not being able to access them from statically compiled languages, but hopefully we can come up with some kind of solution for it.
