### ISSUE TITLE
`move_and_slide` with cylinder shape gets stuck on 90-degree edge

### ISSUE THREAD

**Issue by X8E85yST** [godot-jolt/godot-jolt#634]
I have done alot of testing with this and distilled it down to an MRP. Basically when walking up a "triangle" (I dont know a better name, sorry!) sometimes the player can get stuck. This happens with default godot-jolt settings on 0.8.0 and with shape margins and speculative collision detection disabled.  This happens on these slants (the only ones ive tested) 45 degrees, 30, 20. I have not tested any other collision shapes.

The MRP uses https://github.com/rbarongr/GodotFirstPersonController as a base.
Please note that I am manually setting the position of the player controller in the _ready() function of the controller. This is because finding some way to move the player and always hit a stick seemed impossible. If you keep walking over the edge over and over you are likely to hit it. If something is off with the MRP please let me know!

Do note that the MRP does not have the addons or .godot folder.

[MRP-TriangleStuck.zip](https://github.com/godot-jolt/godot-jolt/files/12847112/MRP-TriangleStuck.zip)

**Comment by mihe** [comment]
Thank you for taking the time to report the issue, and for providing a minimal repro.

> Basically when walking up a "triangle" (I dont know a better name, sorry!) sometimes the player can get stuck.

This is indeed an issue about triangles, and is somewhat of a known issue, especially when using a cylinder or box shape for your character. In this particular scene the problem is made worse by the fact that you have the character's `floor_max_angle` set to 45 degrees while also walking up a slope of 45 degrees, which will make the underlying issue even worse due to floating-point precision problems.

The underlying issue is that both Jolt and Godot Physics will eventually (although not necessarily in the same scenarios) collide with the edges of individual triangles of a `ConcavePolygonShape3D`, especially when walking up slopes like this. In this particular scene that triangle ends up being one of the two that makes up the opposite side of the slope, resulting in a collision/contact normal that's angled more horizontally than it would normally be, since that happens to be the shortest path by which to separate the character from this particular triangle. `move_and_slide` will then interpret this as being too steep of a floor (i.e. a wall) and stop any further movement.

Jolt tries to mitigate this problem to some degree with a technique dubbed [active edge detection](https://youtu.be/EanFxlkZgcA), which when creating a `ConcavePolygonShape3D` will go through and label every triangle edge as either "active" or "inactive", determined largely by the angle between the two triangles sharing the edge, where an edge will be "inactive" so long as the angle between the two triangles is within a certain threshold. This threshold is currently set to 50 degress in Godot Jolt, as seen [here](https://github.com/godot-jolt/godot-jolt/blob/c8b9689ceb06164b5b377f9a4419f50a97dc1c2b/src/shapes/jolt_concave_polygon_shape_impl_3d.cpp#L7). When you then collide with an "inactive" triangle edge Jolt will simply override the collision/contact normal to be the surface normal of the triangle instead.

So in this particular scene, with the angle between the slope's faces being 90 degrees, this triangle edge ends up being "active" and the above mentioned mitigation is not used at all. It is technically possible to set the above mentioned threshold to 90 degrees instead, which would make this specific triangle edge "inactive" instead and thereby "fix" the problem. The issue with increasing this threshold any further is that it also affects `RigidBody3D`, which can end up with artifacts like sinking into edges when this threshold is set too high, from what I understand.

Here's a diagram of what it looks like when the edge is treated as an active edge (like it is now) and what it would look like as an inactive edge:

![image](https://github.com/godot-jolt/godot-jolt/assets/4884246/a438ed11-0c9c-4e55-a4eb-a22c14cd917e)

All that is to say that there is no real solution in this case. The options are basically one or several of the following:

1. Don't have slopes that are too close to your `floor_max_angle`.
2. Use a capsule shape instead of a cylinder/box, which when combined with option 1 should make the problem much less likely to happen.
3. Expose the active edge threshold as a project setting, allowing you to set it to 90 degrees and evaluate whether the trade-offs are worth it.
4. Try to improve `move_and_slide` itself by mixing in actual surface normals and choosing between that or collision/contact normals based on some heuristic.

I'll probably go ahead with option 3 either way, which I probably should have done to begin with, but as mentioned it's not exactly a panacea. Option 4 is a big and scary change (on the Godot side of things) in terms of the impact it has, so is unlikely to happen any time soon.

**Comment by X8E85yST** [comment]
I haven't noticed this issue happening more frequently on slopes of 45 degrees compared to 20/30. I guess it is more about having a walk-able angle greater than 50 degrees.

I do wish I could use a capsule shape to avoid most of these issues. But having a flat bottom is very important to the type of game I am trying to make. In the worst case scenario I can try to design levels to avoid encountering issues.

Exposing a setting seems like a great option and I am excited to test it out whenever it gets merged and released!

I do have one question, would compiling jolt with double precision support fix some of the float precision issues? I am not too familiar with float imprecision.

Thanks for the quick and thorough response!

**Comment by mihe** [comment]
> I haven't noticed this issue happening more frequently on slopes of 45 degrees compared to 20/30. I guess it is more about having a walk-able angle greater than 50 degrees?

The floating-point problem might be more of an issue when you use a capsule shape rather than a cylinder. In either case I would recommend avoiding slopes close to your `floor_max_angle`, since there are other edge-cases that can trip you up in that scenario.

> having a flat bottom is very important to the type of game I am trying to make

Just out of curiosity, what are the reasons for needing to have a flat bottom?

> I do have one question, would compiling jolt with double precision support fix some of the float precision issues?

I don't currently support compiling this extension with double-precision support, but even if I did the results would be unclear in this case. Jolt's double-precision support is somewhat conservative, so it might or might not have an effect here. Either way, it would only really help with the issue of slopes being very close to your `floor_max_angle`, which you should ideally avoid either way.

**Comment by X8E85yST** [comment]
I am making a FPS precision platformer. Having curved endpoints makes the game feel floaty and not crisp and predictable.

**Comment by mihe** [comment]
I went ahead and marked this as fixed/closed in conjunction with adding this new project setting. I don't consider it a proper fix by any means, but frankly it's the only realistic option here. If this doesn't pan out there's not a whole lot that can be done besides changing `move_and_slide` itself on the Godot side of things.

**Comment by X8E85yST** [comment]
Thanks for the quick merge, I'll test it when 0.9.0 hits!

**Comment by mihe** [comment]
I just released [0.9.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.9.0-stable), which has this new "Active Edge Threshold" setting, if you want to try it.

**Comment by X8E85yST** [comment]
I just tested this with 90 degree active edge threshold. 

It is unfortunately causes a lot of issues with movement, for example in the MRP jumping at the edge of the triangle basically allows you to walk along the edge of the wall if you spam the jump button. If you stop jumping its as if you are on the floor.

In my own character controller standing at the top of a triangle and trying to commit to a movement moves me in a fixed direction no matter which movement buttons I hit.

**Comment by mihe** [comment]
> It is unfortunately causes a lot of issues with movement

That is unfortunate.

> In my own character controller standing at the top of a triangle and trying to commit to a movement moves me in a fixed direction no matter which movement buttons I hit.

What do you mean by "standing at the top of a triangle"? As in standing on a triangle edge or just flat on its surface?

> This has made me curious in how other games, most notable source engine games, work around this problem since it doesn't happen there with a box collider. Its probably all handled by havok though.

In my limited experience player controllers are usually tailored to the specific physics engine, if not provided by it directly. I assume there's a lot of trickery you can do when you can make assumptions about its behavior.

Jolt's own character controller alleviates this issue to some degree by doing something similar to option 5 mentioned earlier, where it picks either the surface normal or the collision normal based on which of the two that points the most upwards, using the up-vector configured for the character, as seen [here](https://github.com/godot-jolt/jolt/blob/7df682edda5dee5f0445ceba27513f9e623dd758/Jolt/Physics/Character/CharacterVirtual.cpp#L93-L94). Unfortunately I'm not able to do that with `move_and_slide` due to not having access to the `CharacterBody3D` up-vector in the specific part that I'm responsible for implementing, hence why this would require modifications to `move_and_slide` itself on the Godot side of things instead.

Anyway, like I hinted at before, I'm not sure what else I can really do here. I'll experiment with improving `move_and_slide` at some point, since it would benefit not only this extension but Godot Physics as well, but it's a scary change, and might not pan out.

**Comment by X8E85yST** [comment]
Yes, I do mean standing on the triangle edge, sorry for the poor wording.

Thank you for the in depth explanations and the work you have done!
