### ISSUE TITLE
`move_and_slide` jitters when colliding with flat wall and angled surface

### ISSUE THREAD

**Issue by ghost** [godot-jolt/godot-jolt#643]
When running against a gap that is barely not large enough for the collision shape the CharacterBody3D will jitter and jumping is affected.

**Cylinder Shape**: The CharacterBody3D will jitter and is_on_floor() will flip between true and false. Jumping is nearly impossible since you do not get the right amount of height from a jump.

**Capsule Shape**: The CharacterBody3D will jitter and is_on_floor() will flip between true and false. Jumping is nearly impossible since you do not get the right amount of height from a jump.

**Box Shape**: The CharacterBody3D will jitter **but is_on_floor() is right**. Jumping is nearly impossible since you do not get the right amount of height from a jump.

_The jumping bug does still happens when the gap is much smaller than the width of the collision shape._

Setting the amount of max_slides to a value much higher ( I use ~20) than default will fix the jumping issue, but the jitter issue and is_on_floor() issue is still present. This happens with 60 physics ticks per second and 100 physics ticks per second with no change. These scenarios occur with default jolt settings on 0.9.0 and 0.8.0. Not entirely sure if this is a known issue or not. Since it affects the most common collision shape I thought it would be worth making this issue anyways.

MRP is included.  The .godot and addons folder are not present in the MRP so godot-jolt needs to be installed.
Setting the max amount of slides is commented out in the _ready() function. is_on_floor() is printed at the beginning of every physics tick in the console. All that is needed to change collision shapes is to change CShape in player.tscn (The default sizes of the named collision shapes are what should be used).

[MRP-Jittering.zip](https://github.com/godot-jolt/godot-jolt/files/12890919/MRP-Jittering.zip)

**Comment by mihe** [comment]
Thank you for reporting this, and for providing the minimal repro.

> Jumping is nearly impossible since you do not get the right amount of height from a jump.

Assuming I'm actually performing the repro correctly, this particular thing seems to happen with Godot Physics as well, where jumping will be severely hindered when you push yourself into one of these corners. Bumping up `max_slides` to a higher value does indeed fix this, as you point out.

As for the jittering and flip-flopping of `is_on_floor`, I'll have to do some more in-depth debugging to see why/where this diverges from Godot Physics. I would've bet money on it being a regression caused by #559, similar to #626, since that seems to have messed with some floor stuff internally within `move_and_slide`, but that does not appear to be the case.
