### ISSUE TITLE
CharacterBody3D touching a RigidBody3D when RigidBody3D is removed gives error on move_and_slide

### ISSUE THREAD

**Issue by knil79** [godot-jolt/godot-jolt#645]
A CharacterBody3D touching a RigidBody3D when the RigidBody3D is removed gives error on move_and_slide

E 0:00:04:0630   CharacterBody3D.gd:31 @ _physics_process(): Parameter "body" is null.
  <C++ Source>   src\servers\jolt_physics_server_3d.cpp:1114 @ _body_get_direct_state()
  <Stack Trace>  CharacterBody3D.gd:31 @ _physics_process()

I have created a test scene made in v4.1.2.stable.mono.official [399c9dc39] (I'm a bit proud I was able to recreate it so fast outside my own huge project)

[godot_jolt_move_slide_bug.zip](https://github.com/godot-jolt/godot-jolt/files/12908089/godot_jolt_move_slide_bug.zip)

**Comment by mihe** [comment]
Thank you for reporting this, and for providing the minimal repro.

Apparently `PhysicsServer3D.body_get_direct_state` is meant to quietly return null when passed an invalid RID, which is used by `move_and_slide` to determine whether a previously used platform has been freed or not. I'm not sure I love this behavior, but I don't have much choice but to conform I guess.

Anyway, the error itself is not indicative of any problem, and you can safely ignore it until it's fixed in the next release.

**Comment by mihe** [comment]
Apologies for the long wait, but the fix for this is included in the newly released [0.10.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.10.0-rc1).

If this is still relevant to you then I'd appreciate it if you could give that release a try and report back whether it fixes the problem for you.

**Comment by knil79** [comment]
I can confirm that v0.10.0-rc1 fixes the problem :)
