### ISSUE TITLE
`Area3D` generates contacts in "Visible Collision Shapes"

### ISSUE THREAD

**Issue by Conz3D** [godot-jolt/godot-jolt#649]
It seems there a bug in the "Debug" -> "Visible Collision Shapes", there is an offset in the display of the contact points in v.0.9. I haven't notices this in 0.8.
In my case I can see this with compound shapes and shapes that are connected by joints.

![jolt_debug_display_bug01](https://github.com/godot-jolt/godot-jolt/assets/129608680/43bb7e69-ed49-4ce4-af19-249fbe8730ed)
![jolt_debug_display_bug02](https://github.com/godot-jolt/godot-jolt/assets/129608680/24af3c9f-4589-413e-b177-9f6e6c80f41a)

It seems like it's only the debug display, the simulation itself looks ok.

(Or could this be based on my update process of the scenen from v.0.8 to v.0.9?)

**Comment by Conz3D** [comment]
Maybe my test scene can help to pin it down:
[godot_jolt_debug_display_bug.zip](https://github.com/godot-jolt/godot-jolt/files/12999364/godot_jolt_debug_display_bug.zip)

**Comment by mihe** [comment]
What you're seeing are the contact manifolds between the `Area3D` ("ObjectRemover") and the various `RigidBody3D`. Unlike Godot Physics areas are (mostly) just regular bodies in Jolt and generate contacts like any other body, and since I don't filter them out in any way they show up in "Visible Collision Shapes" as well. This is not a regression and has been the case since I first implemented "Visible Collision Shapes".

I can definitely see it being quite annoying in this particular scene though, and is obviously a discrepancy with how Godot Physics behaves in either case, so maybe I should just omit the debug contact points if either of the two bodies is an `Area3D`.

**Comment by Conz3D** [comment]
Thank you!

**Comment by mihe** [comment]
Apologies for the long wait, but the fix for this is included in the newly released [0.10.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.10.0-rc1).

If this is still relevant to you then I'd appreciate it if you could give that release a try and report back whether it fixes the problem for you.

**Comment by Conz3D** [comment]
> If this is still relevant to you then I'd appreciate it if you could give that release a try and report back whether it fixes the problem for you.

Just upgraded my project to the 0.10, and the debug display seems to be fixed, cool. 
Thank you for your work on this AddOn.
