### ISSUE TITLE
Strange results from PhysicsDirectSpaceState3D.collide_shape against trimesh colliders

### ISSUE THREAD

**Issue by phelioz** [godot-jolt/godot-jolt#662]
Get some strange results from PhysicsDirectSpaceState3D.collide_shape when using it against trimesh colliders.

Added a some videos and a MRP that shows the behaviour and the differences in using collide_shape with a sphere shape against a box collider and against a trimesh  (ConcavePolygonShape3D).

One of the points on the collider seems to follow edges on the trimesh. 

Left is a BoxCollider3D and the right one is a Trimesh (ConcavePolygonShape3D)
Transparent sphere to indicate the collide_shape shape. 
Pink sphere for collider contact point and green sphere for the contact point on the collide_shape shape.

https://github.com/godot-jolt/godot-jolt/assets/4129503/cbdcf815-31d0-48db-bfbb-c484632cd767

If the orign of the collide_shape is exactly a the edge of the trimesh we get even stranger results.

https://github.com/godot-jolt/godot-jolt/assets/4129503/05da04af-acfe-415f-860e-bd48a2fe1c8c

Attached MRP:
[jolt-physics-trimesh.zip](https://github.com/godot-jolt/godot-jolt/files/13205080/jolt-physics-trimesh.zip)

**Comment by phelioz** [comment]
I'm experiencing similar issues with Godot Physics, so it seems the problem may not be solely related to Godot Jolt.
Created a issue for it on the Godot repo [#84187](https://github.com/godotengine/godot/issues/84187)

**Comment by mihe** [comment]
I'm not an expert on the inner workings of collision detection, so take this with a grain of salt, but that looks to be about what I'd expect, since you're colliding with that face of the mesh cube, which consist of two triangles. The contact points you're seeing look to be about right if they're meant to represent the closest point on each of the two triangles relative to the sphere.

Contrary to what one might expect (myself included) mesh shapes are not treated as a cohesive surface but instead as the individual triangles that they in fact are. As such, I don't believe this is a bug, and something you'll likely see with other physics engines as well.

**Comment by phelioz** [comment]
Hoped that wasn't the case, but understandable. Thanks for the explanation, makes sense!
