### ISSUE TITLE
Kinematic bodies with contact reporting don't detect other kinematic/static bodies

### ISSUE THREAD

**Issue by Janblu** [godot-jolt/godot-jolt#682]
Honestly, this one has stumped me greatly.

A frozen Rigidbody3D cannot detect other frozen Rigidbody3D's when using Jolt Physics. This is true regardless of whether freeze_mode is set to static or kinematic for either object.

The behaviour also seems tied to collision layers and/or masks, in fact that might be the cause but I haven't been able to test it that well.

Unfrozen Rigidbody3D's can reliably detect and be detected, though the signal doesn't fire on the frozen Rigidbody3D with freeze_mode static.

The intended behaviour, according to the default physics, is that the frozen Rigidbodies at least fire their collision signals if contact_monitor is set to true. This is not happening in Jolt.

Steps to reproduce:
1. Download the following project: [Jolt rigidbody freeze test.zip](https://github.com/godot-jolt/godot-jolt/files/13344045/Jolt.rigidbody.freeze.test.zip)

2. Install Godot Jolt addon
3. Run scene using default physics to observe intended behaviour, note the output log when the Rigidbodies with scripts detect a collision
4. Switch to JoltPhysics3D
5. Run scene again with broken behaviour
6. Feel free to change the following values for the Rigidbodies with a script attached: freeze, freeze_mode, collision_layer, collision_mask

Edit: Tested in Godot 4.1.3 and Godot 4.2_beta6

**Comment by mihe** [comment]
This one threw me for a loop as well. I could've sworn I had tested this exact thing a while back, but it might very well have been that I only ever tested kinematic vs dynamic contact reporting.

@jrouwe Judging by `JPH::Body::sFindCollidingPairsCanCollide` I'm guessing that kinematic-vs-kinematic and kinematic-vs-static contacts have in fact never worked in Jolt, presumably for the same reason that sensor-vs-static contacts are opt-in, meaning it could potentially severely impact the contact cache?

Is there any chance of maybe allowing kinematic-vs-kinematic and then having kinematic-vs-static be opt-in similar to sensor-vs-static?

**Comment by mihe** [comment]
@Janblu If you need a workaround in the meantime then you should be able to child an `Area3D` to your bodies using the same collision shapes and hook up to their `body_entered` signals instead. You might also need to enable the "Areas Detect Static Bodies" project setting if you want to detect static bodies. Just be mindful of the warning mentioned [here](https://github.com/godot-jolt/godot-jolt/blob/master/docs/settings.md#jolt-3d).

**Comment by jrouwe** [comment]
> Judging by [JPH::Body::sFindCollidingPairsCanCollide](https://github.com/jrouwe/JoltPhysics/blob/b084d8f9054d78cb50bc851cc4db505462c4c634/Jolt/Physics/Body/Body.inl#L47-L53) I'm guessing that kinematic-vs-kinematic and kinematic-vs-static contacts have in fact never been generated in Jolt, presumably for the same reason that sensor-vs-static contacts are opt-in, meaning it could potentially severely impact the contact cache?

That's right, this was never supported since kinematic objects cannot change velocity due to a collision so detecting the collision was pointless and since it is easy to misconfigure the layers and pay a lot of CPU cost in narrow phase collision detection only to ignore the result. I guess it would be possible to create a flag like ```Body::SensorDetectsStatic``` for kinematic objects, but it does increase the complexity of the code again and the code complexity there already makes my head hurt.

Technically you can already achieve kinematic colliding with kinematic/static by making a dynamic body, giving it zero damping and a gravity factor of zero and in the contact callback setting the inverse mass/inertia scale to 0, but if this is a desirable solution is debatable.

**Comment by mihe** [comment]
> I guess it would be possible to create a flag like `Body::SensorDetectsStatic` for kinematic objects, but it does increase the complexity of the code again and the code complexity there already makes my head hurt.

Would it make it any simpler if the existing `SensorDetectsStatic` flag was removed in favor of more generalized flags, like `AlwaysDetectKinematic` and `AlwaysDetectStatic`, that would then be applicable to any body (except static ones I guess) regardless if it's a sensor or not?

Otherwise I'm perfectly fine with just documenting this as a known discrepancy and closing this issue as `wontfix`. I don't think omitting this is a huge deal personally.

I feel like kinematic bodies in general became sort of a second-class citizen in Godot 4 when they dropped `KinematicBody` in favor of `CharacterBody3D`, which doesn't have the ability to do any sort of contact reporting anyway. It's only thanks to the ability to "freeze" a `RigidBody3D` as kinematic that you have access to this, and there are plenty of other `RigidBody3D` properties that don't make a whole lot of sense when you do, and even more so when you freeze it as static.

**Comment by jrouwe** [comment]
> Would it make it any simpler if the existing SensorDetectsStatic flag was removed

Yes, this crossed my mind to but would mean that I would need to bump Jolt to v5.0.0 because of the API change.

> Otherwise I'm perfectly fine with just documenting this as a known discrepancy and closing this issue as wontfix

I would say: Let's see how many people actually want this. If this turns out to be something popular then I'll add a flag and bite the bullet.

**Comment by mihe** [comment]
> Yes, this crossed my mind to but would mean that I would need to bump Jolt to v5.0.0 because of the API change.

Right, yes, that's certainly not warranted here.

> I would say: Let's see how many people actually want this. If this turns out to be something popular then I'll add a flag and bite the bullet.

Fair enough. I'll leave this open then.

**Comment by jrouwe** [comment]
I've collected enough breaking changes that I need to release a v5.0.0 anyway, so I went ahead and renamed the option and made it possible to get callbacks for kinematic vs kinematic/static.

**Comment by mihe** [comment]
Naming things is hard, but with how this manifests for the user in Godot I went ahead and made this opt-in through a new project setting called "Report All Kinematic Contacts", which is opt-in for the same performance reasons that "Areas Detect Static Bodies" is opt-in, as talked about already.

**Comment by yosoyfreeman** [comment]
Thank you so much both of you for having feedback into account for this! I do think it will be very useful!

**Comment by mihe** [comment]
You can find this new project setting in the newly released [0.12.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.12.0-stable).
