### ISSUE TITLE
Holes in `HeightMapShape3D` use a different constant from Godot Physics

### ISSUE THREAD

**Issue by TokisanGames** [godot-jolt/godot-jolt#688]
Godot-Jolt v0.10. Win11/64. Godot 4.1.3. Terrain3D 0.9-dev

In a heightmap shape, I can set a vertex to NAN and in Godot physics the vertex ceases to exist, allowing us to create actual holes. 

In Godot-jolt, when set to NAN, the vertices are still present but are set to a low value. When nearby vertices were 100, the hole vertices went to -38.4. But when I sculpted down to -50, the hole vertices also went to -50. So holes are somewhere between pits and solid floors/walls. But there may be instances where hole vertices actually protrude from nearby mesh vertices, as I haven't tested all possibilities of angles and heights. 

`visible collision shapes` does not draw these NAN vertices at any visible height. If I set the vertices to +/-INFINITY, the whole collision shape stops functioning.

If you can make it work like Godot Physics that would be great. Holes has been our # 1 request, FYI.

**Godot Physics**

https://github.com/TokisanGames/Terrain3D/assets/632766/9974e86c-e20d-45d0-a222-10a61566e8c8

**Jolt Physics**

https://github.com/TokisanGames/Terrain3D/assets/632766/f59bf606-8bc9-4159-b778-0bb382abbb5b

Here's a build of Terrain3D that will work with 4.1.3 or 4.2rc1 if you want to experiment. Use the hole tool on the left bar, paint some holes, and run the scene. Collision builds at runtime. You can also enable `debug/show_collision` in the inspector to see it in the editor.
https://github.com/TokisanGames/Terrain3D/actions/runs/6915856803

Here's where I set NANs in the code. This is in our 0.9-beta branch, which will be our next release in 2-4 weeks.
https://github.com/TokisanGames/Terrain3D/blob/3bf0a750cbfad676ab3a456f6e070a278e8d8b5f/src/terrain_3d.cpp#L333

**Comment by mihe** [comment]
This is something I ran into myself a while back that I really should have dealt with at the time, or at least made an issue for.

> In Godot-jolt, when set to NAN, the vertices are still present but are set to a low value.

Jolt (and this extension as a result) supports this already, but Jolt uses `FLT_MAX` as its magic constant instead of `NAN`, as seen [here](https://github.com/jrouwe/JoltPhysics/blob/6535d6ca60a47bed90153730b3fc3a409d48e274/Jolt/Physics/Collision/Shape/HeightFieldShape.h#L22-L23).

Seeing as how GDScript doesn't define `FLT_MAX` as a named constant you unfortunately have to use the actual numeric constant instead, meaning `3.402823466e+38`, which is certainly not ideal. I believe C# does however define this, as `float.MaxValue`.

> If you can make it work like Godot Physics that would be great.

I'm curious, is this an actual documented thing in Godot Physics? I get that it's a thing that works, but I can't seem to find any trace of this in the documentation nor the actual implementation.

Anyway, this would of course be trivial to fix by just translating `NAN` to `3.402823466e+38` on my end. The one potential downside with that is having to marshal every height value one-by-one, but seeing as how I'm already doing it row-by-row in order to transpose the height map to fit with Jolt's triangulation I guess it wouldn't be all that much worse.

**Comment by mihe** [comment]
> The NAN/INFINITY macros are compiler dependent

I was not aware of this. That would certainly be a problem if I were to do any sort of translation on my end.

In any case, I'm not sure how I missed this, but [the documentation](https://docs.godotengine.org/en/stable/classes/class_heightmapshape3d.html) does mention that "holes in a `HeightMapShape3D` are created by assigning very low values to points in the desired area", which I guess technically applies to this extension as well, although it would presumably have a negative effect on the block compression by not using the designated magic constant.

At the same time, there seems to be an [unresolved/open proposal](https://github.com/godotengine/godot-proposals/issues/2746) for this feature at the moment, hinting at the possibility that holes are indeed not officially supported by Godot Physics and that this `NAN` thing is mostly a happy accident.

> Godot/Jolt: At some angles the visible shapes connect with cones. At other angles they show as holes. NAN shows holes at all camera angles.

I have no control over how "Visible Collision Shapes" draws anything, unfortunately. That's all happening on the Godot side of things, based on its interpretation of the shape data. An issue/PR for Godot itself would probably be advisable here.

> Jolt: collision is only one way. The player collides with the top side of the terrain. When going through a hole, it will pass through the backside, either as a roof or wall. This is less of a concern as they're going to have their own tunnels/caves. But in Godot physics, the collisions happen on both sides. Is there an option to turn that on in Jolt?

This a somewhat deliberate (undocumented) discrepancy on my part.

It is technically possible to set the back-face mode for the shape queries that happen as part of things like `move_and_slide`, but whichever way you turn it you end up with a behavior that differs from Godot Physics.

Godot Physics will (as you point out) collide with the back-faces of a `HeightMapShape3D`, but it won't by default collide with the back-faces of a `ConcavePolygonShape3D` unless you enable its `backface_collision` property. That last part is true for this extension as well. This means that if I were to always enable back-face collisions for shape queries then I would align with how Godot Physics behaves with `HeightMapShape3D`, but I would start to differ in behavior with (the arguably much more widely used) default behavior of `ConcavePolygonShape3D`.

Of course I could add a project setting to make this opt-in, but I try to be conservative with adding new project setting, and I don't think adding a new setting is justified here. The proper solution would instead be to introduce something like the `backface_collision` property for `HeightMapShape3D` on the Godot side of things.

With all that in mind, I don't think there's much I can/should do here, so I'll go ahead and close this for now.

**Comment by mihe** [comment]
I just realized that I can actually just use the same solution for back-face collisions with `HeightMapShape3D` that I use for the `backface_collision` property of `ConcavePolygonShape3D`, but just treat it as always being `true`, so I went ahead and pushed that as #691.

Expect to see it in the next release, which will likely be when Godot 4.2-stable is out.

**Comment by TokisanGames** [comment]
Godot has problems using INFINITY, but works well with NAN. So what I'm doing now is using one or the other depending on which physics engine is selected.

https://github.com/TokisanGames/Terrain3D/blob/b53fb7081db9ba38792dcbf48c7ec7bc7f8201eb/src/terrain_3d.cpp#L297-L300

**Comment by mihe** [comment]
@TokisanGames I went ahead and added support for NaN holes as well, using `std::isnan`. Loading times might take a slight hit, but even without profiling it'll probably be fine in the grand scheme of things.

I assume you'll still need to do your `physics/3d/physics_engine` check though, since people could be using older versions of Godot Jolt that don't support NaN, but now it's supported at least.

I also realized I had been sloppy when I added the back-face collision and forgot to do so for non-square height maps, which I'm currently representing using Jolt's `MeshShape` rather than its `HeightFieldShape`, so that's been added as well now. I assume you only ever use square height maps though, so that's probably not relevant to your stuff.

Anyway, expect to find all this in version 0.12.0, which should be out some time next week.
