### ISSUE TITLE
Jolt enabled project fails to export in CICD

### ISSUE THREAD

**Issue by evan-gordon** [godot-jolt/godot-jolt#711]
### Problem Description
I started setting up a gitlab CICD pipeline today for a small project I've got that uses Jolt and ran into some issues preventing my pipeline from successfully completing. This seems to be due to running from command line when the .godot folder is not present.

### Context
Due to some of the current godot engine oddities godot must be launched once which triggers an import of all assets and libraries (as the .godot folder shouldn't exist) from there another godot run should be launched  that actually does the compiling.

I setup my pipeline but it kept hanging during the initial empty run. The command that needed to run was `godot -v -e --quit --headless` (again on a machine with no .godot folder). I was also able to reproduce this locally and did confirm that this indeed only happened when running projects with godot-jolt.

### Steps to reproduce
* Setup a new godot 4.2 project
* Add the godot-jolt package and enable it
* Delete the .godot folder
* from a linux terminal run `godot -v -e --quit --headless`

I haven't been able to figure out any workarounds here, but if I find some time I might dig a bit more into what's going on (no promises though :) )

**Comment by mihe** [comment]
> and did confirm that this indeed only happened when running projects with godot-jolt

I don't believe this is specific to this extension, and likely happens with any GDExtension.

This is almost certainly because you don't have an `extension_list.cfg` when you start up a project fresh for the first time, i.e. without a `.godot` folder.

If (before running Godot) you create a `.godot/extension_list.cfg` file containing a single line, like this:

```
res://addons/godot-jolt/godot-jolt.gdextension
```

It should be able to load the extension right away without needing a restart first.

Some people even commit this file into their source control, which should be fine I guess, since it's not really transient/temporary/local in the same way that much of the other stuff is in that folder.

Anyway, please confirm whether this fixes the problem for you.

**Comment by felipejfc** [comment]
omg this should be documented somewhere! just hit this problem and thanks god there was an issue with this info

**Comment by mihe** [comment]
For what it's worth this limitation of needing the `extension_list.cfg` has been removed from Godot as of godotengine/godot#93972 (i.e. Godot 4.4).
