### ISSUE TITLE
After extraction of the zip into my project I am not seeing the plugin, nor as a 3d option in General. 

### ISSUE THREAD

**Issue by glassoctopus** [godot-jolt/godot-jolt#721]
Hello, 
I am having trouble installing the plugin. 

Running:
Description:	Pop!_OS 22.04 LTS
Release:	22.04
&
ldd (Ubuntu GLIBC 2.35-0ubuntu3.5) 2.35

So I meet those requirements, but after extracting the download from: https://godotengine.org/asset-library/asset/1918
extracting to:

.var/app/org.godotengine.GodotSharp/data/godot/app_userdata/Test3Dproject/addons

Close and reopened Godot, and I did not see the 3d option in general or as a plugin. 
Did some investigation, and added a addon.cfg script in:

.var/app/org.godotengine.GodotSharp/data/godot/app_userdata/Test3Dproject/addons/godot-jolt

```
[plugin]
name="Jolt Physics"
script="res://addons/jolt_physics/jolt_physics.gd"
```

Also to no avail.  Any ideas on what I am missing?

Thank you, in advanced.

**Comment by mihe** [comment]
> /var/app/org.godotengine.GodotSharp/data/godot/app_userdata

I'm not sure what prompted you to use this path, but this directory is the per-project "user data" for Godot, which houses various transient files like caches and whatever else, hence why it's under `/var`. It's not meant to be used for general storage.

You need to extract the `addons` folder next to (or below) your `project.godot` file, in your actual project directory.

You can also install it directly through Godot itself, using the button labeled "AssetLib" found at the top of the Godot editor once you've loaded a project.

The `addons.cfg` file is (confusingly) only meant for script add-ons, which are different from native extensions, so that file has no effect.

**Comment by glassoctopus** [comment]
I really appreciate this quick response. Apologies for you needing to break out the crayons, but I am grateful for it. 
The AssetLib method was the flawless way to execute this!
I am really struggling with what you are meaning by `project.godot` file. 
I have been searching and trying to find a good resource to understand this, reading through this:
https://docs.godotengine.org/en/stable/tutorials/best_practices/project_organization.html
I thought my path: .var/app/org.godotengine.GodotSharp/data/godot/app_userdata/Test3Dproject
was to this specifically, but i hear you when you say it's 'directory is the per-project '
i made a new path from my user file: ~/Godot/3D/ and created a new test project, if i un-hide hidden files there is the project.godot... but i don't see my project in this folder... so I am trying to understand the difference. Going to reread the docs and keep researching. Thank you, thank you for taking time out, and I got this installed successfully, and set it as the 3d engine in Project>general>physics>3D settings. 

~new to the linux, new to Godot, and ready to struggle through it. I really appreciate your time and help and look forward to seeing your physics incorporated into the engine. Everything  I have watched on this shows that it's a great asset and will only get better.
