### ISSUE TITLE
Show version somewhere in the editor

### ISSUE THREAD

**Issue by oninoshiko** [godot-jolt/godot-jolt#751]
While this may seem silly, (and, really, is a defect in the gdextensions / assetlib), I think there needs to be somewhere we can see the version of godot-jolt we are running. Until some way is added in godot itself, I think it would be a good idea to just put a "version" label in the "project settings > physics > Jolt 3D" screen.

**Comment by mihe** [comment]
As much as I would love for there to be a version number prominently displayed somewhere, I don't (as far as I know) really have any way of adding a regular label to the project settings screen, since it's all populated with the help of the `ProjectSettings` class.

For a while I was debating for over whether I should just emit the version into the editor log, much like Godot itself does, but decided it felt a bit too obnoxious/intrusive.

There are of course other cheeky ways of doing it, like adding another tool (under `Project > Tools > Jolt Physics`) that does nothing but display a popup with the version number or something, but realistically nobody is going to go look for a version number there.

I'm open to ideas.

**Comment by oninoshiko** [comment]
Unfortunately, the cheeky way and just putting it in the editor log were the two things that came to mind for me. Ultimately, I think this is a really a problem on Godot's side, and they need to implement better management of assets installed from the AssetLib tab.

Beyond the editor, even exposing it as a variable I can access somehow would be helpful.

**Comment by Gizrah** [comment]
Since Jolt is a conscious choice and a major impact in the way your game is handled and playing, I'm honestly not that adverse to the idea of logging the version in the console on startup.

I'd even go a step further, adding a checkbox setting for checking for version updates every day or week, and showing an update notice in the log as well, similar to the startup notice that running on a separate thread is ignored.

**Comment by NuclearPhoenixx** [comment]
How about having a singleton approach just like `Engine.get_version_info()`? I've seen this approach with custom modules and I think it makes sense without any of the trouble of manipulating the project settings. You could do whatever you want with that info and print it to the debug console when running your game or something.

**Comment by Karagra** [comment]
Is something like this not possible?
![image](https://github.com/user-attachments/assets/e70f7676-5f36-4883-a256-9ccac5d62e61)

**Comment by mihe** [comment]
> Is something like this not possible?

@Karagra Not without breaking everyone's projects when they go to update Godot Jolt. That name is the actual identifier for the registered physics server, as opposed to just a display string.

I realize I haven't actually mentioned this anywhere in this thread, but keep in mind that the version number is available through the actual binaries on all operating systems as well. On Windows you can just right-click any of the DLLs, click "Properties" and then "Details", and there you have it. On macOS you would right-click the `*.framework` bundles instead, and then click "Get Info".

Linux is a bit trickier, since there's nothing standardized like this, but (mostly as a tool for myself) I've embedded a bunch of strings into the binaries that start with `@FileInfo_`, which you can find by `grep`ing the output from the `strings` command.

> How about having a singleton approach just like `Engine.get_version_info()`?

While this is certainly possible, you'd only be able to use it through GDScript (or other dynamic languages) since classes exposed by extensions aren't generally available through more static languages like C#, C++, Rust, Swift, etc. without doing something more involved, like `Engine.get_singleton("JoltPhysicsServer3D").call("get_version_info")` and then cast that to a string.

I should probably add it anyway though, just to give people some kind of runtime option.

**Comment by mihe** [comment]
I realize #979 doesn't technically satisfy this request, but someone suggested to just stick the version in the `*.gdextension` file, and that (much to my surprise) works just fine, so I'll leave it at that.
