### ISSUE TITLE
Axis-locked bodies connected to joints can sometimes go crazy

### ISSUE THREAD

**Issue by yosimba2000** [godot-jolt/godot-jolt#757]
Using Godot 4.2.1 .Net w/ Godot Jolt 12.0

I have a door created with a JoltHingeJoint3D, where the Joint is rotated 90 degrees around its X-axis so that the Joint allows the attached Rigidbody to rotate around the Y-axis.

A Skeleton3D with bone colliders moves towards the door in _Process().

There is a Door Rigidbody3D as the Joint's A-Node, and a StaticBody3D as the Joint's B-Node.
When the Skeleton3D encounters the Rigidbody3D, the Rigidbody3D jitters around and rotates around multiple axes, not just the Y-axis.

Issue does not resolve when axis-locking the Rigidbody3D (it actually makes it worse), nor when moving the Skeleton under _PhysicsProcess() instead.
Issue also does not resolve when switching the Rigidbody3D to the Joint's B-Node, and the StaticBody3D to the Joint's A-Node.

MRP here: https://filebin.net/h6qq6inzay9qi1my
1) Just run the project, and wait for the Skeleton3D to go thru the door, and observe the door jitter.

**Comment by mihe** [comment]
> When the Skeleton3D encounters the Rigidbody3D, the Rigidbody3D jitters around and rotates around multiple axes, not just the Y-axis.

It seems to me like this exact thing happens with Godot Physics as well.

Since you're not actually running the rigid body simulation of the bones (using `Skeleton3D.PhysicalBonesStartSimulation()`) your skeleton is effectively a kinematic body (like a `CharacterBody3D` or an `AnimatableBody3D`) which will have infinite mass/inertia and will go through anything and everything in its path. So when the skeleton's arm intersects with the door's `RigidBody3D` in that manner, then the door won't really have a choice but to violate the constraint of the hinge joint in order to solve for the collision.

> Issue does not resolve when axis-locking the Rigidbody3D

Combining axis-locking with joints is not something that works all that well with Jolt, from what I've seen. Axis-locking isn't implemented in quite the same way as in Godot Physics though. You can kinda make this work in Godot Physics (see [this](https://github.com/godot-jolt/godot-jolt/files/14064979/Locked_HingeJoint.zip) project), but you need to set a custom center-of-mass for the body and have it be right on the hinge axis, and then lock every axis but "Angular Y". It will still jitter somewhat though. With Jolt this will seemingly cause the joint to freak out at the slighest impulse.

(Should this be considered a bug @jrouwe? I'm assuming it just is what it is.)

I'm honestly not sure how you would best solve this with the tools available in Godot. Ideally you would have something like [powered ragdolls](https://youtu.be/lYHhe6HLbs4), since they can actually have some "give" to them, but that's not something I've exposed, and I'm not sure how you'd go about implementing that with Godot's `Skeleton3D`, or if it's even possible to retrofit in the first place.

Maybe the simpler solution is to just not have your skeleton be the thing that's collidable, and instead rely on something like a `CharacterBody3D` and `move_and_slide` (or the character controller of your choice) for the actual kinematic movement, which can be set up to actually stop when encountering the door frame. Then if you need some sort of ragdoll behavior you would just disable the collision for the `CharacterBody3D`, enable the collision for the skeleton and start its rigid body simulation using the method mentioned earlier.

**Comment by jrouwe** [comment]
> Should this be considered a bug @jrouwe? I'm assuming it just is what it is.

This sounds like a bug indeed. The Locked_HingeJoint project that you added doesn't seem to do anything for me (I added the godot-jolt addon and enabled it) so I'm not really sure what I'm looking at. If you have a repro (e.g. in the Samples app) for me then I can take a look.

Jorrit.

**Comment by mihe** [comment]
> This sounds like a bug indeed. The Locked_HingeJoint project that you added doesn't seem to do anything for me (I added the godot-jolt addon and enabled it) so I'm not really sure what I'm looking at. If you have a repro (e.g. in the Samples app) for me then I can take a look.

I forgot to mention that it's a .NET project, like the original repro project, which might be why nothing is happening for you, since it needs the .NET version of Godot to run. It really didn't have to be though, so I went ahead and converted it to a GDScript project instead: [Locked_HingeJoint_GDScript.zip](https://github.com/godot-jolt/godot-jolt/files/14066536/Locked_HingeJoint_GDScript.zip)

I'll go ahead and make a Samples repro either way, if only just to have an official issue for it.

(Note that if you run the repro in `EditorDebug` you'll likely get a ton of asserts about invalid scales, as the matrices for `PhysicalBone3D` are ever so slightly non-uniform, which is a known issue in Godot.)

**Comment by mihe** [comment]
I'm taking some liberties and reframing the issue here to specifically be about using axis-locking on bodies connected to joints, as mentioned in the original issue description:

> Issue does not resolve when axis-locking the Rigidbody3D (it actually makes it worse)

This has now been fixed as of #783 thanks to @jrouwe making some changes to how axis-locking works in Jolt.
