### ISSUE TITLE
`SeparationRayShape3D` collides when enveloped by convex shapes

### ISSUE THREAD

**Issue by reliAttic-Games** [godot-jolt/godot-jolt#759]
Hey,

so I activated Jolt physics in Godot and it seems, that the separation ray shape is a bit too sensitive.

I set up a top down scenario, so movement is locked to xz movement at the moment. When approaching a wall the separion ray shape "separates" the character even though the wall is way higher than the ray. However, when switching back to the Godot physics engine, everything works normally, so I guess it's some kind of bug or setting error, am I right?

Here you can see, how the separation ray setup works with standard physics:
https://github.com/godot-jolt/godot-jolt/assets/157819867/c3975db7-a1df-4604-b4f9-e823eb13d908

Here with Jolt:
https://github.com/godot-jolt/godot-jolt/assets/157819867/3adfd4ab-76d5-4f4c-9b1d-b4916a704a01

And this is the setup:
![SeparationRaySetup](https://github.com/godot-jolt/godot-jolt/assets/157819867/28d6af35-f1ff-465a-9a8f-19e0da7c5f6e)

I added a cylinder mesh to the separation ray in order to visualize the length and position of the ray.

Hope this helps. I'm happy to share more information and test cases if needed.

**Comment by mihe** [comment]
Interesting. I'm guessing this is going to be this decision coming back to bite me:

https://github.com/godot-jolt/godot-jolt/blob/cafbe8f93b800d0f4c929c334fb0c628ea0f6899/src/shapes/jolt_custom_ray_shape.cpp#L73-L77

It should be a simple fix if that's the case.

I'll see if I can reproduce it on my end.

**Comment by reliAttic-Games** [comment]
Hey, first of all thanks for all your replies and for investigating the problem so quickly. Really appreciate your work!

Yeah, totally makes sense. Sounds reasonable to treat the ray shape as convex shape. I tried it on my end with your first suggested solution (so positioning the ray shape directly at the capsule edge) and it seems to work. So thanks for bringing that up. There's no real reason for the offset except to detect the actual step before hitting it, which (at least in theory) gave a nicer transition to the actual step handling. But it seems, that without the offset it works quite nicely.

Maybe it might be a good idea to place a comment somewhere, that explains, why the ray shape was implemented the way you've done it? Just to prevent further confustion in the future.

**Comment by mihe** [comment]
> Maybe it might be a good idea to place a comment somewhere, that explains, why the ray shape was implemented the way you've done it? Just to prevent further confustion in the future.

I must admit I never expected anyone to actually run up against this discrepancy, which is why I didn't document it, but I guess given enough people using the extension eventually every stone will be turned over by somebody.

There are a couple of other very minor/niche/specific differences between Jolt and Godot that I chose not to document in order to not make the list of differences too overwhelming, but yeah, maybe this one warrants being added to it after all.

I'll stew on it for a little bit. It might be better to just align with how Godot Physics does it, just for the sake of not having to document the discrepancy.

**Comment by mihe** [comment]
I went ahead and made the change without any setting. It'll probably be fine. I can't imagine anyone is actually depending on the current behavior anyway.

It might be a little while before I cut a release with this change in it though.

**Comment by mihe** [comment]
"A little while" turned into 5 months somehow, but the fix for this can now be found in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).

Note that this version targets the just recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.

A proper release will be out some time around Godot 4.3-stable.

**Comment by mihe** [comment]
I figured I'd give a minor update here, as [0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, so if you've been relying on 0.13.0-beta1 for this functionality until now I would highly recommend updating, as this most recent release includes some important bug fixes.

Note that the release on the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
