### ISSUE TITLE
Thread pool is not configurable

### ISSUE THREAD

**Issue by Zylann** [godot-jolt/godot-jolt#76]
https://github.com/godot-jolt/godot-jolt/blob/de0fa3de7af352282812ad6f808a8c29b77e4830/src/jolt_physics_server_3d.cpp#L77

I'm wondering if this needs to be changed in case the game already uses several threads for doing other stuff in parallel to physics. If this uses almost all hardware threads, could there be contention leading to performance issues?

In my case I also run a voxel engine, which typically runs jobs that can be pretty packed and long, sometimes overlapping multiple frames. It's a job system that doesn't need to complete all its jobs every frame like Jolt does.
I made my job system use only half of the available threads for this reason, but I wonder what that means for Jolt's job system. It is said in the docs that you could integrate your own job system in Jolt, but mine isn't really designed the same due to the absence of low-latency per-frame requirement.

**Comment by Zylann** [comment]
If it limits *the amount of jobs*, it wont limit how many threads will run them at once.

**Comment by Zylann** [comment]
Limiting the amount of jobs can be problematic because it really isnt the same thing as the number of threads. There could be an order of magnitude more jobs to process than a number of threads available, so it could be quite limiting.
Godot has the same problem when it comes to thread count here... I guess it has to be brought up in the API too?

> I'm not sure I follow. What kinds of problems are you referring to?

If you look at the place I linked in Godot's Thread implementation, you will see that it setups a number of things in addition to run the thread's function. This is missing from the implementation in GodotCpp, and will be missing if you use thirdparty threads or vanilla `std::thread`. That means Godot will not be aware of that thread and some things might not work. One of which, from what I read, would be related to scripts debugging.

**Comment by Zylann** [comment]
> So it looks like Jolt expects to run one job per core essentially.

IMO the best solution remains to simply set the desired number of threads, limiting job count doesnt make sense to me and could harm performance.

**Comment by mihe** [comment]
A lot has happened since this discussion. I've since replaced Jolt's `JPH::JobSystemThreadPool` with [my own](https://github.com/godot-jolt/godot-jolt/blob/master/src/spaces/jolt_job_system.cpp) job system using Godot's `WorkerThreadPool`. Performance seems to be roughly in the same ballpark, so in the interest of keeping things simple for the initial release I will let this be the only job system implementation for now.

The amount of threads in `WorkerThreadPool`, which applies to all of Godot (but [not the editor](https://github.com/godotengine/godot/blob/d6dde819be6e02de133fe1b9f97c8fa6ce8668bb/core/register_core_types.cpp#L305-L313)), can be configured using the project setting `threading/worker_pool/max_threads`.
