### ISSUE TITLE
`move_and_slide` can apply impulses to `RigidBody3D`

### ISSUE THREAD

**Issue by Garbg** [godot-jolt/godot-jolt#761]
Pretty self explanitory. If the player's collision shape is a capsule and you walk backwards onto the edge of a rigidbody cube you and the cube go flying.
Steps to replicate:
* Have a player with a collision object of capsule
* Have a cube
* Jump on top of the cube and walk backwards
* Go flying
[Screencast from 2024-01-27 18-17-55.webm](https://github.com/godot-jolt/godot-jolt/assets/83542885/0593c454-493e-4e72-8f92-96297b270ede)

**Comment by mihe** [comment]
This is technically more of an issue with the part of `move_and_slide` that's on the Godot side of things, and is something that happens with Godot Physics as well, although the effect is harder to reproduce there.

Here's an example, when running with Godot Physics:

https://github.com/godot-jolt/godot-jolt/assets/4884246/2c0d54a5-6888-4474-9c1a-5cb1de160040

The default collision layer/mask setup of having everything on layer 1 doesn't really make a whole lot of sense for `move_and_slide` in my opinion. The fix is to put your character on a dedicated collision layer and remove that layer from the mask of the rigid bodies, so that you end up with an asymmetric/one-way collision setup. That way the rigid bodies won't be affected by the character but the character will still collide with the rigid bodies.
