### ISSUE TITLE
Unhandled override mode error

### ISSUE THREAD

**Issue by AlexandrDzyuba** [godot-jolt/godot-jolt#773]
![Screenshot_16](https://github.com/godot-jolt/godot-jolt/assets/64035114/c4f61696-1752-4815-984c-d37d6573d7fb)
Hey everyone,

I've encountered a persistent issue while working with the Godot-Jolt physics engine integration on GitHub. The error message I'm facing seems to be quite elusive and keeps popping up incessantly:
E 0:06:14:0448   integrate: Unhandled override mode: '2036625250'
  <C++ Error>    Method/function failed. Returning: {}
  <C++ Source>   src\objects\jolt_body_impl_3d.cpp:36 @ integrate()
It appears that this error is related to an unhandled override mode within the physics engine, specifically within the jolt_body_impl_3d.cpp file.

Has anyone else encountered this error before, and if so, were you able to resolve it? I've searched extensively for solutions but haven't found anything conclusive yet.

Any insights, suggestions, or guidance on how to tackle this issue would be immensely appreciated. I'm eager to get past this roadblock and continue making progress with my project.

Thank you in advance for your help!

**Comment by mihe** [comment]
Since there is no override mode with the value `2036625250`, and they only go up to `4`, something has likely corrupted the stack, or some stale pointer is being accessed. Frankly, I'm a bit surprised that you're only seeing this error message. Things like this typically cause a crash somewhere. The question is whether it's a bug somewhere in the extension or if it's somewhere else. In any case, it's highly unlikely that this will be diagnosed without some type of repro.

What version of Godot are you using, and what version of Godot Jolt?

**Comment by AlexandrDzyuba** [comment]
I use the latest versions of Godot and Jolt physics, but propably I found the reason of that error.
I had a 2 sub viewports, both with flag "own world", and in both viewports I had some count of CharacterBody3D. After a +- minute of play with that configuration, debugger starts print that error. But when i replace second sub viewport type to Node3D, error was disappear.

**Comment by mihe** [comment]
Would you be able to reduce that project down to something minimal that I can run to reproduce it on my end? Having multiple physics spaces/worlds is definitely something I don't test very often.

**Comment by AlexandrDzyuba** [comment]
I can try create another project for reproduce that, but little later

**Comment by mihe** [comment]
For what it's worth I've had this bug reported by someone else as well, who was not using multiple spaces/worlds, so it doesn't seem to be strictly related to that.

Sadly they were unable to provide a solid repro.

**Comment by mihe** [comment]
Seeing as how there's no repro for this one yet I don't have much choice but to close this as "cannot reproduce".

If anyone reading this happens to have a solid repro for this, please leave a comment (and ideally upload a repro project as well) and I'll reopen this.

**Comment by SoapSpangledGames** [comment]
Not that this helps, but I also get this error withing Godot 4.2. The override numbers differ from run to run, but my latest run alternates between 6 and -1. My game is rather large, so I haven't tried creating a minimal project  (hence why I'm sure this doesn't help).

**Comment by mihe** [comment]
@SoapSpangledGames Any sort of context you can provide might help. When does it happen, and how often?

Also, are you using any sort of physics stuff in a multi-threaded fashion, whether that's resource loading or ray-casting or whatever?

**Comment by SoapSpangledGames** [comment]
I don't explicitly use physics in threads  (unless Godot does it behind the scenes). I only explicitly use threads for loading and instantiating objects to construct map scenes. Though I'm not yet 100% certain, I THINK it happens when I free all the objects in my map while switching levels (though that's not the only time). I don't have anything concrete to offer yet.

I just started noticing it today, so I don't have much to go on.

**Comment by mihe** [comment]
It's likely that this bug has something to do with physics bodies hanging on to stale references of `Area3D`, in case that helps narrow down a repro for anyone here.

**Comment by mihe** [comment]
> Though I'm not yet 100% certain, I THINK it happens when I free all the objects in my map while switching levels (though that's not the only time).

@SoapSpangledGames I take it that the error is not consistent then?

**Comment by SoapSpangledGames** [comment]
No, it isn't consistent. To add an additional layer of complexity, it's a multiplayer game and I haven't been able to cause the error with only a single player active.

**Comment by SoapSpangledGames** [comment]
It is happening while I am loading and instantiating my models in a Godot background thread.

**Comment by SoapSpangledGames** [comment]
More accurately, I am loading my game classes which contain the models, collision shapes, scripts, etc.

**Comment by mihe** [comment]
I'm assuming you're doing this using `ResourceLoader.load_threaded_request`? Are you also using `use_sub_threads = true` by any chance?

**Comment by SoapSpangledGames** [comment]
My game launches and connects to the default server. The server starts sending the map specification, causing all the objects in the client's local map to be cleared and all objects to be freed. Since this is the first connection, the map is already empty so nothing is removed/deleted/freed.

I then enter an object which causes me to leave the server and connect to a different one. This causes all the objects in the client's local map to be cleared, and all objects to be removed/deleted/freed before the client drops the connection and connects to the new server. Everything is fine at this point.

The new map has an object that causes me to leave the server and connect to another one (it doesn't matter which one, but it happens to be the original server). During loading the objects, I start getting the errors. Sometimes it's a couple dozen, and sometimes it's tens of thousands.

**Comment by SoapSpangledGames** [comment]
> I'm assuming you're doing this using `ResourceLoader.load_threaded_request`? Are you also passing `use_sub_threads = true` to it by any chance?

I am using ResourceLoader.load_threaded_request, but I am not I'm using the default use_sub_threads = false.

**Comment by SoapSpangledGames** [comment]
I meant to type I am using the default.

**Comment by SoapSpangledGames** [comment]
```func _ready():
	m_nError = ResourceLoader.load_threaded_request(m_stPath)
	if m_nError != OK:
		print("Can't start the threaded load.")```

**Comment by mihe** [comment]
You mentioned earlier that:

> I only explicitly use threads for loading and instantiating objects to construct map scenes.

Does that mean you're using your own threads to do the instantiating part of it?

**Comment by SoapSpangledGames** [comment]
I do the instantiation when the resource load finishes:

```
func _process(delta):
	if !m_bDone:
		m_nError = ResourceLoader.load_threaded_get_status(m_stPath)
		match m_nError:
			ResourceLoader.THREAD_LOAD_INVALID_RESOURCE:
				fatalError.emit(self)
				queue_free()
			ResourceLoader.THREAD_LOAD_IN_PROGRESS:
				pass
			ResourceLoader.THREAD_LOAD_FAILED:
				fatalError.emit(self)
				queue_free()
			ResourceLoader.THREAD_LOAD_LOADED:
				var scene = ResourceLoader.load_threaded_get(m_stPath).instantiate()
				
				m_bDone = true
				loaded.emit(self,scene)
				queue_free()
			_:
				fatalError.emit(self)
				queue_free()
```

**Comment by mihe** [comment]
Hm. I feel like that should be fine. No part of the extension is thread-safe is at the moment, but I don't believe that *loading* a scene on another thread will actually call into the physics server. It's only once you instantiate stuff concurrently that you ought to run into problems.

I'll need to double-check that.

In the meantime, do you have the ability to do everything on the main thread, just to rule out the threaded resource loading?

**Comment by SoapSpangledGames** [comment]
Yes, it shouldn't take long.

**Comment by SoapSpangledGames** [comment]
I replaced the threaded loading with a non-threaded loading, and I got the same results.

**Comment by SoapSpangledGames** [comment]
I made a mistake, so I'll get back to you in a few minutes.

**Comment by SoapSpangledGames** [comment]
I fixed the mistake, and it didn't change the outcome. I'm still getting the errors.

**Comment by SoapSpangledGames** [comment]
This is the single-threaded code:

```
func _process(delta):
	var scene = ResourceLoader.load(m_stPath).instantiate()

	loaded.emit(self,scene)
	queue_free()

Since this is blocking code, I didn't bother with ensuring the load happens only once.

**Comment by mihe** [comment]
> I fixed the mistake, and it didn't change the outcome. I'm still getting the errors.

Alright. I guess that rules out that part. Thanks for checking.

Do the scenes being loaded have any `Area3D` in them?

**Comment by SoapSpangledGames** [comment]
Some of them have ```Area3D```. Unfortunately, I have other stuff to do for at least a couple hours. When I get back, I will test that.

**Comment by SoapSpangledGames** [comment]
I have two maps: one with at least one ```Area3D```, and one with no ```Area3D```. I first connect to the server that hosts the map with the ```Area3D```, and it loads with no errors.

I then connect to the server the hosts the map with no ```Area3D```. Part of the client's process is to destroy all objects in its map before making the connection to the new server. It's at this point that I start seeing the errors.

**Comment by mihe** [comment]
What happens if you remove all `Area3D` from both maps?

**Comment by SoapSpangledGames** [comment]
My game was not designed to do that, so it will take some time to implement.

**Comment by mihe** [comment]
Alright, don't worry about it. Thank you for testing.

It sounds like destroying all the objects in the map with an `Area3D` in it is what's causing trouble, which would make sense given that the error likely has something to do with a physics body internally hanging on to an `Area3D` reference that has gone away.

I'll see if I can recreate that on my end somehow.

**Comment by SoapSpangledGames** [comment]
It's done, and I didn't get any errors. I started with the map that has no ```Area3d```, and forced a map switch back to the same map.

**Comment by mihe** [comment]
Cool, thank you for confirming that.

Is there anything special about the way you destroy all the objects in the map, or is it just doing a `queue_free()` of some root node?

**Comment by SoapSpangledGames** [comment]
Nothing particularly special. I have several arrays of references to nodes, and I just iterate over all the arrays and ```queue_free()``` each node in each array. Then I clear the arrays:

```
func clear():
	freeAllSceneItems(m_aSceneItems)
	freeAll(m_aSpawnPoints)
	freeAll(m_aSpawners)
	freeAll(m_aTriggers)
	freeAll(m_aPlayerTurnWheelNotShootTrigger)
	freeAll(m_aThreeTextureItem)
	
func freeAllSceneItems(aItems):
	for item in aItems:
		item[1].queue_free()
	aItems.clear()

func freeAll(aItems):
	for item in aItems:
		item.queue_free()
	aItems.clear()
```

**Comment by mihe** [comment]
I've tried reproducing this now, by freeing bodies/areas in all sorts of ways and orders, both using `queue_free()` and `free()`, but I haven't managed to run into this error once yet.

Is there any possibility that I can run your actual game and try to debug this error through that instead, @SoapSpangledGames? If not, would you be able to reduce it down to something somewhat manageable that you'd feel comfortable sending to me?

**Comment by SoapSpangledGames** [comment]
I created a new small test project, and haven't been able to reproduce the error there. I also uninstalled and reinstalled Jolt on my main game project, but the errors persist there.

I am not comfortable with sending my entire game project, so I'll continue trying to pinpoint exactly what triggers the errors.

**Comment by mihe** [comment]
That's totally fair.

Let me know if you manage to narrow in on the problem in any way. I'm not sure what I can do from my end at the moment.

**Comment by mihe** [comment]
@SoapSpangledGames Would you perhaps have the ability to upgrade your game to the recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/) by any chance? I'm currently in the process of packaging a beta build of my own that will be compatible with Godot 4.3-beta1 (which the current release isn't) and it would be interesting to see if this problem has fixed itself somehow, since there's been quite a few changes since the last release (on both sides).

**Comment by SoapSpangledGames** [comment]
I will give that a try, but it will be a few days (maybe next weekend) before I will have time to do so.

**Comment by mihe** [comment]
Sounds good. You can find the version of Godot Jolt meant for Godot 4.3-beta1 [here](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-beta1).

**Comment by mihe** [comment]
I've had it reported through other channels that this issue is seemingly not reproducible in Godot 4.3-beta2 when using Godot Jolt 0.13.0-beta1.

If anyone in this thread could confirm that as well I'd appreciate it.

**Comment by TheoJao** [comment]
I'm getting this same error only when using Jolt, it works fine with the default physics engine.

I have a player that can go to another location when pressing a button on a map, in this process I reparent the player to an autoloaded global Node3D scene (so I don't have to instance and load the player again), and then reparent it again to the new location once it has been loaded. I get spammed with thousands of errors while the scene is being loaded, and it stops when the player is reparented to the location node (although sometimes it continues spamming errors even when the player is reparented to the loaded location).

I'm using Godot 4.3beta2 and Jolt 0.13.0-beta1

![image](https://github.com/godot-jolt/godot-jolt/assets/102422180/efcad674-acf5-47be-b02d-2d9f9658bb63)

**Comment by mihe** [comment]
@TheoJao I can't fix this without a somewhat consistent repro, and so far I have yet to see this error once on my own machine, so I would kindly ask that you either try to reproduce your issue in a new project and upload it here, or you try to reduce your existing project to something you're comfortable uploading.

The issue is likely related to `Area3D` in some way, if that helps narrow things down.

**Comment by MJBrune** [comment]
I've found myself here because of the same error but I can reliably repro mine. So what I am doing is transferring a Node between scene changes by holding on to it via a reference in a singleton and reattaching it to a new node.

I do this:
`player.get_parent().remove_child(player)`
just before I call `get_tree().change_scene_to_file(new_scene)`
then I call `get_tree().root.add_child(player)`
Player of course has some CollisionShapes on it. So I feel like in my case the solution might be:

1. Reinitialize the player collision shapes with the new physics scene (ideal)
2. Spawn new collision shapes and destroy the old ones in this process. (probably by just actually serializing the data I need to transfer instead of transferring the whole player node, I'm just trying to be lazy here)

Is there any way to do 1?

**Comment by mihe** [comment]
@MJBrune What you're describing should work perfectly fine, and seems to work perfectly fine without any errors when I try it for myself. Neither of your proposed solutions should be necessary, and I can't imagine they'd have any impact on this particular problem.

Again, this issue is almost certainly related to `Area3D` in some way, as the error being emitted likely indicates that a `RigidBody3D` or `CharacterBody3D` is (internally) holding on to a reference of an `Area3D` that has already been deleted. This shouldn't be possible, but is clearly happening somehow, which is why I really would like someone to upload a repro project of some sort, so I can get to the bottom of where it's coming from and actually fix it.

Could you try to reproduce your issue in a new minimal project and upload it here, or reduce your current project down to something you'd be comfortable uploading? It doesn't even need to be reduced necessarily, if you're comfortable just sending the project as-is, I just need something I can actually run in a native debugger.

If neither of those options are viable I could even accept an exported build of your project (ideally a Debug export), which I could run with the debug version of Godot Jolt on my end and debug things that way. That would make things a bit more cumbersome to debug though.

**Comment by MJBrune** [comment]
Hmm, I think the biggest use of area3D in my project is my AI which would be hard to reduce to a decent size. That said I want this issue to be easy to debug for you. I can get you a copy of my current source code, do you have an email address I can send a Google Drive link to?

**Comment by mihe** [comment]
@MJBrune You'll find my email in [my profile](https://github.com/mihe).

**Comment by MJBrune** [comment]
Awesome, sent an email. Sorry in advanced for the state of my project.

**Comment by mihe** [comment]
Yay! That does seem to reproduce it.

![image](https://github.com/user-attachments/assets/9e4a3bfe-dcd8-49a9-ba5c-7bf0d7de0fc2)

I'll dive right into it and try to fix this once and for all. Much appreciated!

**Comment by mihe** [comment]
Alright, so reducing that project down to something more manageable took me a while, but for posterity's sake here's the result of that: [area-use-after-free.zip](https://github.com/user-attachments/files/16227911/area-use-after-free.zip)

(Note that this repro won't emit an error every time, since it's accessing random memory, so to guarantee a crash you'll need to run it through something like Application Verifier on Windows, or Valgrind on Linux.)

The problem ended up being quite straight-forward, and a dumb oversight on my part (as expected) but at least now I know I have fixed the right thing.

@MJBrune You ended up being correct about this being related to your reuse of the player node inbetween scene changes. What you were doing should of course work just fine, but that is what prompts the bug in this extension, unfortunately. If you need a workaround in the meantime, it should be doable in your specific case by doing something like this:

1. Store the `collision_layer` property of the physics body (i.e. the player).
2. Set the `collision_layer` of the physics body to `0`.
3. Do `await get_tree().physics_frame` _twice_.
4. Remove the physics body from the tree.
5. Restore the `collision_layer` property of the physics body
6. Do the scene change.
7. Add the physics body back into the tree.

Basically you need to "hide" the `PhysicsBody3D` from any `Area3D` that's currently overlapping it, and then wait for all those areas to flush their relevant overlap events, and only once that's done can you go ahead and start messing with the scene tree.

It's not ideal, especially if you have many nodes that you want to reuse inbetween scene changes, but it's the best I can think of for now, until I've published a new release with the fix (#917) in it.

**Comment by mihe** [comment]
Oh, and thank you again for sharing your project @MJBrune. I've deleted all the copies of the project you sent me. Feel free to delete the Google Drive thing as well, I guess.

**Comment by mihe** [comment]
[0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, which includes the fix for this.

Note that the release in the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
