### ISSUE TITLE
Some area methods don't allow for space RIDs

### ISSUE THREAD

**Issue by Sievaxx** [godot-jolt/godot-jolt#777]
Certain world state features like the current global gravity vector are inaccessible, as trying to use `PhysicsServer3D.area_get_param(get_world_3d().get_space(), PhysicsServer3D.AREA_PARAM_GRAVITY_VECTOR)` does not work.
The space type that this plugin sets the World3D space to is not an "area" space, like it is in GodotPhysics.

![image](https://github.com/godot-jolt/godot-jolt/assets/21314708/1ad828c5-e85e-4542-8152-6ec138f032a9)
The first assert clears with default settings, showing that the world space does exist and has some parameters.
Both asserts clear in GodotPhysics with default settings.
The World3D space is intended to be accessible as an area space, as it is used as so in the [documentation. ](https://docs.godotengine.org/en/4.2/classes/class_projectsettings.html#class-projectsettings-property-physics-3d-default-gravity-vector)

**Comment by mihe** [comment]
Thank you for reporting this. I'm not sure how I overlooked `area_get_param` as I had already accommodated for the default area in `area_set_param`.

I see now that I missed `area_attach_object_instance_id` and `area_get_object_instance_id` as well.

I'll have it fixed shortly.

**Comment by mihe** [comment]
It might be a little while before a cut a release with this fix. I'd like to finish up some other stuff before that.

**Comment by mihe** [comment]
"A little while" turned into four months somehow, but the fix for this can now be found in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).

Note that this version targets the just recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.

A proper release will be out some time around Godot 4.3-stable.

**Comment by mihe** [comment]
I figured I'd give a minor update here, as [0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, so if you've been relying on 0.13.0-beta1 for this functionality until now I would highly recommend updating, as this most recent release includes some important bug fixes.

Note that the release on the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
