### ISSUE TITLE
Cylinder versus triangles yields over-exaggarated penetration depth

### ISSUE THREAD

**Issue by Awarets** [godot-jolt/godot-jolt#789]
### Tested versions

Reproducible in Godot v4.2.1.stable.mono.official [b09f793f5] with Godot-Jolt v0.12.0-stable

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon (TM) R9 390 Series (Advanced Micro Devices, Inc.; 27.20.20913.2000) - Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz (4 Threads)

### Issue description

When a CharacterBody3D with CylinderShape3D collides against particular triangles on a StaticBody3D with ConcavePolygonShape3D, the collision results after invoking MoveAndSlide() and GetSlideCollision() are sometimes extremely incorrect.

The reproduction project includes an example of a CharacterBody3D on the edge of a StaticBody3D, moving only very slightly into it, which causes an extreme shift (The collision has a depth of .398, despite the cylinder only having a radius of .25. This becomes significantly more problematic if collision response is used to control character velocity)

![image](https://github.com/godot-jolt/godot-jolt/assets/8617121/4e3b9e11-a026-497b-92b2-a885c1969183)

### Steps to reproduce

Run the example project. The CharacterBody3D is moving into the StaticBody3D at a very low speed, but the collision depth+normal pushes it extremely far to the left, as displayed through the console logs.

### Minimal reproduction project (MRP)

[CollisionDepthIssue_jolt.zip](https://github.com/godot-jolt/godot-jolt/files/14321220/CollisionDepthIssue_jolt.zip) (with Godot-jolt v0.12.0-stable, which I could not include due to filesize limit)

**Comment by Awarets** [comment]
Could be related to very similar issue in base Godot Physics godotengine/godot#88476, but it is not reproducible under the exact same conditions,

**Comment by mihe** [comment]
First of all, thank you for the detailed issue report and for the very minimal repro project. I've become used to people dumping half their character controller in my lap, so this was refreshing to see.

This looks to be an unfortunate side effect of the binary search that Godot sort of forces upon the `PhysicsServer3D.test_body_motion` method, which is implemented in the physics server (this extension included) and is what powers `move_and_slide`.

The algorithm goes something like this:

1. Do a collision check with some padding (the "safe margin")
2. Iteratively move the body away from whatever collision was found by step 1
3. Shape-cast from this new position by the motion vector, using a binary search, without the safe margin
4. Do a collision check at the unsafe fraction reported by step 3, with the safe margin

In Godot this binary search is always done using a hardcoded number of steps (8), whereas in this extension I dynamically scale the number of steps by the movement/cast distance between 4 and 16.

In this case the number of steps ends up being 4, since the motion is fairly small, which leads the binary search to being somewhat "coarse" and output a safe fraction of 1.56% and an unsafe fraction of 6.25%, when in fact the collision happens at around ~3.82%, which means it overshoots quite a bit and thus reports an over-exaggarated penetration depth.

It might be a good idea to expose these min/max step counts as project settings, so that people who need more precision can adjust them accordingly.

I should maybe consider bumping up the minimum step count a tiny bit as well. Even just one more step (5) resolves this particular issue.

**Comment by mihe** [comment]
Although, now that I think about it, this difference of ~2.43% (6.25 - 3.82) would only really be a distance of about 0.0006. So it actually doesn't really explain this massively exaggarated penetration depth of about 0.398.

Still, upping the step count does fix the issue, but maybe it's just masking some quirk in the collision detection that happens at that exact spot.

It's not impossible that this has something to do with cylinders as well. They tend to be problematic.

I'll do some more digging.

**Comment by mihe** [comment]
Apologies for taking so long to get back to this.

This specific scenario turned out to be a bug within Jolt itself in the end, which was promptly fixed as soon as I reported it upstream.

The fix will be in the next release, which will likely be out around the time when Godot 4.3-beta1 is released.

**Comment by Awarets** [comment]
This is great news! Thank you so much.

**Comment by mihe** [comment]
With Godot 4.3-beta1 having just been released, the fix for this can now be found in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).

Again, note that this version targets the just recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.

A proper release will be out some time around Godot 4.3-stable.

**Comment by mihe** [comment]
I figured I'd give a minor update here, as [0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, so if you've been relying on 0.13.0-beta1 for this functionality until now I would highly recommend updating, as this most recent release includes some important bug fixes.

Note that the release on the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
