### ISSUE TITLE
Question regarding scale

### ISSUE THREAD

**Issue by huwpascoe** [godot-jolt/godot-jolt#796]
In the past when working with physics engines, simulating smaller scenes, I'd leave the world units as is and increase the gravity. So to simulate objects within 1cm sort of range, I'd set the gravity to 98.0ms^2 and that'd typically work. With godot-jolt, if I increase the gravity either by project settings or per body multiplier, it causes simulation to break: rigidbody can't come to a rest, vibrating in place or perpetually sinking through static colliders. Even with CCD and increasing iteration.

What's impressive is that if I reset the gravity to 9.8, then shrink all the bodies down to 1/10th of the scale, like 0.01m scale (beyond the documented [limitations](https://jrouwe.github.io/JoltPhysics/index.html#conventions-and-limits)) the simulation is a lot more stable!

What is correct here? Is there a bug with high gravity? Is it preferable to use tiny units for small scenes?

![image](https://github.com/godot-jolt/godot-jolt/assets/1812087/424e5b2d-da1b-41a9-9e13-5a44900e6a93)

**Comment by huwpascoe** [comment]
Yes with godot internal physics it seems to work.

Here's a MRP, it demonstrates falling through the floor. 
[ptest.zip](https://github.com/godot-jolt/godot-jolt/files/14444016/ptest.zip)

You can get a demo of the "vibrating" rigid bodies by adding a physics material to the floor cube with bounce = 0.2

**Comment by mihe** [comment]
> Yes with godot internal physics it seems to work.

I'm not seeing this particular scene working very well in Godot Physics either. Here's what it looks like for me:

https://github.com/godot-jolt/godot-jolt/assets/4884246/bf514ea1-7566-4d8c-9840-f98f5ac1d12f

Here's what it looks like with Jolt's default settings:

https://github.com/godot-jolt/godot-jolt/assets/4884246/699767c7-6c48-4a92-82f8-b27574f3f36b

It seems like the issue of sinking into the ground might be related (at least in part) to Jolt's Baumgarte stabilization, which from what I understand causes Jolt to deliberately not correct for the entire position error in a particular step (iteration?) in order to provide a more stable simulation, at the cost of artifacts like this. This setting (called "Position Correction" in Godot Jolt) is set to 20% by default.

If you crank up the "Position Correction" project setting to 100% you should get something that looks more like what Godot Physics puts out, in which case it looks like this instead:

https://github.com/godot-jolt/godot-jolt/assets/4884246/5e37dc75-b336-495a-9e3d-c8252f831a69

I'm not sure it's advisable to set it as high as 100% necessarily, but maybe you can experiment with higher values at least.

As for the constant vibration, I'm not sure what's causing that. I do know that thin/elongated shapes like this tend to produce quite wonky results in the physics engines that I've tried, even at normal gravity scales, but again, I'm not sure why exactly.

Maybe @jrouwe has some ideas as to what might be causing the vibration? The repro in `Samples` seems to be straight-forward:

```cpp
void SimpleTest::Initialize()
{
	CreateFloor();

	RefConst<Shape> shape = new CapsuleShape(1.0f, 0.1f);

	Body &body1 = *mBodyInterface->CreateBody(BodyCreationSettings(shape, RVec3(-5, 2, 0), Quat::sRotation(Vec3::sAxisX(), 0.25f * JPH_PI), EMotionType::Dynamic, Layers::MOVING));
	body1.GetMotionProperties()->SetGravityFactor(10.0f);
	mBodyInterface->AddBody(body1.GetID(), EActivation::Activate);

	Body &body2 = *mBodyInterface->CreateBody(BodyCreationSettings(shape, RVec3(0, 2, 0), Quat::sRotation(Vec3::sAxisX(), 0.1f * JPH_PI), EMotionType::Dynamic, Layers::MOVING));
	body2.GetMotionProperties()->SetGravityFactor(10.0f);
	mBodyInterface->AddBody(body2.GetID(), EActivation::Activate);

	Body &body3 = *mBodyInterface->CreateBody(BodyCreationSettings(shape, RVec3(5, 2, 0), Quat::sRotation(Vec3::sAxisX(), 0.75f * JPH_PI), EMotionType::Dynamic, Layers::MOVING));
	body3.GetMotionProperties()->SetGravityFactor(10.0f);
	mBodyInterface->AddBody(body3.GetID(), EActivation::Activate);

	PhysicsSettings settings = mPhysicsSystem->GetPhysicsSettings();
	settings.mBaumgarte = 1.0f;
	mPhysicsSystem->SetPhysicsSettings(settings);
}
```

**Comment by huwpascoe** [comment]
Thank you for such a detailed answer!

Whilst Godot internal has spooky movement, that kind of problem can be designed around one way or another. Same with the bouncing in jolt.

Clipping through floor however can't be worked around without ruining the game's flow so I'm happy there's a fix in the position correction setting.

**Comment by huwpascoe** [comment]
I found a setting that fixes all of the above: CCD with max_penetration turned all the way down.

Thanks again for the help.

**Comment by jrouwe** [comment]
The problem is that the acceleration is so high that in 1 frame it goes from having 1 contact point on one side:

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/f847c59c-1fae-4016-a060-c128a6f95a86)

to having 1 contact point on the other side (and pointing a bit upward to the left):

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/06957c56-b5e7-4a84-a0f7-cfc611e593b4)

Normally in this situation there should be a contact manifold consisting of 2 points, which ensures there is a stable contact:

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/911e8cfc-ff19-47b6-ace4-75f706b12e3c)

But because of the large distance traveled in 1 time step, it was pointing a little bit upwards to the left and it is just outside the tolerance and only reports 1 contact point. It then starts oscillating between the 2 points. The tolerance is currently hardcoded here:

https://github.com/jrouwe/JoltPhysics/blob/1f643028c4e4f85a0e1d0b3ef52c911db6496747/Jolt/Physics/PhysicsSettings.h#L19

Increasing that value makes the problem go away but potentially introduces issues at other gravity scales.

In general I wouldn't recommend cranking up the gravity this high.

**Comment by mihe** [comment]
Great, thank you for taking a look, @jrouwe.
