### ISSUE TITLE
Doesn't support 4.3 (dev builds) right now

### ISSUE THREAD

**Issue by catboy-catfish** [godot-jolt/godot-jolt#803]

**Comment by mihe** [comment]
I will likely be putting up a pre-release here on GitHub shortly after 4.3-beta1 is out.

**Comment by catboy-catfish** [comment]
Cool cool

**Comment by RisingThumb** [comment]
FYI, you can also hack around with the Godot source code and compile your own that says it's 4.2 instead, or compile your own godot-jolt(though unsure what changes you'd need here) if you need the godot jolt extension in the meantime for bleeding edge versions.

FWIW, and just to add on, I'm using v-sekai's group 4.3 branch https://github.com/V-Sekai/godot which is pretty close behind the master branch for godot minus a few commits, and haven't run into any issues coming myself using godot-jolt(with the additional version number change to 4.2 when compiling)

**Comment by mihe** [comment]
Just keep in mind that Godot releases can be binary incompatible in ways that are not immediately obvious.

I'm not aware of any such breakages in 4.3, but part of the reason for this version check was so that I wouldn't have to keep up with that stuff, so that doesn't mean much.

(The next version of Godot Jolt will utilize a new `compatibility_maximum` version that was added to the `*.gdextension` file format in Godot 4.3 to make this sort of opt-in a bit less painful.)
