### ISSUE TITLE
move_and_collide() behaves erratically on object with no collision layer

### ISSUE THREAD

**Issue by ghostsoft** [godot-jolt/godot-jolt#807]
[move_and_collide_bug.zip](https://github.com/godot-jolt/godot-jolt/files/14623308/move_and_collide_bug.zip)

To reproduce: left click mouse and drag around to move the **dragbody** object using move_and_collide(). Turning off the collision layer so the **dragbody** object has no influence on the **standingbody** (there is code for this in the _ready() function) will cause collision points to appear all over the scene and when released the object might get a huge boost of speed or result in _!v.is_finite is true_ errors. With the collision layer on, the **dragbody** body can influence and push the **standingbody** object and these errors no longer happen.

In default GodotPhysics3D neither of these things happen and the dragbody simply has no influence on the standingbody while frozen.

**Comment by mihe** [comment]
Apologies for the late triage, but it does seem like this has been fixed already, as part of updating Jolt itself in #800.

I'm guessing that it was probably jrouwe/JoltPhysics#949 that fixed it.

**Comment by mihe** [comment]
The fix for this can now be found in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).

Note that this version targets the just recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.

A proper release will be out some time around Godot 4.3-stable.

**Comment by mihe** [comment]
I figured I'd give a minor update here, as [0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, so if you've been relying on 0.13.0-beta1 for this functionality until now I would highly recommend updating, as this most recent release includes some important bug fixes.

Note that the release on the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
