### ISSUE TITLE
`linear_damp`/`angular_damp` produces inconsistent behavior between different `physics_ticks_per_second`

### ISSUE THREAD

**Issue by Jamsers** [godot-jolt/godot-jolt#827]
When using Godot Jolt, `linear_damp`/`angular_damp` produces inconsistent behavior between different `physics_ticks_per_second`, while with Godot Physics, behavior is still consistent.

`physics_ticks_per_second` 200:

https://github.com/godot-jolt/godot-jolt/assets/39361911/c5055532-cada-440d-9f36-b0d128300358

`physics_ticks_per_second` 60:

https://github.com/godot-jolt/godot-jolt/assets/39361911/eab8162f-4300-4b8e-bfd5-f7016e708e53

`physics_ticks_per_second` 30:

https://github.com/godot-jolt/godot-jolt/assets/39361911/ba2844ee-d291-4938-b4aa-b5e50172de1b

Issue can be reproduced by moving an object with, say, `rigidbody.constant_force = Vector3.FORWARD * 800`, then setting `linear_damp` to, say, `30`, then switching between different `physics_ticks_per_second` ranging from `30` to `200`.

**Comment by mihe** [comment]
Thank you for reporting this. That does indeed look to be a discrepancy between the two implementations, which I hadn't noticed before. I'm not seeing it quite as pronounced as what you're showing in your clips, but it's definitely there.

Given that I'm seeing the same behavior in Jolt's `Samples` application, @jrouwe, where a higher update frequency will seemingly result in less effective damping, should this be considered a bug upstream, or is this a known quirk with Jolt?

**Comment by mihe** [comment]
I'm assuming this discrepancy is at least in part explained by the fact that Godot Physics applies the damping before integrating any applied forces, as seen [here](https://github.com/godotengine/godot/blob/dc91479082bd9cd56cd74282573492fe1ba9618a/servers/physics_3d/godot_body_3d.cpp#L632-L651), whereas Jolt seems to do it the other way around, where applied forces are integrated before damping is applied, as seen [here](https://github.com/jrouwe/JoltPhysics/blob/5c9d3b011ab76cdaa05c9e1b1e699f716bd1ddc4/Jolt/Physics/Body/MotionProperties.inl#L126-L137).

This also explains why the scooter is impossible to move at 30 FPS (and a damping of 30) with Jolt, as any applied force is immediately nullified.

Now I'm curious what other engines do in this situation.

**Comment by Jamsers** [comment]
Would there be a more "correct" way to do it or is it just a matter of opinion/engine convention?

**Comment by mihe** [comment]
I'm honestly not sure.

Looking at [the source code](https://github.com/NVIDIA-Omniverse/PhysX/blob/439b4767167e1753d335b613b059140d4d1b4757/physx/source/lowleveldynamics/src/DyBodyCoreIntegrator.h#L39-L81) for PhysX seems to suggest that they do things the same way as Jolt, assuming I'm looking in the right place. Trying this out in Unity seems to support that as well.

Unreal/Chaos also behaves in the same way as Jolt and PhysX, but considering Chaos was meant to replace PhysX I'm not sure that means all that much.

Interestingly the Havok integration in Babylon.js does in fact seem to behave as Godot does, where it does not kill off the velocity completely if the damping matches or exceeds the update frequency, so I'm assuming they also apply the damping first.

The Bullet integration in Godot 3 seems to line up with Godot Physics and Havok as well.

Just swapping the order of these two operations in Jolt does in fact seem to resolve this issue entirely, but whether that has any other ill effects I can't really say.

**Comment by jrouwe** [comment]
Damping uses a pretty coarse first order approximation (the same one as PhysX uses):

https://github.com/jrouwe/JoltPhysics/blob/5c9d3b011ab76cdaa05c9e1b1e699f716bd1ddc4/Jolt/Physics/Body/MotionProperties.inl#L132-L135

This means that if damping * dt is not close to zero then the approximation will become worse and the result will be very frame rate dependent. A damping of 30 is way too high for this approximation to work.

I'd prefer to not make the damping calculations more expensive for everyone and would suggest to pass a damping of 0 to godot-jolt and apply your own damping logic every frame. Basically if you use `velocity *= exp(-damping * dt)` at every step then it should be accurate and frame rate independent.

**Comment by mihe** [comment]
> I'd prefer to not make the damping calculations more expensive for everyone and would suggest to pass a damping of 0 to godot-jolt and apply your own damping logic every frame. Basically if you use velocity *= exp(-damping * dt) at every step then it should be accurate and frame rate independent.

Applying custom damping on the script side of things (or even in Godot Jolt itself) would presumably end up replicating the same order of operations as what Godot Physics does (i.e. damping before force integration), which uses the same cheap approximation as Jolt and PhysX, meaning this discrepancy of big swings from varying update frequency would go away pretty much entirely.

I'm not sure how one would go about emulating Jolt's own application of damping, seeing as how you're doing it after force integration but before any constraint solving (if I'm understanding your job graph correctly) which I'm assuming manipulates the velocity further. If I were to do this within Godot Jolt I would presumably have to stop using `AddForce`/`AddTorque` and integrate those myself (before applying the damping) in order to end up with the same order of operations?

But again, everything seems to work fine (at least in terms of any update frequency swings) if you apply the damping before doing the force integration, even with the same cheap approximation that Jolt uses.

Is there anything inherently wrong with that particular order?

**Comment by Jamsers** [comment]
I just checked and there's a line in the [documentation](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-physics-3d-default-linear-damp) that implies frame rate dependence:

"A value equal to or greater than the physics frame rate will bring the object to a stop in one iteration"

But it was definitely frame rate independent when I tested Godot Physics, the behavior was consistent even with extreme differences in tick rates. So it may be a "bug" on the Godot side - I'll try to create a documentation bug report when I have the time to get confirmation what the "intended" behavior is for Godot as an engine.

**Comment by mihe** [comment]
> I just checked and there's a line in the [documentation](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-physics-3d-default-linear-damp) that implies frame rate dependence:
> 
> "A value equal to or greater than the physics frame rate will bring the object to a stop in one iteration"

Yes, I saw that as well, but I'm not entirely sure how to interpret it in this context, since you're continuously applying a force to the body. As soon as you stop applying the force you should see that the body comes to a complete stop at the next iteration with Godot Physics, so that statement still holds true to some degree.

**Comment by jrouwe** [comment]
> If I were to do this within Godot Jolt I would presumably have to stop using AddForce/AddTorque and integrate those myself (before applying the damping) in order to end up with the same order of operations?

I was not suggesting to do this in godot-jolt but rather in the particular application that @Jamsers is building and only for the objects that are being picked up as part of the 'pick up logic' that would have to run every frame anyway. I doubt that the order of operations matters much in that case, you just want to stop the picked up objects from rotating. Note that picking up could also be achieved by using a Generic6DOFJoint3D that has no degrees of freedom where one side is attached to the object to be picked up and the other side to a kinematic object that you move around depending on mouse input.

As for swapping the order of operations: Both solutions look valid to me and apparently different physics engines have chosen different orders. I'm a bit reluctant to swap it around since I don't know if anyone depends on the current behavior.

**Comment by mihe** [comment]
> I was not suggesting to do this in godot-jolt but rather in the particular application that @Jamsers is building.

Yes, I was trying to say that the more expensive `velocity *= exp(-damping * dt)` isn't necessary if @Jamsers were to go that route, since you end up with the same order of operations as with Godot Physics if you do it from the script side of things, which seems to resolve the problem somehow anyway.

> As for swapping the order of operations: Both solutions look valid to me and apparently different physics engines have chosen different orders. I'm a bit reluctant to swap it around since I don't know if anyone depends on the current behavior.

I would be hesitant about that change as well. I'll just go ahead and apply it from my side, to line up better with Godot Physics. It's not a huge/expensive ordeal.

**Comment by mihe** [comment]
@Jamsers If you need a workaround until I can get another release out, applying this script on any `RigidBody3D` you want to use high damping values on should do the trick:

```gdscript
extends RigidBody3D

func _init():
    custom_integrator = true

func _integrate_forces(state: PhysicsDirectBodyState3D) -> void:
    state.linear_velocity *= maxf(0.0, 1.0 - state.total_linear_damp * state.step)
    state.angular_velocity *= maxf(0.0, 1.0 - state.total_angular_damp * state.step)
    state.linear_velocity += state.total_gravity * state.step
```

**Comment by mihe** [comment]
> with the approach I'm doing I don't have access to `_integrate_forces`

If that happens to be because you're messing with bodies that you can't (or don't want to) set/change the script for, you can also technically use `PhysicsServer3D.body_set_force_integration_callback` to set your own `_integrate_forces`-like callback on any arbitrary `RigidBody3D` reference, like so:

```gdscript
func _my_custom_integration(state: PhysicsDirectBodyState3D, body: RigidBody3D) -> void:
    state.linear_velocity *= maxf(0.0, 1.0 - state.total_linear_damp * state.step)
    state.angular_velocity *= maxf(0.0, 1.0 - state.total_angular_damp * state.step)
    state.linear_velocity += state.total_gravity * state.step

func _grab(some_body: RigidBody3D):
    some_body.custom_integrator = true
    PhysicsServer3D.body_set_force_integration_callback(some_body, _my_custom_integration, some_body)

func _release(some_body: RigidBody3D):
    PhysicsServer3D.body_set_force_integration_callback(some_body, Callable())
    some_body.custom_integrator = false
```

It's not really meant to be used for this purpose, but I believe it should work. Note however that unlike the normal `_integrate_forces` the body won't have synchronized its state with the physics engine by the time that particular callback fires, so make sure to only read/write such state through `PhysicsDirectBodyState3D`.
