### ISSUE TITLE
Editor ray-casts fail when using many bodies

### ISSUE THREAD

**Issue by chirpying** [godot-jolt/godot-jolt#833]
Using Godot 4.2.2

I was getting inaccurate results with some of my raycasts, some of them not colliding even though I had similar raycasts correctly colliding the same object (in different positions).

So I made a little [test project](https://drive.google.com/file/d/109Ushp5Z0aNaIQFfiuIIxQQmYmoHYC8n/view?usp=sharing) to figure out why, with a plugin that creates a grid of collision boxes and then paints those boxes when you hold space. This was the result:

![image](https://github.com/godot-jolt/godot-jolt/assets/68937048/93808673-4174-4326-af34-1f7ff7cc52c9)

A half circle in the +X position (may not be perfect due to my code). When disabling godot jolt, I can paint the entire area.

This also occurs when casting the rays programmatically, straight down.

To test the [project](https://drive.google.com/file/d/109Ushp5Z0aNaIQFfiuIIxQQmYmoHYC8n/view?usp=sharing) I made: open the tester_node, turn the toolbar Edit toggle on, then hold space and paint with cursor.

**Comment by mihe** [comment]
I was wondering when this was gonna come back to haunt me.

The problem seems to be related to the fact that I never call Jolt's `JPH::PhysicsSystem::OptimizeBroadPhase()` method, which means that physics queries within the editor end up traversing an incredibly inefficient broadphase (quadtree) and subsequently blows out its fixed-size stack of 128, resulting in largely arbitrarily broken results.

I had left this out somewhat deliberately, since at runtime the broadphase gets rebuilt/optimized at the first physics tick anyway, which seemed as good of a time as any to do it, and that it wouldn't matter a whole lot if the editor queries were a bit slower than they should be. Obviously this ends up actually breaking things rather than just being slow though, so I'll need to do something about this.

Perhaps I can start/reset some quick timer whenever a new body is added to the scene and run `OptimizeBroadPhase()` when it finishes.

I'd love to hear your thoughts on this @jrouwe.

**Comment by mihe** [comment]
I cooked up a tentative solution in #834, which seems to resolve the issue, by queueing up an `OptimizeBroadPhase()` call for the next frame (`call_deferred`) for any simulation that has bodies added/removed, but only if that simulation is inactive (i.e. editor stuff typically).

It's a fairly scary change, but I don't really see any other way out of this.

**Comment by jrouwe** [comment]
> I'd love to hear your thoughts on this @jrouwe.

As an alternative to your current solution, you could also keep a simple counter that counts the number of bodies that got added since the last physics update and if it gets close to the danger zone (128 * 3) you could trigger the optimize call.

**Comment by mihe** [comment]
I'm a bit hesitant to make assumptions about the particular broad-phase structure Jolt uses, but that is undoubtedly a less scary (and probably more robust) solution.

I figured since this is (and correct me if I'm wrong) theoretically also an issue at runtime if someone decides to add a few hundred bodies, and then immediately perform a physics query on them, I would instead check the counter at the start of every physics query. I then reset the counter if we've already run `OptimizeBroadPhase` or `PhysicsSystem::Update`.

That way you shouldn't have any `OptimizeBroadPhase` calls during normal runtime use unless absolutely necessary, but it will always run in the editor viewport if you're dealing with a few hundred bodies.

**Comment by jrouwe** [comment]
> I would instead check the counter at the start of every physics query, as opposed to when bodies are added. I then reset the counter whenever OptimizeBroadPhase or PhysicsSystem::Update is run.

That sounds like it will work (and apparently it did, given you just submitted the change 😄).

Another thing I just thought of is that you could delay the adding of bodies. Basically you would batch up BodyIDs in an array and you would call `AddBodiesPrepare` / `AddBodiesFinalize` on the batch just before doing a collision check, before removing a body (it could be in the 'to add' list) or before stepping the simulation (and maybe a few other places). For the most part, the Jolt interface doesn't care if a body has been added or not (search for `IsInBroadPhase`), the biggest thing is you can't activate a body before it has been added. Obviously this change is a bit bigger and riskier than the one you just did, but it is more efficient.

**Comment by mihe** [comment]
> Another thing I just thought of is that you could delay the adding of bodies. Basically you would batch up BodyIDs in an array and you would call AddBodiesPrepare / AddBodiesFinalize on the batch just before doing a collision check, before removing a body (it could be in the 'to add' list) or before stepping the simulation (and maybe a few other places). For the most part, the Jolt interface doesn't care if a body has been added or not (search for IsInBroadPhase), the biggest thing is you can't activate a body before it has been added. Obviously this change is a bit bigger and riskier than the one you just did, but it is more efficient.

I did contemplate deferring/batching the creation of the bodies, but I failed to realize that I could just defer/batch the adding of them instead. I do however suspect that it would complicate the logic surrounding the association between a body and its physics space/world/system, given that it could then be in three states (none/created/added) rather than two (none/added), but maybe not by much.

But yeah, deferring stuff in general is scary, and tends to be where bugs show up in my experience, hence why I also chose not to go with the previous `call_deferred` solution.

I think this counter thing should be fine, even if it warrants some explanation in the code.

Thanks for the help!

**Comment by mihe** [comment]
The fix for this can now be found in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).

Note that this version targets the just recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.

A proper release will be out some time around Godot 4.3-stable.

**Comment by mihe** [comment]
I figured I'd give a minor update here, as [0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, so if you've been relying on 0.13.0-beta1 for this functionality until now I would highly recommend updating, as this most recent release includes some important bug fixes.

Note that the release on the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
