### ISSUE TITLE
Softbody properties cannot be changed

### ISSUE THREAD

**Issue by TheContainer** [godot-jolt/godot-jolt#840]
I cannot tell if this is intended behavior or if I am doing something wrong, but I cannot seem to change properties of a softbody in the editor. Also, at runtime, the position of the softbody snaps to the world origin, and if I try to change it during runtime, it keeps snapping back

If this is intended behavior there needs to be more clarity in my opinion.

**Comment by mihe** [comment]
No release has been published with the implementation for `SoftBody3D` yet. You'll need to [build](https://github.com/godot-jolt/godot-jolt/blob/master/docs/building.md) latest `master` from source yourself in order to try that out.

I realize it's confusing that there's no warning or anything saying that it's unsupported in the current release, but unfortunately I couldn't do that due to how the `SoftBody3D` is implemented on the Godot side of things (which differs from all the other physics nodes).

I had hoped to push a new release by now, but there's still some things left to do, and other things have gotten in the way for the past couple of months. Now it's also late enough in the lifecycle of Godot 4.2 that I'd rather just wait until Godot 4.3 is out, which will be a while longer.

Expect a pre-release here on GitHub sometime around Godot 4.3-beta1.

**Comment by TheContainer** [comment]
> No release has been published with the implementation for `SoftBody3D` yet. You'll need to [build](https://github.com/godot-jolt/godot-jolt/blob/master/docs/building.md) latest `master` from source yourself in order to try that out.
> 
> I realize it's confusing that there's no warning or anything saying that it's unsupported in the current release, but unfortunately I couldn't do that due to how the `SoftBody3D` is implemented on the Godot side of things (which differs from all the other physics nodes).
> 
> I had hoped to push a new release by now, but there's still some things left to do, and other things have gotten in the way for the past couple of months. Now it's also late enough in the lifecycle of Godot 4.2 that I'd rather just wait until Godot 4.3 is out, which will be a while longer.
> 
> Expect a pre-release here on GitHub sometime around Godot 4.3-beta1.

but why is #503 closed as completed? Is there any issue or pr I can track to see when softbodies are supported?

**Comment by mihe** [comment]
> but why is #503 closed as completed?

Perhaps my previous comment wasn't very clear, but the work for `SoftBody3D` is pretty much done (although not thoroughly tested) on the `master` branch, hence why the issue is closed. Issues are tied to its status in source, not its status in the latest release, just like in Godot itself (or most projects for that matter).

Just keep a lookout for a new release [here](https://github.com/godot-jolt/godot-jolt/releases) or set yourself as a watcher for releases in this repo, by click "Watch" (at the top) -> "Custom" -> "Releases".
