### ISSUE TITLE
Support for tapered capsule shape

### ISSUE THREAD

**Issue by ettiSurreal** [godot-jolt/godot-jolt#846]
Jolt physics states that it supports a tapered capsule shape, which i imagine would be useful for detection cones and bone collision shapes.
Is there anything preventing support other than lack of support in Godot Physics?

**Comment by mihe** [comment]
> Is there anything preventing support other than lack of support in Godot Physics?

No, and extending the built-in physics nodes tends to be more or less impossible due to their reliance on `protected` methods/variables and whatnot that aren't exposed in the bindings.

But even if we disregard that problem, I've tried to refrain from adding stuff to the API that isn't in the default physics API already, so I would suggest making a Godot proposal for this instead.
