### ISSUE TITLE
GodotJolt is crashing the project and can't be opened in the editor, when Godot is a custom 4.2.2 build

### ISSUE THREAD

**Issue by Zylann** [godot-jolt/godot-jolt#847]
Users of my module keep reporting that adding GodotJolt to their project makes the editor crash, and can't be opened afterwards 

https://github.com/Zylann/godot_voxel/issues/637
https://github.com/Zylann/godot_voxel/issues/618#issuecomment-2094960928

I have no idea what I'm supposed to do, because my module isn't doing anything special regarding physics, and the precompiled builds of the engine I provide are made using the 4.2.2 Godot version tag.

The only eventual difference with GodotPhysics would be support for creating shapes in separate threads, but my module specifically avoids that currently, so there is really no reason for it to crash due to a misuse of the API. Also, it seems the crash doesn't even happen due to a use of the API, it looks like a GDExtension loading issue when Godot opens the project.

Edit: might close this issue as it seems to be a double-precision/single-precision mismatch, which might be something to improve on the GDExtension side to tell the user what's wrong instead of crashing. Eventually GodotJolt could also provide a double-precision build in its package?

**Comment by mihe** [comment]
I'm fairly confident about this being due to running it in a double-precision build, so I'll go ahead and close this for now.

The next version (which will target 4.3) will have the `single` feature tag in the `*.gdextension` file (which was only [recently](https://github.com/godotengine/godot/pull/84711) properly supported) to prevent this from crashing at least.
