### ISSUE TITLE
Applying force/torque to `RigidBody3D` does not reset its sleep timer

### ISSUE THREAD

**Issue by boboalice** [godot-jolt/godot-jolt#866]
when using apply_force() on a RigidBody3D in the _physics_process, every 30 frames the body falls asleep and wake up again, causing a jittery movement.
setting can_sleep to false fixes the lag.

**Comment by mihe** [comment]
Please provide a minimal reproduction project that showcases the issue.

**Comment by mihe** [comment]
Oh, nevermind, I managed to reproduce it pretty easily.

That is indeed a bit strange. I would have thought that waking up the body as part of applying the force would reset the sleep timer of the body, but I guess that's not in fact happening?

I'll look into it.

**Comment by mihe** [comment]
It seems this was just me making too many assumptions about the Jolt API, which explicitly does an early out if the body is already active. There is a separate `ResetSleepTimer` method instead.

@jrouwe Obviously changing this would be a breaking change, but is there some performance reason for this? It strikes me as a little bit odd. If someone is explicitly calling `ActivateBody`/`ActivateBodies`, wouldn't the expectation be for it to reset the sleep timer if the body is already active?

**Comment by mihe** [comment]
That part I can understand, which is why I explicitly wake the body up at any applied force/torque already. If I don't, the body ends up being locked in-place until the user explicitly wakes it up (or some collision response happens I guess), which is not how Godot Physics behaves.

Interestingly it seems that Godot Physics is still able to somewhat handle the case you mentioned, where if I apply some very small force, then let the body settle, it'll go to sleep, but if I then amp up the force applied to it then it'll still react to it appropriately, without needing to be woken up explicitly.

So I guess the discrepancy at play here is less about me needing to reset the sleep timer every time a force is applied, but instead the fact that the sleep timer is in fact reset when activating a body with Jolt.

In fact, [this comment](https://github.com/godotengine/godot/blob/b947c53ddc08d4314b2ce70ca1bc2adb37b83c37/servers/physics_3d/godot_body_3d.cpp#L792) seems to tell the story pretty well. Basically, Godot only resets the sleep timer if the sleep test fails, which happens at the end of the physics step, so a body can have a force applied to it, wake up and then fall asleep again, all within the same step.

I'm assuming I can't replicate that behavior without modifying Jolt, if it's even worth replicating to begin with, so perhaps just resetting the sleep timer myself is the better option.

**Comment by jrouwe** [comment]
> What I was referring to in my previous comment was calling ActivateBody on an already active body, and not having its sleep timer reset.

Ah, sorry, I misunderstood. I think you have a valid point here, but I will need to do some investigations to see what side effects this would have. I'm also thinking about adding a parameter `BodyInterface::AddForce(..., EActivation inActivationMode)` to give the caller control if the body should be activated or not.

> Basically, Godot only resets the sleep timer if the sleep test fails, which happens at the end of the physics step, so a body can have a force applied to it, wake up and then fall asleep again, all within the same step, hence why it looks like it's sleeping despite having forces applied to it.

This would be an option, but quite an expensive one because effectively you're waking up the body every frame (=overhead), simulate it, make it sleep again (=overhead) meaning that effectively the body is only reporting that it is sleeping while actually it is simulated and costing even more than a normal simulated body.

> I'm assuming I can't replicate that behavior without modifying Jolt, if it's even worth replicating to begin with, so perhaps just resetting the sleep timer myself is the better option.

Indeed, BodyManager::ActivateBodies calls ResetSleepTimer so it can never go to sleep in the same frame.

**Comment by mihe** [comment]
Yeah, I caught it. :)

Thank you, much appreciated!

**Comment by mihe** [comment]
The fix for this can now be found in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).

Note that this version targets the just recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.

A proper release will be out some time around Godot 4.3-stable.

**Comment by mihe** [comment]
I figured I'd give a minor update here, as [0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, so if you've been relying on 0.13.0-beta1 for this functionality until now I would highly recommend updating, as this most recent release includes some important bug fixes.

Note that the release on the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
