### ISSUE TITLE
`mouse_entered` and `mouse_exited` for CollisionObject3D do not work

### ISSUE THREAD

**Issue by DarkSlein** [godot-jolt/godot-jolt#869]
Signal is not called on Jolt Physics (on Godot Physics everything works)
![image](https://github.com/godot-jolt/godot-jolt/assets/55765623/76ced499-7e3f-4464-b921-a4b61bd06ea0)
```
func _on_static_body_3d_mouse_entered():
	print("Test")
```

**Comment by mihe** [comment]
Would you mind providing a minimal reproduction project? It seems to work just fine for me.

If your camera happens to be inside of another physics body, like a character or something, you will need to set the `ray_pickable` property of that physics body to `false`, since you unfortunately can't change the `hit_back_faces` ray-cast parameter for the camera pick ray (which is what triggers those signals), and `hit_back_faces` behaves slightly different with Godot Jolt.

**Comment by DarkSlein** [comment]
You're right. I set `ray_pickable` to `false` for player body and it worked. Thank you so much!
