### ISSUE TITLE
Add support for AddressSanitizer

### ISSUE THREAD

**Issue by qarmin** [godot-jolt/godot-jolt#873]
I added address sanitizer by modyfing linux-base preset to
```
    {
      "name": "linux-base",
      "inherits": ["platform-base"],
      "hidden": true,
      "condition": {
        "type": "equals",
        "lhs": "${hostSystemName}",
        "rhs": "Linux"
      },
      "cacheVariables": {
        "CMAKE_CXX_FLAGS": "-fsanitize=address",
        "CMAKE_EXE_LINKER_FLAGS": "-fsanitize=address",
        "CMAKE_MODULE_LINKER_FLAGS": "-fsanitize=address",
        "CMAKE_SHARED_LINKER_FLAGS": "-fsanitize=address",
        "CMAKE_MAKE_PROGRAM": {
          "type": "FILEPATH",
          "value": "${sourceDir}/tools/ninja/linux/ninja"
        }
      }
    },
```

not sure why, after finding crash it freeze before printing lines where crash occured

**Comment by mihe** [comment]
I'll see about adding it as a CMake parameter instead. I'd prefer not to add another set of presets, since it would create another combinatory explosion.

The crash you're seeing (since you're now presumably running the `master` branch) is likely happening as part of fuzzing `SoftBody3D`, which I have a fix for lined up in a local branch.

I did also try running your fuzzer with Application Verifier on Saturday, which is similar to Valgrind in that it can detect things like buffer overruns/underruns, use-after-free and probably other stuff as well, and it did seem to pass there. I am a bit curious to see what ASan reports though.

**Comment by mihe** [comment]
I gave this a try (on Windows/MSVC) a while back, but ran into some strange issues that I frankly don't have the time (nor patience) to pursue. Given that something like Application Verifier serves this need for me already fairly well I don't see a compelling reason to spend more time on this.

It's also looking likely that this extension will be migrated to Godot itself in a not too distant future, at which point this repository will be put into maintenance mode, so with that in mind I'll go ahead and close this.
