### ISSUE TITLE
Add CMake option for providing a custom extension API

### ISSUE THREAD

**Issue by cridenour** [godot-jolt/godot-jolt#886]
Rather than require people to fork the forked godot-cpp, they can update `CMakePresets.json` with

```json
    {
      "name": "platform-base",
      "hidden": true,
      "generator": "Ninja Multi-Config",
      "binaryDir": "${sourceDir}/build/${presetName}",
      "cacheVariables": {
        "CMAKE_EXPORT_COMPILE_COMMANDS": true,
        "GODOT_GDEXTENSION_DIR": {
          "type": "FILEPATH", 
          "value": "${sourceDir}/../gdextension"
        }
      }
    },
 ```
 
 and place their dumped extension JSON and headers in a folder they control. 

I admit I don't know CMake well enough to know if there's a better way to customize this without needing to modify Presets but godot-cpp does read that variable.

**Comment by mihe** [comment]
I experimented with adding a new CMake option for providing the `extension_api.json` at one point, same as what godot-cpp does, but ran into problems due to how I manage the external libraries (like godot-cpp), where it wouldn't actually build properly whenever the `extension_api.json` file was modified, so I ended up abandoning that effort.

But yes, I realize it's a bit of a hassle currently. I'll see if I can take another look at it at some point.

(If you're just looking to make a build for Godot 4.3-beta1, I'm in the middle of packaging one as we speak.)

**Comment by cridenour** [comment]
I'm on double precision build with custom modules so I'm always going to be stuck with my own builds I think - but we used the CMake variable for our own extension too.

Your issues with it make sense - I feel like I'm constantly deleting the build cache when working with godot-cpp + CMake.

**Comment by mihe** [comment]
I don't believe you need to target a custom `extension_api.json` just because you have custom engine modules, assuming of course that you haven't modified Godot Jolt to actually make use of them.

I'm pretty sure you should be able to get away with just building a `GDJ_DOUBLE_PRECISION` build of Godot Jolt, or use the prebuilt one that I'm about to publish.

**Comment by cridenour** [comment]
I'll give the prebuilt a shot then - I've been on 4.3 since before I moved to Jolt so I'll test and report back later tonight.

**Comment by mihe** [comment]
You can find the prebuilt one here: [v0.13.0-beta1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-beta1)

**Comment by cridenour** [comment]
Prebuilt worked great! Seems extensions aren't as picky about the JSON as I once believed. 

Simplifies my engine upgrades in the future slightly, thanks!

**Comment by mihe** [comment]
I'm gonna be honest with myself and say that I likely won't get around to doing this, so I'll go ahead and close this.

If someone has a strong need for this I might take another look at it, but given where the winds are blowing it's more likely that this extension will be migrated to Godot (and put into maintenance mode) before I get around to actually doing this anyway.
