### ISSUE TITLE
Can't lock all axes of `PhysicalBone3D`

### ISSUE THREAD

**Issue by Nguyennhatminh3445** [godot-jolt/godot-jolt#891]
The problem with this is I can only made rigidbody3d static there no option to make Physicalbone3d stay in place(static) as you can see here in this video:
https://github.com/godot-jolt/godot-jolt/assets/140886383/031942ec-c374-4e47-954c-acb0eb5e7a9f
So there is an option to make rigidbody freeze(static) but there is no option to make physicalbone3d freeze(static so it is impossible to make physicalbone3d stay in place  when I use godotphysics I still can lock the object on all axes.
I found the cause of this issue there is an update for godotjolt which caused this.
![Capture](https://github.com/godot-jolt/godot-jolt/assets/140886383/927a3b2a-a0a3-411e-89f6-78fb84e96764)
I dont know c++ so I cant modify the source code to fix this.

**Comment by nguyenductien087** [comment]
Ahh I found a solution for this just change this line of code at https://github.com/godot-jolt/godot-jolt/blob/master/src/objects/jolt_body_impl_3d.cpp line 1282 from None to All
![temprary fix](https://github.com/godot-jolt/godot-jolt/assets/140886383/58853b75-3830-4e44-9bda-97273998e5a3)

**Comment by mihe** [comment]
Yes, this is an unfortunate reality right now, due to the way that axis-locking works in Jolt, which differs from how it's implemented in Godot Physics. I've been meaning to make a PR for Godot to add "freezing" to `PhysicalBone3D`, same as what `RigidBody3D` has, but I haven't gotten around to it.

In the meantime you can do the "freezing" yourself instead, by simply doing this:

```gdscript
PhysicsServer3D.body_set_mode(your_physical_bone, PhysicsServer3D.BODY_MODE_STATIC)
```

or if you plan to move the bone around while it's "frozen", you'll want to make it kinematic instead:

```gdscript
PhysicsServer3D.body_set_mode(your_physical_bone, PhysicsServer3D.BODY_MODE_KINEMATIC)
```

**Comment by mihe** [comment]
With this extension now having been merged into Godot in the form of an engine module (see [README](https://github.com/godot-jolt/godot-jolt?tab=MIT-1-ov-file)), it will be considered to be in maintenance mode going forward, where only bug fixes will be considered for merging. As such, I'll go ahead and close this.

This will instead be addressed for the new engine module by adding freezing support to `PhysicalBone3D`, as mentioned in my previous comment.
