### ISSUE TITLE
Crash when `SeparationRayShape3D` collides with compound shape

### ISSUE THREAD

**Issue by Splagoon** [godot-jolt/godot-jolt#893]
Godot 4.3-beta1 crashes using godot-jolt 4.3-beta1 when a body with a SeparationRayShape3D moves towards a concave StaticBody3D.

To illustrate, consider the following scenario from a top-down perspective:
![Godot_v4 3-beta1_win64_1717787966](https://github.com/godot-jolt/godot-jolt/assets/4906921/8a9671b6-daf1-448a-a900-68a6d780e6f9)

The center object is a RigidBody3D with a SeparationRayShape3D as its only collision shape, and the rest is a StaticBody3D with three ConcavePolygonShape3Ds. When the RigidBody3D moves towards the StaticBody3D (downward in the screenshot), Godot crashes:
```
Godot Engine v4.3.beta1.official.a4f2ea91a - https://godotengine.org
Vulkan 1.3.277 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 3080


================================================================
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.3.beta1.official (a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
[3] error(-1): no debug info in PE/COFF executable
[4] error(-1): no debug info in PE/COFF executable
[5] error(-1): no debug info in PE/COFF executable
[6] error(-1): no debug info in PE/COFF executable
[7] error(-1): no debug info in PE/COFF executable
[8] error(-1): no debug info in PE/COFF executable
[9] error(-1): no debug info in PE/COFF executable
[10] error(-1): no debug info in PE/COFF executable
[11] error(-1): no debug info in PE/COFF executable
[12] error(-1): no debug info in PE/COFF executable
[13] error(-1): no debug info in PE/COFF executable
[14] error(-1): no debug info in PE/COFF executable
[15] error(-1): no debug info in PE/COFF executable
[16] error(-1): no debug info in PE/COFF executable
[17] error(-1): no debug info in PE/COFF executable
[18] error(-1): no debug info in PE/COFF executable
[19] error(-1): no debug info in PE/COFF executable
[20] error(-1): no debug info in PE/COFF executable
[21] error(-1): no debug info in PE/COFF executable
[22] error(-1): no debug info in PE/COFF executable
[23] error(-1): no debug info in PE/COFF executable
[24] error(-1): no debug info in PE/COFF executable
[25] error(-1): no debug info in PE/COFF executable
[26] error(-1): no debug info in PE/COFF executable
-- END OF BACKTRACE --
================================================================
[1]    104 segmentation fault  ../Godot_v4.3-beta1_win64/Godot_v4.3-beta1_win64.exe
```

The crash also happens if the moving body is a CharacterBody3D using `move_and_slide()`. As far as I can tell, the crash doesn't occur if the moving body has a different shape type. The crash does not occur when using Godot's built-in physics, which makes me suspect it's a godot-jolt issue. I'm using the 64-bit Windows version of Godot, without Mono support. I'm running on Windows 11 22631.3672 if that's relevant.

Here's a repro project (including godot-jolt made the ZIP too large for GitHub so remember to put 4.3-beta1 in addons/):
[jolt-crash-repro.zip](https://github.com/user-attachments/files/15744094/jolt-crash-repro.zip)

Please let me know if there's any other information I can provide that would be helpful. Thanks!

**Comment by mihe** [comment]
Thank you for reporting this, and for providing the minimal repro.

I can confirm that I can see the crash as well, using your repro, but I don't yet understand why it's crashing.

It's clear that it's caused by #837 though, as it's crashing when trying to get the triangle of the mesh that was hit by the ray-cast, which it can't due to the ID being invalid. I just need to understand why exactly, and why it hasn't happened in my own testing.

**Comment by mihe** [comment]
Ah, right, so it's specifically because the `ConcavePolygonShape3D` shapes are part of a compound shape. That explains why I haven't seen the issue myself, as I typically only have one `ConcavePolygonShape3D` when testing those types of bodies.

That could potentially give you some type of workaround at least, by using a dedicated `StaticBody3D` for all of the `ConcavePolygonShape3D` shapes, in case that's a viable setup for you.

**Comment by mihe** [comment]
@jrouwe I seem to be in a bit of a pickle here, maybe.

It seems that the problem has to do with the fact that I'm using the `SubShapeIDCreator` that's passed in for shape 2 (the `MeshShape` within the `StaticCompoundShape`) in the dispatch function, as seen here:

https://github.com/godot-jolt/godot-jolt/blob/f9a4b2e735a6687cd08e47fc07d25523e5e82157/src/shapes/jolt_custom_ray_shape.cpp#L74

Which I presumably must do in order for the `mSubShapeID2` in the `CollideShapeResult` to be correct at the original callsite, which is `PhysicsSystem::ProcessBodyPair` in this case.

But this obviously means that the compound shape is encoded into `mSubShapeID2`, which means that I can't use it when trying to get the supporting face within the dispatch function:

https://github.com/godot-jolt/godot-jolt/blob/f9a4b2e735a6687cd08e47fc07d25523e5e82157/src/shapes/jolt_custom_ray_shape.cpp#L120-L126

Do you have any suggestions for how to deal with this? Can/should I pop some bits off the `SubShapeID` in some way before passing it into `GetSupportingFace` perhaps?

**Comment by jrouwe** [comment]
I'm not behind my computer now, but I think you have the context of the collision collector. This is a TransformedShape that holds the root shape. Your sub shape ID should be relative to this shape, so if you call GetSupportingFace on that shape you should be good.

**Comment by mihe** [comment]
At first glance that does not seem to be the case, unfortunately. `GetContext()` returns a `nullptr` in this particular situation.

I'll try to take a closer look at why exactly tomorrow.

**Comment by mihe** [comment]
Hm, yeah, I'm not seeing this collector context get set very often. It's only ever set when the query is being done through `TransformedShape`, which isn't the case in `PhysicsSystem::ProcessBodyPair`, as it just uses the dispatch functions instead.

Unless there's some way of concatenating or otherwise transforming the sub-shape IDs, the only alternatives that I can see are either:

1. Do a second `CastRay` if we're meant to collect faces, purely to get the correct `mSubShapeID2`.
2. Revert #837.

I'm thinking that option 2 isn't a terrible idea perhaps. The only reason I added it in the first place was because it seemed like the right thing to do, given that `InternalEdgeRemovingCollector` depends on these faces, but I'm assuming that a `CastRay` hit isn't likely to result in the kinds of hits that would necessitate having internal edges removed anyway?

**Comment by jrouwe** [comment]
Still not behind my computer, so I can't test my suggestion:

Before you do CastRay you can ask the SubShapeIDCreator GetNumBitsWritten, then when you want to get the face you can use SubShapeID PopID with that value. You ignore the return value (because that's the bits leading up to the shape) but pass the 'remainder' to GetSupportingFace

**Comment by mihe** [comment]
> Before you do CastRay you can ask the SubShapeIDCreator GetNumBitsWritten

I'm assuming this can be done at any point, and not just before `CastRay`, seeing as how the `SubShapeIDCreator` is `const`?

But yes, that does seem to work! The value of the remainder from that `PopID` is the same as if I would have just passed a new `SubShapeIDCreator` to `CastRay`.

Thank you!

**Comment by mihe** [comment]
[0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, which includes the fix for this.

Note that the release in the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
