### ISSUE TITLE
`PhysicalBone3D` causes errors about failing to scale body

### ISSUE THREAD

**Issue by nicoszpako** [godot-jolt/godot-jolt#912]
Hello, when I use the physical bones simulation of a Skeleton3D, I get a lot of errors in console while the simulation is running well : 

```
E 0:01:16:0919   try_build_shape: Godot Jolt failed to scale body 'Physical Bone LeftHand:<PhysicalBone3D#88348821897>'. (0.999909, 0.999908, 0.999999) is not a valid scale for the types of shapes in this body. Its scale will instead be treated as (1, 1, 1).
  <Source C++>   src\objects\jolt_shaped_object_impl_3d.cpp:141 @ try_build_shape()
```
![e7924fdec1028054467cd966a58e290f](https://github.com/godot-jolt/godot-jolt/assets/31455037/74b8187b-600a-4cbf-b54f-100d32861bb5)

My bones are all scaled to 1, and their parents too. 
The errors spawn at a rate of the numbers of bones per frame, which makes about 20k errors after ~20 seconds of game running.
I'm using Godot v4.3.beta2 on Windows 10.

**Comment by nicoszpako** [comment]
I could not manage to make a MRP, but as you mentioned it I fixed the issue by orthonormalizing the body_offset of each PhysicalBone3D of my skeleton (I thought it was about their transform but no).

Thanks a lot for your work and for your help !

**Comment by mihe** [comment]
Yeah, it's clear that this error-checking was too aggressive considering Godot's lack of any sort of internal orthonormalization, so it's fairly easy to find yourself with this error if you just rotate something like a `CharacterBody3D` over a couple of thousand frames, which is not ideal.

The author of Jolt was kind enough to make some changes to Jolt itself that will make it possible for me to drastically bump up the tolerance for this error check, so expect that to be in the next release.

Until then you will indeed need to do some sort of orthonormalization yourself.

**Comment by ModularNucleus** [comment]
Yeah, these sorts of things are likely hard to avoid when integrating complex systems. And to be fair, the Godot docs do suggest to orthonormalize when rotating things often, so I probably should have done so from the start.

> The author of Jolt was kind enough to make some changes to Jolt itself that will make it possible for me to drastically bump up the tolerance for this error check, so expect that to be in the next release.

Sounds very good. Godot Jolt and Jolt are excellent.

**Comment by mihe** [comment]
[0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, which includes the fix for this.

Note that the release in the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.

**Comment by HungryHedgehog** [comment]
I am getting this error in Godot 4.4, it seems to be related to scale tracks imported from blender in combination with rigify (hand animation, breathing etc) areas in it are throwing this every frame. Is tehre a fix for this that isn't just not using animations with scale tracks? the ability to lock the scale of children or something would be fine or it simply not throwing an error and just setting it to 1,1,1 would be fine for me.

**Comment by mihe** [comment]
@HungryHedgehog Would you be able to share more details about your particular setup? Like how the affected scene is structured.

There are ways to work around it, with things like `RemoteTransform3D` and the `top_level` property, but I can't give you specifics without knowing how you've structured things.

**Comment by HungryHedgehog** [comment]
Okay I think I have found more info about what is happening. Previously it would constantly tell me that it's an unknown body because I had physics threading activated.
But I think I now know why this is happening, but don't really know how to fix it. I am using an IK rig for a human body so I don't really control the bones of the skeleton. The animations slightly scale some of the bones (I have tried to get rid of it but I think it's from when I had a breathing animation that propagated through the bones?). In Godot I use Bone attachments on the hands to attach weapons to the model, these weapons are frozen rigidbodies so I can drop them when the enemy dies. The melee weapons have an area so they can hit the player. Since the hand slightly scales during the animations the area gets also slightly scaled, seemingly too slightly for Jolt. And instead of just simply turning 1.0007632 into 1.0 as I would expect, it does that but also gives me a dozen error messages every time the animation loops.
I understand that Jolt is a 3rd party engine so I guess this is a Jolt issue then. I don't even think this is a bug, I would simply expect the engine to round it to the nearest displayable float without throwing an error, maybe I am wrong but doesnt this sort of stuff happen constantly in physics engines?
Is there maybe a way to suppress this error message so it doesnt clutter my feed?

**Comment by mihe** [comment]
> I understand that Jolt is a 3rd party engine so I guess this is a Jolt issue then. I don't even think this is a bug, I would simply expect the engine to round it to the nearest displayable float without throwing an error

@HungryHedgehog This isn't a Jolt issue per se. Jolt requires that the shape retains its inherent primitive shape when scaled, but the [specific tolerance](https://github.com/godotengine/godot/blob/46c495ca21f40f57a7fb9c7cde6143738f1652d4/modules/jolt_physics/shapes/jolt_shape_3d.h#L93) and [the error](https://github.com/godotengine/godot/blob/46c495ca21f40f57a7fb9c7cde6143738f1652d4/modules/jolt_physics/shapes/jolt_shape_3d.h#L112-L114) is something that I put in.

I've been wanting to find a better solution to this, because I've had a handful of reports about this since it was first introduced, so I realize it's a point of friction for some. However, I'm not really on board with just removing the error and letting the shape be potentially wildly off from what the user might see/expect. In your case it might be acceptable, for others it might not. It's just a bug report waiting to happen either way.

It could be that allowing the error to be turned off through a project setting is the more pragmatic move, but I fear that people will be too quick to disable it without understanding the often simple mitigations.

> maybe I am wrong but doesnt this sort of stuff happen constantly in physics engines?

I can't speak to how other game engines deal with this, but we put in a relatively generous tolerance specifically to allow things like smaller precision error build-up to slip through without any error, but we had to draw the line somewhere.

It's not even a physics-specific issue if we do include precision errors. Godot's own documentation on 3D transforms talks about [this problem](https://docs.godotengine.org/en/latest/tutorials/3d/using_transforms.html#precision-errors) more generally, recommending things like orthonormalization as one way of dealing with this, as mentioned earlier in this thread.

In your case though, since you have a parent node setting an "invalid" transform on your Area3D, rather than it gradually becoming "invalid" through precision errors, you would need to rely on `Node3D.set_disable_scale`, which will do this orthonormalization for you under the hood instead:

```gdscript
extends Area3D

func _init() -> void:
    set_disable_scale(true)
```

That'll work so long as you're fine with a scale of `(1, 1, 1)` for that particular node.

You can also have your `Area3D` go `top_level = true` when `_ready` and then have a `RemoteTransform3D` sibling that controls it instead, while discarding scaling, but that's a bit more involved.

---

Anyway, I would highly recommend that you create an issue (as a bug report) for this in the Godot repository instead, ideally with some kind of representative minimal repro project. That way more people can pile on if they feel the same way, and we can get some kind of feel for how widespread this frustration is.

**Comment by HungryHedgehog** [comment]
Thanks for the info, I will try out the set_disable_scale that would prob already help me here.
