### ISSUE TITLE
`CharacterBody3D` reports errors about invalid transform/scaling

### ISSUE THREAD

**Issue by samkoesnadi** [godot-jolt/godot-jolt#935]
Does anyone know what this issue might be, and how to fix? Thank you before :)

This happens, seemingly, when my CharacterBody3D get push by a rigid body to the ground. Perhaps for some seconds it gets compressed, and the scale changes.

Jolt version: v0.13.0-beta1
Godot version: 4.3-rc2
 
E 0:05:28:0331   main_character.gd:140 @ _physics_process(): body_test_motion failed due to being passed an invalid transform. A scale of (0.999960, 1.000000, 0.999960) is not supported by Godot Jolt for this shape type. Its scale will instead be treated as (1, 1, 1).
  <C++ Source>   src\spaces\jolt_physics_direct_space_state_3d.cpp:714 @ test_body_motion()
  <Stack Trace>  main_character.gd:140 @ _physics_process()

**Comment by mihe** [comment]
I'm assuming you're encountering this while using `move_and_slide()`?

The fix for this is technically for you to call `orthonormalize()` before you call `move_and_slide()`, as you seem to be ending up with slight numerical inaccuracies in your `global_transform` from accumulated floating-point imprecision, which causes it be slightly skewed and thereby scaled non-uniformly, which Jolt doesn't like.

This has already been resolved in #925 though, as the error-reporting for this is now much less aggressive, but I haven't published a release with it yet. I will hopefully publish one shortly after Godot 4.3-stable is released next week.

See #912 for more information.

**Comment by mihe** [comment]
[0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, which includes the fix for this.

Note that the release in the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.

**Comment by samkoesnadi** [comment]
@mihe that is awesome. I will try it out now. Big thanks for your work!
