### ISSUE TITLE
Ray-casts using `hit_back_faces` will hit the back/inside of all shapes, not only concave ones

### ISSUE THREAD

**Issue by jrouwe** [godot-jolt/godot-jolt#957]
Continuing the discussion from here: https://github.com/godotengine/godot-proposals/issues/7308#issuecomment-2307521547

Will the following PR solve the issue?

https://github.com/jrouwe/JoltPhysics/pull/1228

**Comment by mihe** [comment]
> Will the following PR solve the issue?

Yes.

**Comment by mihe** [comment]
I will mention one other thing though, which complicates this whole thing a bit more, which is the discrepancy with the `backface_collision` property of `ConcavePolygonShape3D`.

This per-shape property (which is disabled by default) controls _all_ back-face collisions in Godot Physics, including ray-casts. This means that even with `hit_back_faces` enabled (which it is by default) on a ray-cast in Godot Physics you won't hit the back-faces of `ConcavePolygonShape3D` (again assuming defaults) whereas you will with this extension.

So basically these two together (`backface_collision` and `hit_back_faces`) act as a logical AND in Godot Physics, and you'll only see a ray-cast hit against a back-face if both are true.

What also slightly adds to the confusion here is that `HeightMapShape3D` has no `backface_collision` property, and essentially behaves as though it's enabled, but I suppose the use-case for toggling back-face stuff with a height map shape is niche at best.

I personally found all this to be quite odd, since you basically have no recourse if you want your ray-cast to hit the back-face of a `ConcavePolygonShape3D` that otherwise shouldn't have back-face collision, so I changed it when I added the double-sided decorator in #551 to instead make `hit_back_faces` completely dominant, and so far I haven't heard a single mention of it.

In hindsight maybe this was questionable though, given the drop-in aspirations, so perhaps it's time to change this if we're fixing this `hit_back_faces` discrepancy as well. It should be as easy as passing a parameter to the `JoltCustomDoubleSidedShape` decorator shape I guess.

**Comment by jrouwe** [comment]
So the PR has been merged and I'm looking at your comments regarding `hit_back_faces`. Looking at your implementation of `JoltCustomDoubleSidedShape` I think you could make it a little bit more consistent by overriding CastRay and flipping the back face mode on the `RayCastSettings` just like you do in `collide_double_sided_vs_shape`. To me it makes sense to do it the way you do, but I think you can easily replicate godot's behavior by doing the AND in `collide_double_sided_vs_shape`.

Jolt's physics update always ignores backfaces as doing collision with back facing polygons can easily get rigid bodies stuck. In that sense the AND is maybe even the safer thing to do. Alternatively (with your current implementation), people who set the `hit_back_faces` property should be really careful when creating a mesh, making sure that there are no locations where a rigid body could get inbetween a back facing and front facing polygon.

**Comment by mihe** [comment]
> So the PR has been merged

Awesome, thank you!

> I think you could make it a little bit more consistent by overriding CastRay and flipping the back face mode on the `RayCastSettings` just like you do in `collide_double_sided_vs_shape`. To me it makes sense to do it the way you do, but I think you can easily replicate godot's behavior by doing the AND in `collide_double_sided_vs_shape`.

Right, that lines up with what I was thinking as well.

> Alternatively (with your current implementation), people who set the `hit_back_faces` property should be really careful when creating a mesh, making sure that there are no locations where a rigid body could get inbetween two back facing polygons.

Just to be clear, `hit_back_faces` is purely a ray-cast property, and with the `backface_collision` property on `ConcavePolygonShape3D` being disabled by default, bodies will not collide with back-faces by default. But (and maybe this was more your point) to actually make use of `hit_back_faces` with Godot Physics you have to enable `backface_collision` on the relevant shapes first, so you do end up exposing yourself to the problem you brought up. Frankly, this might be reason enough to make the breaking change as part of the migration. I'll see about bringing it up at some point.

**Comment by jrouwe** [comment]
Sorry, I meant the 'backface_collision' where I typed 'hit_back_faces' (I corrected the text above).

**Comment by mihe** [comment]
> people who set the `backface_collision` property should be really careful when creating a mesh, making sure that there are no locations where a rigid body could get inbetween two back facing polygons.

I'm assuming there's no reason this shouldn't already be applicable to Godot Physics as well, right, or is this problem inherent to the decorator shape approach that I'm using in this extension in some way?

**Comment by jrouwe** [comment]
> I'm assuming there's no reason this shouldn't already be applicable to Godot Physics as well, right, or is this problem inherent to the decorator shape approach that I'm using in this extension in some way?

Looking through the Godot Physics code it appears that you're right that it would probably also cause issues there.

So then I would say that we should only add a `CastRay` function to `JoltCustomDoubleSidedShape` which will override `mBackFaceMode` to `IgnoreBackFaces` when `backface_collision` is false. That would make it behave as Godot. I would say it's not the most logical implementation, but in the spirit of compatibility probably the best (and perhaps in the future a proposal should be opened to change it).

**Comment by mihe** [comment]
Great, thank you for taking a look. Then we seem to be on the same page. I'll go ahead and make the `backface_collision` change as well.

I'll probably put the current behavior behind some `legacy_ray_casting` project setting, in case anyone becomes upset about losing the ability to ray-cast back-faces without needing to enable `backface_collision`.

**Comment by mihe** [comment]
In case anyone happens to be subscribing to this issue, this change (along with the above mentioned project setting) can now be found in the newly released [0.14.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.14.0-stable) release.

Note that the release on Godot Asset Library is still pending approval, so you might need to download it from GitHub for the time being.
