### ISSUE TITLE
Rotational friction is the opposite of what is expected and default Godot physics

### ISSUE THREAD

**Issue by ryevdokimov** [godot-jolt/godot-jolt#966]
Version: 0.13.0-stable

Project: https://github.com/Open-Industry-Project/Open-Industry-Project

Every roller is an independent rotating RigidBody3D with a dependent cylinder collision shape. 

The box should move in the direction of the skew of the rollers like when default physics is enabled, however when using Jolt Physics the opposite occurs.

![image](https://github.com/user-attachments/assets/3f202b00-6a6f-4385-981a-5101ddaa7d11)

Default:

https://github.com/user-attachments/assets/7703c115-8df6-42db-b0fb-67f872bf4648

Godot Jolt:

https://github.com/user-attachments/assets/9c0b151f-3605-4d00-824d-79122cde7022

**Comment by ryevdokimov** [comment]
I was able to resolve this by unlocking all the angular axes, I don't think they didn't need to be locked in my project in the first place, not sure why result would be different between default and godot jolt, but I'll mark this closed for now.

**Comment by mihe** [comment]
While axis-locking is implemented slightly differently in this extension compared to Godot Physics, the two engines seem to behave largely the same when using it, as showcased by this minimal repro: [conveyor-belt.zip](https://github.com/user-attachments/files/16803351/conveyor-belt.zip)

Axis-locking operates in global-space though, so using it for something like this is not ideal, since you'd be forced to align your rollers with the global axes. The better option would likely be to use a motored 6DOF joint, with the appropriate axes limited. Note that Godot Physics doesn't support 6DOF motors though, whereas this extension does.

I haven't tried your specific project, but if you're relying on [these lines](https://github.com/Open-Industry-Project/Open-Industry-Project/blob/241418d127a5726291e89120bc70eda3ba784234/src/RollerConveyor/Roller.cs#L39-L41) to serve as axis-locking instead I would probably recommend against it, as continuously changing the transform of a dynamic body tends to produce strange artifacts. It might be that is/was the reason you were seeing the friction issues shown in your clips as well.

**Comment by ryevdokimov** [comment]
Makes sense and agreed. I was in the process of reviewing that code. Thanks for looking into it, this project wouldn't be where it's at without this addon.
