### ISSUE TITLE
Erratic detection of animated bodies by Area3D

### ISSUE THREAD

**Issue by vaner-org** [godot-jolt/godot-jolt#970]
Hello. I encountered a bizarre issue and I'm not sure how best to explain or diagnose what could be going wrong.

I've prepared a minimal reproduction project that mimics what I'm encountering in my game. Please download it here: [jolt-area-mrp.zip](https://github.com/user-attachments/files/16825657/jolt-area-mrp.zip). I'm using the newest stable Godot and Jolt releases.

I have two cubes, both animated with an AnimationPlayer. They both turn on the same Z axis over the course of ten seconds, but one turns towards the middle of the Area3D, and the other turns perpendicular to it.

![jolt-area-mrp (DEBUG) 31 Aug 24 11_36_44 PM](https://github.com/user-attachments/assets/08c94a4a-dfc0-4162-b2e0-ea2aad0e1b59)

I have the Area3D set to report the name of any body entering it. Since both are already inside Area3D, under Godot default physics, they are reported once when the game is run, and then never again, while the animation plays.

```
along
perp
```

Under Jolt, along is reported over fifty times, while perp is reported either once or a handful of times, depending on how much of it is inside Area3D.

```
perp
(53) along
```

I'm at a loss as to why this would be happening, since they both remain inside Area3D for the entire duration of the animation.
I'd appreciate any help. Thank you.

**Comment by mihe** [comment]
CSG shapes with collision enabled are effectively `StaticBody3D` under the hood (which is why you need `areas_detect_static_bodies` enabled for this to work in the first place) and translating/rotating a `StaticBody3D` like this is somewhat "undefined behavior" in terms of what you can expect from its collisions/overlaps. They're not really meant to be moved/rotated at all.

If you switch your `along` and `perp` to instead be `AnimatableBody3D` you'll find that the two engines work the same.

(While `AnimatableBody3D` does inherit from `StaticBody3D` it is in fact not a static body, but a kinematic body, so can be thought of more as a "simpler" `CharacterBody3D`.)

**Comment by vaner-org** [comment]
I see, thank you.
