### ISSUE TITLE
RayCast3D.get_collision_shape() reports wrong faceID of -1 from ConcaveShape3D

### ISSUE THREAD

**Issue by 0bjective0pinion** [godot-jolt/godot-jolt#973]
RayCast3D reports a value that is normally reserved for non-Concave collision shapes.

![GD docs](https://github.com/user-attachments/assets/84ac3aa3-2af6-497b-a3a2-857ed817bf86)

I have isolated the issue to Jolt's response to the above scenario

The data was reported with this str() clause: str("Face ID: ", ray_cast.get_collision_face_index(), ", Collider Shape: ", shape.shape)

Jolt:
![in-game-jolt](https://github.com/user-attachments/assets/4c9fae7b-8826-4f9b-b13c-554bf787fb27)

Godot:
![in-game-godotPhys](https://github.com/user-attachments/assets/a7415352-3b86-4868-aa04-83a35b853a1e)

**Comment by mihe** [comment]
Support for `face_index` was only just recently added in #955. I haven't yet published a release with it.

If you need it urgently you can always [build from source](https://github.com/godot-jolt/godot-jolt/blob/master/docs/building.md) yourself (and enable the somewhat costly project setting).

**Comment by 0bjective0pinion** [comment]
Thank you for your answer! 

My hope is that using Jolt will fix an inconsistent collision bug that I have been running into. I'll figure it out on release of the next version.

Have a good one!

**Comment by mihe** [comment]
Support for `face_index` can now be found in the newly released [0.14.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.14.0-stable) release.

Note that the release on Godot Asset Library is still pending approval, so you might need to download it from GitHub for the time being.

Also note that you have to explicitly enable support for it, by enabling the `physics/jolt_3d/queries/enable_ray_cast_face_index` project setting, since it comes at a non-trivial memory cost, as talked about in #702.

**Comment by 0bjective0pinion** [comment]
Sweet!

**Comment by peteski** [comment]
Hey @mihe thanks for getting back to me! 
I went to make a repro project and it worked fine 🤪 

Turns out there must have been some of the old settings hanging around in that project and the option is under both.
<img width="374" alt="Image" src="https://github.com/user-attachments/assets/f87504d6-817b-4914-80e8-0981815dfef5" />

Sorry for the hassle!

**Comment by mihe** [comment]
Yeah, sorry, I contemplated making some sort of migration of the settings from the extension to the built-in module, but I opted not to in the end. Maybe that was a mistake in hindsight.
