### ISSUE TITLE
3D signals fired/not fired

### ISSUE THREAD

**Issue by lyghtkruz** [godot-jolt/godot-jolt#974]
I created a minimum project so that you can see the issue I'm referring to: https://github.com/lyghtkruz/jolt_bug

If you have a RigidBody3D in an Area3D and freeze it.  Default Godot physics do not fire a body_exited signal, but godot-jolt is firing that signal upon the freeze.  It might need a separate bug report but the StaticBody3D that starts within the Area3D throws a body_entered signal and jolt does not throw that signal. 

This is the entire script that I used (the timer is a 2 second one-shot auto start timer.
```
extends Node3D

@onready var timer: Timer = $Timer
@onready var rigid_body_3d: RigidBody3D = $RigidBody3D
@onready var area_3d: Area3D = $Area3D

func _ready() -> void:
	timer.timeout.connect(freeze)
	area_3d.body_entered.connect(entered)
	area_3d.body_exited.connect(exited)

func entered(node: Node3D) -> void:
	print("Node entered: ", node.get_name())

func exited(node: Node3D) -> void:
	print("Node exited: ", node.get_name())

func freeze() -> void:
	print("Freezing")
	rigid_body_3d.freeze = true
```

**Comment by mihe** [comment]
As mentioned [here](https://github.com/godot-jolt/godot-jolt?tab=readme-ov-file#what-else-is-different) `Area3D` detecting static bodies is opt-in through the project setting `physics/jolt_3d/collisions/areas_detect_static_bodies`. If you enable that setting you'll find that the two engines behave the same.

Note that enabling that setting can come at a heavy performance cost if you have big (or many) overlaps between complex static geometry and `Area3D`, so use with caution.

If you don't actually need the `RigidBody3D` to be frozen as _static_ specifically, you can also just set its `freeze_mode` to `FREEZE_MODE_KINEMATIC`, which will make the body kinematic (think `CharacterBody3D` or `AnimatableBody3D`) instead of static, which will work without needing to enable the above mentioned project setting. You still won't have the `StaticBody3D` overlap be reported though.
