### ISSUE TITLE
Include version in GDExtension file

### ISSUE THREAD

**Issue by aogden-zynga** [godot-jolt/godot-jolt#977]
Hello, can you please include the version of Godot Jolt build in godot-jolt.gdextension so it's easier to track? Thanks

**Comment by mihe** [comment]
Funnily enough I've had this exact thought a couple of times over the past few months. Somehow I had convinced myself that Godot would emit error messages if I added my own custom entries to the `*.gdextension` file, but I never actually sat down and tried it.

It turns out that Godot doesn't care at all, so I'm free to add whatever I want in there I guess.

So yes, that should be easy enough to add. I'll go ahead and do just that.

Keep in mind that you can also [do this](https://github.com/godot-jolt/godot-jolt/issues/751#issuecomment-2242691874) to view the version number, but it's not quite as convenient I guess, especially on Linux.
