### ISSUE TITLE
Add max force/torque to springs

### ISSUE THREAD

**Issue by Brokolis** [godot-jolt/godot-jolt#980]
Hello. I was exploring this better and more complete physics engine for Godot, and I found out that there is no way to set the force limit for a positional motor on the `JoltGeneric6DOFJoint3D`. It seems like it was intentionally not implemented, as seen here:
https://github.com/godot-jolt/godot-jolt/blob/8569326393f87521f52e1482c62ad3351a9ab97f/src/joints/jolt_generic_6dof_joint_impl_3d.cpp#L583-L585

**Feature request:** it would be really great, if it would be possible to set the force and torque limits for the positional motors.

I hope I'm just wrong and don't know how to use the joint properly.

Rant (feel free to ignore this): it's kind weird to me that the Jolt-specific `JoltGeneric6DOFJoint3D` joint doesn't really follow the Jolt API directly, exposing every feature as-is, it just seems like more work to abstract it away than just expose the controls (and their caveats) directly. I've ran into the issue of the game engine abstracting away features of the physics engine in Unity and Unreal Engine, and in Godot 4, the built-in physics engine isn't even complete. I just want access to the physics engine so I wouldn't have to implement sub-optimal (and because of my bad math, wrong) integration myself.

Thanks for working on these bindings!

**Comment by mihe** [comment]
> I found out that there is no way to set the force limit for a positional motor on the `JoltGeneric6DOFJoint3D`

Just to be clear, by positional motors you are referring to springs in this case, right? I haven't exposed positional motors in any other form. Normally Jolt would allow you to make a non-sprung positional motor, but that's not possible with this extension.

I'd be fine with adding a `max_force`/`max_torque` to the spring properties. That seems like a fairly innocent addition.

> it's kind weird to me that the Jolt-specific `JoltGeneric6DOFJoint3D` joint doesn't really follow the Jolt API directly

Sure, I get that. The direction of this extension for a good long while now has been to just serve as a drop-in replacement for Godot Physics, no more, no less. In fact, we spent quite some time trying to avoid introducing the `Jolt*` substitute joints in the first place, so they are mostly there as a compromise, and (largely) tries to stick to the same feature set as the default joints.

In the beginning this was mostly a general direction on my part, and I had planned to fill in some minor gaps in the interface, like the lack of a distance constraint and a fixed constraint, but for the past year or so I've been much more aggressive about this. The reason for this being that this extension has been slated to replace Godot Physics 3D (see [this proposal](https://www.github.com/godotengine/godot-proposals/issues/7308) by the Godot production team) as the default physics engine in Godot, and I wanted to avoid (as much as possible) bringing along a bunch of Jolt-specific features in the migration to an engine module, since Jolt will likely end up living side-by-side with Godot Physics as an opt-in experimental option for the foreseeable future, sharing the same physics server interface.

If/when Jolt is eventually made the default physics engine in Godot then there will inevitably be discussions about adding Jolt-specific features, and perhaps even changing/breaking the interface to better adhere to Jolt in general, but it's not clear to me right now how (or to what extent) that will happen exactly.

**Comment by mihe** [comment]
> Hmm, I only see the position motor being described as a spring in [Jolt docs](https://jrouwe.github.io/JoltPhysics/index.html#constraint-motors):

I think that's just meant to describe the general targeting behavior of the motor. As far as I'm aware you can still give Jolt a spring frequency of zero for a position motor, which will make the constraint as hard as the solver will allow for given the time step and number of solver iterations. I guess it just boils down to semantics though, since that effectively means that no constraint is ever truly not sprung.

I am realizing now though that I actually allowed for (and even defaulted to) a spring frequency of zero, which again will effectively give you a "non-sprung" position motor, so it seems I was mistaken either way.

**Comment by mihe** [comment]
The `max_force` and `max_torque` properties can now be found in the newly released [0.14.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.14.0-stable) release.

Note that the release on Godot Asset Library is still pending approval, so you might need to download it from GitHub for the time being.
