### ISSUE TITLE
Add Linux ARM builds

### ISSUE THREAD

**Issue by tinspin** [godot-jolt/godot-jolt#981]
Or so I heard... Raspberry needs your help!

**Comment by mihe** [comment]
Unfortunately I have no way of testing those builds myself, since I don't own a Raspberry Pi, and frankly I wouldn't really have any time to spare for adding support for it even if I did.

Someone did however report adding another CMake preset for Linux ARM64 that seems to have worked somewhat in #763, but I have no idea how well it actually worked. Note however that the `-m64` argument there isn't necessary, since that's an x86 flag.

Anyway, I'll leave this open, but this is unlikely to ever be worked on unless someone else steps in and does the work with complete autonomy.

**Comment by tinspin** [comment]
Nice I'll give it a shoot!

**Comment by mihe** [comment]
Apologies for letting the above mentioned pull request sit around for so long, but time has been a scarce commodity for me these last few months, and additional platform support has been pretty low on my to-do list.

With this extension now having entered into maintenance mode, as a result of having been merged into Godot in the form of an engine module (see [README](https://github.com/godot-jolt/godot-jolt?tab=readme-ov-file)), adding support for this will no longer be considered. Instead I would recommend that anyone still interested in this go and try out the new engine module in Godot 4.4-dev and report any issues that you run into to the Godot repository.
