### ISSUE TITLE
Connecting 2 VehicleBody3D nodes with any joints give weird behaviour.

### ISSUE THREAD

**Issue by dgsdestinygamestudios** [godot-jolt/godot-jolt#990]
Godot version: 4.3
Godot Jolt version: 0.13.0

![Capture](https://github.com/user-attachments/assets/1c974675-57fa-44d1-a27f-164aac8dc8dd)
![Capture1](https://github.com/user-attachments/assets/48a1e3ea-e95f-4c00-90dd-5ec026a21d26)
![Capture2](https://github.com/user-attachments/assets/ab186e24-2b90-44f6-b218-571c5a72d89a)
![Capture3](https://github.com/user-attachments/assets/94e3fff1-fd11-4f84-8a65-39c37a7e3ad8)
![Capture4](https://github.com/user-attachments/assets/4eaf25ad-d9b9-4880-a172-df0b047b8237)
![Capture5](https://github.com/user-attachments/assets/0ae6fe6c-d216-400c-a36d-12ded8374897)
![Capture6](https://github.com/user-attachments/assets/8355690d-fab6-499f-b612-f5c5a5612216)

We're trying to make a semi-truck with a trailer work. Previously on Godot 4.2 and Godot Jolt 0.11.0 - or 0.12.0, I don't exactly remember - it was a walk in the park. Just add collisions and wheels, then join them with a hinge joint and you're good to go.

But now, as you can see above, no matter which joint nodes we used, the behaviour is weird. With hinge joint, trailer locks truck to left or right, then it's impossible to steer. Use any other joint and you'll see the truck breakdancing 😄 

Tried same setup with GodotPhysics, no problem whatsoever. But as we know, GodotPhysics does not work well with stacked rigidbodies and that is the heart of this project.

Any response and possible fixes are welcome.

**Comment by mihe** [comment]
It's hard to say from just the description alone what the issue might be, especially since you mention that it worked fine in previous versions.

I'd appreciate some kind of minimal repro project.

**Comment by dgsdestinygamestudios** [comment]
I was going to add the project ZIP here, but GitHub says file size is too big, so let me explain.

1- Just download Truck Town Demo from the asset library. It'll convert it from 4.2 to 4.3 without any problems.
2- Press play and drive the semi-truck. No problem.
3- Download Godot Jolt from the asset library, then activate.
4- Now try to drive the semi.

**Comment by mihe** [comment]
I changed the Truck Town demo to work better with Jolt a few weeks ago: godotengine/godot-demo-projects#1102

Apparently they haven't released a new version of it yet though, so the version you'll find on the Godot Asset Library won't have the change. You can just clone the repo though, if you want to try the new version.

Part of the problem there was the discrepancy with the ray-cast parameter `hit_back_faces`, where Jolt would hit the back-faces of convex shapes (`SphereShape3D`, `BoxShape3D`, `CapsuleShape3D`, etc.) as opposed to just triangle-based ones (`ConcavePolygonShape3D`, `HeightMapShape3D`) like they do in Godot Physics, which caused problems with the semi-truck as the trailer's collision box would overlap with the ray-casts of the truck wheels, causing the truck ray-casts to hit the back/inside of the trailer's collision box, making it freak out.

That particular discrepancy has been resolved as of #967 though, so that change to the Truck Town demo (adjusting the collision boxes to not overlap with any ray-casts) isn't strictly necessary any longer, but I also haven't found the time to release a new version of this extension yet, so you'd have to [build from source](https://github.com/godot-jolt/godot-jolt/blob/master/docs/building.md) to get that change.

This discrepancy has existed since I first released the extension though, so if you have in fact seen your setup work in earlier versions of Godot Jolt then this couldn't have been the issue. As such, I would still very much like to see some kind of minimal reproduction project. You can omit things like the `.godot` folder, the `godot-jolt` folder and any `.git` folder to get the ZIP file below the size limit.
