### ISSUE TITLE
apply_torque_impulse() affected by global coordinates without 'await'

### ISSUE THREAD

**Issue by Rosinbolle** [godot-jolt/godot-jolt#991]
I am new to github and apologize if my etiquette is off.

Jolt v0.13.0
Godot 4.3

### Introduction
I have had issues with 'torque' and 'impulse' methods in Godot 4.x, wherein RigidBody3Ds receive no rotation or spin from these methods. When I switched to the Jolt physics engine in 4.3, objects rotate again, but not in the expected way. My current implementation uses 'apply_central_impulse()' combined with 'apply_torque_impulse()', where this unexpected behavior persists. 

### The Scenario
A first-person player throws a RigidBody3D (sword). The player instantiates the sword in front of the camera, and then calls a 'yeet()' function on the sword, as seen below:
```

	var weapon = get(weapon_pickup).instantiate()
	get_tree().get_root().add_child(weapon)
	weapon.global_transform.origin = parent.camera.global_transform.origin - (parent.camera.global_transform.basis.z / 3)
	weapon.yeet(-parent.camera.global_transform.basis.z + Vector3(0, 0.2, 0), parent)
```

```
func yeet(direction : Vector3, source : Object):
	
	rotation = Vector3(source.head.rotation.x - 0.5, source.rotation.y, 0)

	apply_central_impulse(
		direction * yeet_strength
	)
	apply_torque_impulse(
		-transform.basis.x * spin_strength
	)
```
	
### The Problem
With this code, I expect the sword to always spin a certain way. However, the rotation appears to be influenced by its global position. i.e. when thrown in the global Z direction, the sword spins as expected, but when thrown in the global X direction, it spins incorrectly. (tested with both 'global_transform.basis' and 'transform_basis' — no apparent difference).

### The Unexpected "Fix"
By using `await get_tree().create_timer(0.01).timeout` or `await get_tree().process_frame` **directly after setting 'rotation'** at the top of the 'yeet()' function, the rotation of the sword works exactly as expected, and is consistent regardless of the direction it is thrown. This leads me to believe there might be a bug in the physics engine.

### Gifs for demonstration
![without await](https://github.com/user-attachments/assets/e02f6132-a630-494d-bb5a-90eba0ab7c33)
![with await](https://github.com/user-attachments/assets/271b9095-a378-4ab7-a85c-111c4eaa375e)
![image](https://github.com/user-attachments/assets/c743c378-2a86-4d16-9867-9e0457f2993c)
![image](https://github.com/user-attachments/assets/e766b0c2-2ceb-4122-9e5b-fa23942e6489)
![image](https://github.com/user-attachments/assets/e3e0d4ed-a6ae-4646-b44f-c876a8105c43)

**Comment by mihe** [comment]
Thank you for all the information, but sadly I'm not sure it's gonna be enough to give a definitive answer here, without some sort of repro project that I can test for myself.

First of all, do you see the same behavior if you switch back to Godot Physics?

> With this code, I expect the sword to always spin a certain way. However, the rotation appears to be influenced by its global position. i.e. when thrown in the global Z direction, the sword spins as expected, but when thrown in the global X direction, it spins incorrectly.

Most of the physics-related methods, including `apply_central_impulse` and `apply_torque_impulse`, operate in global-space.

> (tested with both 'global_transform.basis' and 'transform_basis' — no apparent difference).

You're childing the weapon to the scene tree root, meaning it has no parent node, so you will indeed not see any difference between them, but you should technically be using `global_transform.basis` (or just `global_basis`).

> `rotation = Vector3(source.head.rotation.x - 0.5, source.rotation.y, 0)`

This line is also a bit confusing to me, since you're setting the local (which happens to also be the global) rotation of the weapon to the _local_ rotation of this `head` node.

All-in-all, it's not super clear to me what's going on here. I do know that some transform-related things are deferred in Godot (see [`Node3D.force_update_transform`](https://docs.godotengine.org/en/stable/classes/class_node3d.html#class-node3d-method-force-update-transform)), but it shouldn't be necessary to invoke here.

I would personally try to rewrite that code to...

1. Remove the `rotation = ...` in your `yeet` method
2. Set `weapon.global_transform.basis` (or `weapon.global_rotation` if you prefer) alongside `weapon.global_transform.origin` in your calling method instead.
3. As mentioned above, use `global_transform.basis`/`global_basis` for your `apply_*_impulse` calls.

If that doesn't help, I would need you to share some kind of minimal reproduction project so I can test it for myself on my end.

**Comment by mihe** [comment]
> because `apply_torque_impulse()` (or indeed the 'position' argument of `apply_impulse()`) do not work **at all** for me

Hm, that's very odd. It should work just fine.

> If I still can't get it working, I'd be happy to provide a minimal reproduction project. As I have not done that before, can you clarify what it entails? Would I make a literal Godot project set up exclusively to demonstrate the issue?

Yeah, pretty much. Try to keep it as straight-to-the-point as possible. Ideally it's just a single scene, where you press F5 and immediately see the issue demonstrated, but in this case I guess it's fine if it's a player character that you have to move around.

Note that there is a size limit to the ZIP file, which you upload by dropping it into the comment field here on GitHub, so you'll want to omit things like the `godot-jolt` addon folder, as well as the `.godot` folder and any `.git` folder.

**Comment by Rosinbolle** [comment]
[rigidbody-impulse-reproduction - Copy.zip](https://github.com/user-attachments/files/17444605/rigidbody-impulse-reproduction.-.Copy.zip)

This project is missing the jolt addon folder (versions 0.13.0 and 4.3 still).

It took a bit of trial and error to recreate the problem, but I hope this is useful. Let me know if you need it re-uploaded for any reason. And if it turns out to just be some trivial problem with my implementation I sincerely apologize 😅

**Comment by mihe** [comment]
Thank you for the repro project.

It seems that my statement above about `force_update_transform` not being necessary in this case was incorrect.

Transform changes are only propagated to the physics engine at specific points in the program flow, namely before and after `_process` and `_physics_process`, and since you need your change to the sword's global transform to have made its way to the physics engine by the time you call `apply_torque_impulse` you'll end up getting wonky results if you don't force this propagation to happen inbetween `look_at` and `apply_torque_impulse`.

The issue with Godot Physics not responding to `apply_torque_impulse` at all during its first tick seems to be a known issue, namely this one: godotengine/godot#75934

That issue seems to have to do with how Godot Physics re-calculates the inverse inertia tensor, which is used when calculating the new angular velocity during `apply_torque_impulse`, meaning it's technically stale (identity) unless you wait a little bit (_two_ physics frames) for it to be updated. Note however that this shouldn't be a problem when using Jolt.

So, basically, you can solve this in a number of ways:

You can work around this by setting your transform _before_ you child the node. Note that this means you can't set the _global_ transform, since that requires the node being part of a tree, so you would need to set the _local_ transform. If your sword wasn't top-level you could do some simple math to figure out the desired local transform of the sword, but since your sword in fact happens to be top-level you can also just set it based on the global transform of the camera, sort of contradicting what I talked about above. That would look something like this:

```gdscript
var body := sword.instantiate()
body.basis = camera.global_basis
body.position = camera.global_position + -camera.global_basis.z
get_tree().get_root().add_child(body)
```

That'll result in the sword's global transform being up-to-date immediately, without the need for `force_update_transform`.

Alternatively, if you still want to keep the (global space) `look_at` stuff you were doing, you can just slap a `body.force_update_transform()` inbetween `look_at` and your impulses.

Lastly, if you want something that works across both physics engines, you have no choice but to do what was suggested in godotengine/godot#75934 and do _two_ `await get_tree().physics_frame` inbetween your `look_at` and the impulses, which will take care of both updating the inverse intertia tensor in Godot Physics as well as propagating the transform changes with both engines.

**Comment by Rosinbolle** [comment]
This info will be very useful going forward, thanks for the help.

And thanks for Jolt. Having objects **not** fall through the floor is a great joy.
